### ISSUE TITLE
Automatic detection of the IP interface address fails depending system language settings

### ISSUE THREAD

**Issue by mospaeda** [jacobsalmela/pi-hole#10]
Herebelow the output of ifconfig 
note that Raspberry is set with french configuration
output contains "inet adr" instead of "inet addr" which causes an error in gravity_adv.sh   
piholeIP=$(ifconfig eth0 | awk '/inet addr/{print substr($2,6)}')

--------------------------------------------------------------------------------------------------------------
pi@raspberrypi ~ $ ifconfig eth0
eth0      Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx  
          inet adr:192.168.1.xx  Bcast:192.168.1.255  Masque:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:192676 errors:0 dropped:1 overruns:0 frame:0
          TX packets:161849 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000 
          RX bytes:135021006 (128.7 MiB)  TX bytes:22700864 (21.6 MiB)

--------------------------------------------------------------------------------------------------------------

**Comment by jacobsalmela** [comment]
So if the configuration is French, ```inet addr``` displays as ```inet adr```?  Strange.  I'll look at a better way to get the IP address.

**Comment by mospaeda** [comment]
I proposed and tested (on my configuration) a solution based on your code using environment LANG

**Comment by mospaeda** [comment]
Following sugestion of pizzafrita, I used the hostname -I command that just give the current IP of hostname (independant of language)

**Comment by jacobsalmela** [comment]
That does sound more simple.  I was out of town this week and am pretty busy next week.  So I will look at this then.

**Comment by jacobsalmela** [comment]
This was fixed with #9 by using ```hostname -I```
