### ISSUE TITLE
Lighttpd starts with warning about unknown key.

### ISSUE THREAD

**Issue by bryanscottwalker** [jacobsalmela/pi-hole#101]
Symptom:

Lighttpd reports "WARNING: unknown config-key: url.access-deny (ignored)" when starting or restarting.

Reason:

Lighttpd is not being told to use "mod_access" during startup.

Solution:

server.modules section in /etc/lighttpd/lighttpd.conf should read:

    server.modules = (
            "mod_access",
            "mod_expire",
            "mod_compress",
            "mod_redirect",
            "mod_setenv",
            "mod_rewrite"
    )

**Comment by fidelito** [comment]
Hi,

I am getting 

 (server.c.1295) WARNING: unknown config-key: alias.url (ignored)

fixed it by mod_alias in /etc/lighttpd/lighttpd.conf

so it looks like below:

server.modules = (
        "mod_access",
        "mod_accesslog",
        "mod_auth",
        "mod_expire",
        "mod_compress",
        "mod_redirect",
        "mod_setenv",
        "mod_rewrite",
        "mod_alias"
)

 lighttpd -v
lighttpd/1.4.45 (ssl) - a light and fast webserver
Build-Date: Jan 14 2017 21:07:19

**Comment by fidelito** [comment]
I did between a minute of me posting here I realized that. :) https://github.com/pi-hole/pi-hole/issues/2248
