### ISSUE TITLE
Firewall & DNS routing

### ISSUE THREAD

**Issue by abhivachan** [jacobsalmela/pi-hole#103]
I am not sure it is an issue in pi-hole.net. When I configured the iptables with the below configuration and configured the DNS (pi ipaddress) in my machine, I cannot access internet. I want to secure my pi and as well as I want to use pi-hole.net.  Please help

*filter

#  Allow all loopback (lo0) traffic and drop all traffic to 127/8 that doesn't use lo0
-A INPUT -i lo -j ACCEPT
-A INPUT -d 127.0.0.0/8 -j ACCEPT

#  Accept all established inbound connections
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

#  Allow all outbound traffic - you can modify this to only allow certain traffic
-A OUTPUT -j ACCEPT

#  Allow HTTP and HTTPS connections from anywhere (the normal ports for websites).
-A INPUT -p tcp --dport 80 -j ACCEPT

#  Allow SSH connections
#  The -dport number should be the same port number you set in sshd_config
-A INPUT -p tcp -m state --state NEW --dport 50684 -j ACCEPT

#  Allow ping
-A INPUT -p icmp --icmp-type echo-request -j ACCEPT

#  Log iptables denied calls
-A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7

#  Drop all other inbound - default deny unless explicitly allowed policy
-A INPUT -j DROP
-A FORWARD -j DROP

COMMIT

**Comment by dschaper** [comment]
Are you getting DNS resolution errors? What do you mean exactly when you say that you cannot access the internet? Can you ping 8.8.8.8 from a machine behind the firewall? The ping can help diagnose if this is a DNS issue or a firewall issue.

**Comment by abhivachan** [comment]
It is because of bad firewall settings and it is corrected. It is working fine.
