### ISSUE TITLE
Script is looking for default user "pi"

### ISSUE THREAD

**Issue by abhivachan** [jacobsalmela/pi-hole#104]
While installing i have noticed that the script is looking for default user "pi" and try to use "UserMod". As part of security improvement, my suggestion it is better to get the username at the time of installation like "Static IP address".

Log details are below

Creating config file /etc/php5/cgi/php.ini with new version
update-alternatives: using /usr/bin/php5-cgi to provide /usr/bin/php-cgi (php-cgi) in auto mode
update-alternatives: using /usr/lib/cgi-bin/php5 to provide /usr/lib/cgi-bin/php (php-cgi-bin) in auto mode
Setting up php5 (5.4.45-0+deb7u2) ...
Setting up spawn-fcgi (1.6.3-1) ...
update-alternatives: using /usr/bin/spawn-fcgi.standalone to provide /usr/bin/spawn-fcgi (spawn-fcgi) in auto mode
update-alternatives: warning: not replacing /usr/share/man/man1/spawn-fcgi.1.gz with a link
usermod: user 'pi' does not exist
dnsmasq: unrecognized service
Stopping web server: lighttpd.

--------------------  Code in basic-install.sh
sudo usermod -a -G www-data pi
--------------------  Code in basic-install.sh

**Comment by jacobsalmela** [comment]
We are planning to [create a pihole user](https://github.com/jacobsalmela/pi-hole/pull/67#issuecomment-161160057) so this won't be an issue after that.
