### ISSUE TITLE
dnsmasq.conf has hardcoded interface

### ISSUE THREAD

**Issue by dschaper** [jacobsalmela/pi-hole#105]
`dnsmasq.conf` is set to `interface=eth0` which may not be the interface chosen by the install. (Also, it may be better to install a `pihole-dnsmasq.conf` under the `/etc/dnsmasq.d/` directory instead of replacing the existing `dnsmasq.conf`

**Comment by jacobsalmela** [comment]
This might be why some users are having issues with Internet access.  They might have selected a different interface than `eth0`...

There is probably a way to edit the file using `sed` with the `-i` option here.   This would be part of the automated installer.

**Comment by dschaper** [comment]
Yeah, I'm thinking that the auto-install should save the interface selected to the temp file for gravity, and then the ip address could be determined from the interface with that updated ip finding routine. The `dnsmasq.conf` template could have a dummy value inserted for the interface like `%INT%` or something that would be easy to parse with sed, and replace with the value exported to the temp file.
