### ISSUE TITLE
gravity.sh won't make gravity.list on initial install if custom IP is made

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#111]
If a user chooses to set their own IP address during the install.  `gravity.list` does not get created.  I think it has something to do with there being two IP addresses.

On a fresh install, I get this output:
```
** Neutrino emissions detected...
** Creating pihole directory...
  Getting adaway.org list: List updated, transport successful...
  Getting adblock.gjtech.net list: List updated, transport successful...
  Getting hosts-file.net list: List updated, transport successful...
  Getting www.malwaredomainlist.com list: List updated, transport successful...
  Getting pgl.yoyo.org list: List updated, transport successful...
  Getting someonewhocares.org list: List updated, transport successful...
  Getting winhelp2002.mvps.org list: List updated, transport successful...
** Aggregating list of domains...
rm: cannot remove ‘/etc/pihole/latentWhitelist.txt’: No such file or directory
** Whitelisting 7 ad list sources...
** Formatting domains into a HOSTS file...
cat: /etc/pihole/pihole.3.eventHorizon.txt: No such file or directory
** 77019 domains being pulled in by gravity...
** 68022 unique domains trapped in the event horizon.
```
So the `eventHorizon.txt` seems to be missing.

Trying to run `gravity.sh` again, gives this:

```
awk: line 1: runaway string constant "192.168.1. ...
```

**Comment by dschaper** [comment]
This is on the devel branch, correct?

**Comment by jacobsalmela** [comment]
No, I just tried it using `curl -L | install.pi-hole.net`...I'm trying to figure out why it happens now so new users don't get confused.

**Comment by dschaper** [comment]
I'm working it too, if you check `/etc/pihole` the file is there, for some reason it's not `cat`ing the file.

**Comment by dschaper** [comment]
And `gravity_unique()` is working, it reports a number of domains, it uses that same `$eventHorizon` file for it's linecount?

**Comment by jacobsalmela** [comment]
What is in the file on your system?

**Comment by dschaper** [comment]
`/etc/pihole/pihole.3.eventHorizon.txt`

**Comment by dschaper** [comment]
** Aggregating list of domains...
     rm: cannot remove ‘/etc/pihole/latentWhitelist.txt’: No such file or directory
     ** Whitelisting 7 ad list sources...
     ** Formatting domains into a HOSTS file...
     cat: /etc/pihole/pihole.3.eventHorizon.txt: No such file or directory
     ** 77019 domains being pulled in by gravity...
     ** 68022 unique domains trapped in the event horizon.
     kill: invalid argument H

**Comment by jacobsalmela** [comment]
Same message here.  My `/etc/pihole/pihole.4.accretionDisc.txt` is empty, but `/etc/pihole/pihole.3.eventHorizon.txt` does have just the domains...  I'm not sure why it can't `cat` it.

**Comment by jacobsalmela** [comment]
I'm running a `bash -x` now for more clues.

**Comment by dschaper** [comment]
I'm on the development branch, and basic-install.sh is `curl`ing `https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/gravity.sh`. I was wondering why any local changes I made to `gravity.sh` didn't show unless I ran `gravity.sh` locally, and that copy is in line with development. Any local changes get overwritten by the `curl`.

**Comment by dschaper** [comment]
I think there's something in the `$piholeIP` detection routine that is also wonky, (may no be related). If I run `basic_install.sh` a few times with unique ip's each time and then run with the default and no custom ip, whiptail lists all the ip's...

**Comment by jacobsalmela** [comment]
I'm trying to find when it last worked as a point of reference.  But that `$piholeIP` would probably be part of that `runaway string` error.

**Comment by dschaper** [comment]
Did find a new bug though, take a look at your `/etc/dhcpcd.conf` file, `basic-install.sh` writes to that file every time the script is run, even if the address is already there.

**Comment by jacobsalmela** [comment]
Haha, I just noticed that, too.

**Comment by jacobsalmela** [comment]
`$eventHorizon` gets created in `gravity_unique()`.
`gravity_hostFormat()` `cat`s `$eventHorizon`
`gravity_advanced()` runs `gravity_unique()` to make the file, but it runs after `gravity_hostFormat()` so the file doesn't exist yet.

**Comment by dschaper** [comment]
Okay, swapping those two function calls in gravity.sh and running locally clears the `cat` bug, but there still is the runaway string constant error... Still working it...

**Comment by jacobsalmela** [comment]
How did you swap them?

**Comment by dschaper** [comment]
In my local copy of `gravity.sh` I switched the order of those two function calls. Then I changed into the directory where my local copy of `gravity.sh` is and ran `./gravity.sh`, otherwise the copy of `gravity.sh` in `/usr/local/bin` would run and the changes wouldn't be picked up. Had to put a `echo "TEST"` to debug which version of `gravity.sh` was running.
