### ISSUE TITLE
gravity.sh remove tmp ip

### ISSUE THREAD

**Issue by ricardo777** [jacobsalmela/pi-hole#114]
gravity.sh

the tmp IP is removed:

rm $piholeIPfile

but when running the script again for updates my ip is not updated properly on debian VPS not a Raspberry.

Also the IP is not recognised properly, so I created the piholeip.txt file myself and removed the: rm $piholeIPfile text on the gravity file.

Now a rerun of the script works.

Also running on venet0:0 on the VPS

**Comment by jacobsalmela** [comment]
So does [these lines](https://github.com/jacobsalmela/pi-hole/blob/master/gravity.sh#L14-L17) not properly get your IP address?  The `/tmp/piholeIP` should only exist upon the initial install.

**Comment by dschaper** [comment]
And which VPS are you using? I can spin up a Digital Ocean droplet, or an AWS EC2 instance to test if needed.

**Comment by ricardo777** [comment]
Also saying this for a Debian VPS running on OpenVZ on venet0:0 nog dev

Digital Ocean is KVM if I am correct,

https://github.com/jacobsalmela/pi-hole/blob/master/gravity.sh#L14-L17 is not working I get the error: Error: either "dev" is duplicate, or "1460" is a garbage.

Running ip route get 8.8.8.8 | awk '{print $5}' does work and get the right server IP.

**Comment by dschaper** [comment]
What is the output of `ip route get 8.8.8.8 | awk '{print $5}'`?

**Comment by ricardo777** [comment]
root@pihole:~# ip route get 8.8.8.8 | awk '{print $5}'
IP Here (the IP is right masked for privacy)
1460

**Comment by dschaper** [comment]
Okay, it should be getting the interface with that command. What is the output of `ip route get 8.8.8.8`? What we are looking for is the interface name, and it's in a different location for OpenVZ based systems it appears.

**Comment by ricardo777** [comment]
Here it is:

8.8.8.8 dev venet0  src IPHERE
    cache  mtu 1500 advmss 1460 hoplimit 64

If you need a test environment I can provide a VPS

**Comment by dschaper** [comment]
Thanks for the output, I'll see what I can do to accommodate that environment. I may need to take you up on the offer for the VPS though, I'll need to see how the environments are set up for the systems I have access to. I normally get a response of `8.8.8.8 via 192.168.1.1 dev eth0  src 192.168.1.156` so I can see why you are getting errors.

**Comment by dschaper** [comment]
While I'm checking, what is the output then of `ip -o -f inet addr show dev venet0`?

**Comment by ricardo777** [comment]
2: venet0    inet 127.0.0.2/32 scope host venet0
2: venet0    inet IPHERE/32 brd IPHERE scope global venet0:0

**Comment by dschaper** [comment]
Okay, that's a bit different than what I am targeting too. 
`2: eth0    inet 192.168.1.111/24 scope global secondary eth0 valid_lft forever preferred_lft forever`

**Comment by ricardo777** [comment]
Yes result is very different as I see now.

I have checked the linux version and it is not Debian sorry for that one it is:

Ubuntu 14.04.3 LTS \n \l

**Comment by dschaper** [comment]
Okay, can you check `ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++)if($i~/dev/)print $(i+1)}'`

**Comment by ricardo777** [comment]
root@pihole:~# ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++)if($i~/dev/)print $(i+1)}'
venet0
root@pihole:~#

IP is active on venet0:0 if correct.

**Comment by dschaper** [comment]
Okay, I think I have a patch that will work, I'll submit a pull to Jacob.

**Comment by ricardo777** [comment]
Ok great =)

**Comment by dschaper** [comment]
Thanks for you help!

**Comment by ricardo777** [comment]
No problem, I think this is a great project.

**Comment by dschaper** [comment]
IPv4dev=$(ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++)if($i~/dev/)print $(i+1)}')
     piholeIPCIDR=$(ip -o -f inet addr show dev $IPv4dev | awk '{print $4}')
     piholeIP=${piholeIPCIDR%/*}

**Comment by ricardo777** [comment]
I have run the code but does it need to output  something because it generates no output.

**Comment by ricardo777** [comment]
The code: ip -o -f inet addr show dev $IPv4dev | awk '{print $4}'

Does print 2 ips:
127.0.0.2/32
ServerIP/32

**Comment by dschaper** [comment]
Okay, I think I have a proper fix, can I take you up on the offer of the VPS for about 5 minutes?

**Comment by dschaper** [comment]
`ip -o -f inet addr show dev venet0 | awk '{print $4}') | awk 'END {print}'`

**Comment by ricardo777** [comment]
root@pihole:~# ip -o -f inet addr show dev venet0 | awk '{print $4}') | awk 'END {print}'
-bash: syntax error near unexpected token `)'

Can you share IP somewhere so I can allow in firewall.

**Comment by dschaper** [comment]
23.241.237.87

**Comment by dschaper** [comment]
`ip -o -f inet addr show dev venet0 | awk '{print $4}' | awk 'END {print}'` I left an extra ')' in there, fixed it.

**Comment by dschaper** [comment]
My email is `dschaper@ganymeade.com`.

**Comment by ricardo777** [comment]
No error I have this:

	IPv4dev=$(ip -o -f inet addr show dev venet0 | awk '{print $4}' | awk 'END {print}')
	piholeIPCIDR=$(ip -o -f inet addr show dev $IPv4dev | awk '{print $4}')
	piholeIP=${piholeIPCIDR%/*}

But the list is without ip so still not working.

I will email you the credentials. I need to go now I am back later.

**Comment by dschaper** [comment]
Okay, thanks for your help.

**Comment by ricardo777** [comment]
Have mailed the credential can you login? Then I will go.

**Comment by dschaper** [comment]
I'm in, thanks again.

**Comment by ricardo777** [comment]
No problem, also thank you.

**Comment by dschaper** [comment]
Okay, confirmed fix works on OpenVZ platform. Thanks for the VPS use, and I left the fix there, your `gravity.sh` is working and `gravity.list` is formatted correctly.

**Comment by dschaper** [comment]
@ricardo777 Let me know if I can get a few more minutes on the VPS, I need to find a way to grab the default gateway, it looks like the output for the Raspbian command doesn't show the same on the OpenVZ platform. This affects the basic-install script and the .deb I'm working on...

**Comment by ricardo777** [comment]
Be my guest =)

**Comment by ricardo777** [comment]
If you want by the way I can provide a PvXen vps also?

**Comment by dschaper** [comment]
I appreciate all the assistance...

**Comment by ricardo777** [comment]
Have mailed you with credentials, for PVXen

**Comment by dschaper** [comment]
Thanks, it looks like the default gateway is set by interface and not by IP address. I'll need to check the documentation to see if that is a portable way to work. May make things a little easier. Have you rebooted the server lately? I cleared another small bug that I'm fixing that would leave multiple entries in `/etc/dhcpcd.conf`.

**Comment by ricardo777** [comment]
Yes few days ago, you may reboot if you think it is necessary no worries.

**Comment by dschaper** [comment]
Okay, you look good. The issues left are with the install scripts, and you won't be needing to run that again unless there are some changes. Can you check and see if ads are being blocked? Check the pihole.log and see if it's showing hits if you can.

**Comment by dschaper** [comment]
Making a note for myself, `ip route list` will show only the interface if an ipv4 /32 is assigned.

**Comment by ricardo777** [comment]
ADs are still blocked great =) mahakala list is massive indeed.

**Comment by dschaper** [comment]
Good, and watch mahakala, it can block a lot of legitimate sites, you might have to manually whitelist some domains if you want to use that list.

**Comment by ricardo777** [comment]
Yes I am testing it, maybe it is a good idea that you make a whitelist for everyone for pihole. But that would be hard because the list is so enormous.

**Comment by dschaper** [comment]
I think Jacob had an idea about a way to share if lists were blocking good domains. Maybe a Wiki entry if you find anything that you'd like to share?

**Comment by ricardo777** [comment]
Yes that would be great also if more users can be participate. I will test it out and when I see a wrong one blocked I can add it.

**Comment by jacobsalmela** [comment]
I was testing out #117 and get the same [`is a garbage` error](https://github.com/jacobsalmela/pi-hole/issues/114#issuecomment-162309599).

**Comment by dschaper** [comment]
That PR just basically rebases the development branch, the fixes come in the later pull requests.

**Comment by jacobsalmela** [comment]
OK, so I should merge them in order?

**Comment by dschaper** [comment]
And it may throw that error if the version of `basic-install.sh` is pulling the old `gravity.sh` from `master` that doesn't have the fixes. I ran into that a few times.

**Comment by dschaper** [comment]
Yeah, #117 gets a baseline to master, #118 should fix the garbage error and #119 fixes running on a non-raspbian platform.

**Comment by jacobsalmela** [comment]
Cool.  Thanks!

**Comment by dschaper** [comment]
Not a problem!
