### ISSUE TITLE
Check for pre requirments before installing

### ISSUE THREAD

**Issue by ricardo777** [jacobsalmela/pi-hole#115]
Running this script on a Debian minimal VPS.

When running the basic-install.sh script.

It abort because of missing dependencies like:

whiptail
curl
sudo
unzip

when missing unzip the web admin part is not functioning.

**Comment by jacobsalmela** [comment]
Are you talking about the install script?  If so, then this is only for Raspbian right now.  Please re-open if this is not the case.  Or create a new feature request.
