### ISSUE TITLE
Pi-hole web interface not updating stats

### ISSUE THREAD

**Issue by agietl** [jacobsalmela/pi-hole#126]
I performed a fresh install of Raspbian (Jessie).
Installed pi-hole, curl -L install.pi-hole.net | bash
configured static IP and rebooted. 
Then configured DNS in my router. 
I have verified that ads are being blocked. However when I view the Pi-hole Admin Console web interface, it is not updating any statistics other than the total number of Domains being blocked.
I noticed I am running Pi-hole Version 2.1. 
Not sure if this is a bug or not. I have done this exact process on 2 separate Raspberry pi units and have the same results.

**Comment by jacobsalmela** [comment]
This is usually because of the permissions.  The installer usually takes care of this, unless we missed something with all the recent changes.  Run these commands and try it again:

```
sudo touch /var/log/pihole.log
sudo chmod 644 /var/log/pihole.log
sudo chown dnsmasq:root /var/log/pihole.log
```

**Comment by dschaper** [comment]
I just did a fresh install of Raspbian Jessie-Lite and then ran
` curl -L install.pi-hole.net | bash` and installed with a static IP address. Running a `tail -f /var/log/pihole.log` does show activity, however a visit to `http://192.168.1.165/admin` does show all 0's for blocking stats.

I haven't had a chance to look at the web code so I'm not sure where the bug might be yet, but I'll try to take a look and see... There are a suprpising number of ad-sites that are serving via IPv6 now though, so some ads do get through. (That's another discussion thread though, lol...)

**Comment by agietl** [comment]
I ran those commands and wanted to confirm that fixed the problem!

**Comment by dschaper** [comment]
Okay, here's the default permissions for the log file:
`-rw-r----- 1 dnsmasq root 1085628 Dec 16 04:50 /var/log/pihole.log`
Looks like we need to update the install to `chmod` that file. I think I took that out because `dnsmasq` auto-creates the file, but the permissions will need to be more open for the `pihole` user to function.

**Comment by zacklb** [comment]
`chown www-data:www-data /var/log/pihole.log` worked for me

**Comment by jacobsalmela** [comment]
That works, too.  But we should replace the commands that were removed previously back into the installer.
