### ISSUE TITLE
Busybox httpd as lightweight webserver

### ISSUE THREAD

**Issue by dschaper** [jacobsalmela/pi-hole#128]
Since we're just serving the admin features and a static image for ad replacement, what do you think about using the built-in httpd server that comes with busybox? Do we need a big http daemon when a small one would pull off some of the load? Might not make a big difference on the Pi 2B's but on a single core Zero or the older Pi's it may help responsiveness.

**Comment by meliton** [comment]
I was thinking about the same thing. I'm not sure if Busybox `httpd` runs multi-threaded. I use `httpd` to serve single files but I've seen it bog down serving multiple clients. I've seen netcat, python, and perl set up as one-liner web servers. I remember pixelserv as an option for ad-blocking but I'm not sure why it's not being used.

**Comment by jacobsalmela** [comment]
Speaking to Pixelserv, I decided not to use it based on research I did when making the Pi-hole because people said it was kind of slow.

The [`netcat` Webserver](http://jacobsalmela.com/create-a-website-on-your-mac-without-a-webserver/) is pretty cool:

```
while true;do sudo nc -l 80 < index.html;done
```

It might be worthwhile to do some testing with all of them.

One thing I like about `lighttpd` is the ability to add X-Headers, redirects, https, and the other features of a regular Web server.

**Comment by dschaper** [comment]
I got the idea while playing with Docker on the RasPi. There's a docker image that has just the busybox server and I thought that it would be something to look at for PiHole. I'll play around some and see what comes through. 

I'll take a look at `Monkey` too, that is supposed to be pretty light and good for static site servicing on the Raspberry.

**Comment by dschaper** [comment]
Monkey looks pretty good as far as a server for admin functions. It is missing the ability to do custom X-Headers currently, but it looks like that is on the target goal for the next point release. As for busybox, I'm trying to see if it can serve up a base64 encoded 1x1 transparent pixel. It looks like busybox is in the raspbian/debian repository so it would be easy to add to the dependencies, but Monkey looks to be still requiring another entry in the sources.list so I'm not sure how that would work for installation purposes. Still playing with that...

**Comment by jacobsalmela** [comment]
A base64 encoded gif would be pretty fun.  One other thing I like about `lighttpd` is the logging functionality.  Not only is it useful for the Web interface, but we can also use it for [data visualization](http://jacobsalmela.com/visualize-ads-blocked-in-real-time-using-pi-hole-and-logstalgia/) and [real-time stats](http://pi-hole.net/faq/install-the-real-time-lcd-monitor-chronometer/).

A larger change like this will be farther down the road as I am planning on working with [Optimal's new project](http://optimal.com/our-product/), so I would like to minimize large changes.  

I have mentioned it before, but my biggest proponent for the project is stability.  Even if that means slower feature releases and fixing bugs right away.

**Comment by Mcat12** [comment]
It is nice to use the pi as a web server and an ad blocking machine with lighttpd.

**Comment by dschaper** [comment]
Yeah, the idea was mostly for the Zero, but it seems to be able to handle the load without problems. So  this will stay on the back burner for now until @jacobsalmela get's the new Optimal integration and we see how that goes.

**Comment by dschaper** [comment]
I'm going to close this out, as I don't think it's going to be as useful as I originally though. May revisit later...
