### ISSUE TITLE
Use Pi Hole with a VPN to block ads on all traffic when connected.

### ISSUE THREAD

**Issue by Josh-Miller** [jacobsalmela/pi-hole#129]
I am currently using my Raspberry Pi as a VPN service, and would like to couple ad blocking into the pi. Is there an easy way to say all traffic coming through the VPN would run through Pi Hole dnsmasq?

**Comment by jacobsalmela** [comment]
As long as the Pi-hole is set at the DNS server in your DHCP options that are given to clients when they connect to the VPN, ad-blocking should commence.

**Comment by Josh-Miller** [comment]
Ah makes sense! Thanks, it's an awesome project!

**Comment by jacobsalmela** [comment]
I'm so glad you like it.  It really makes it fun to continue working on.
