### ISSUE TITLE
problems with cwtv

### ISSUE THREAD

**Issue by chromerobv** [jacobsalmela/pi-hole#130]
started having problems with watching videos on cwtv and i can not figure out what to whitelist. 
has anyone else had this problem?

**Comment by dschaper** [comment]
What kind of issuses have you been running into?

**Comment by dschaper** [comment]
Are you getting the "Oops, you have an ad-blocker" error, or the "Graphics file failed to load" error? Just a quick `grep` of the `/var/log/pihole.log` pulled up some domains that may be part of the issue.

     Dec 21 01:46:23 dnsmasq[10630]: /etc/pihole/gravity.list beacon.krxd.net
     Dec 21 01:46:23 dnsmasq[10630]: /etc/pihole/gravity.list partner.googleadservices.com
     Dec 21 01:46:23 dnsmasq[10630]: /etc/pihole/gravity.list rtd.tubemogul.com
     Dec 21 01:46:23 dnsmasq[10630]: /etc/pihole/gravity.list s.ixiaa.com
     Dec 21 01:46:23 dnsmasq[10630]: /etc/pihole/gravity.list warnerbros.112.2o7.net
     Dec 21 01:46:23 dnsmasq[10630]: /etc/pihole/gravity.list adadvisor.net
     Dec 21 01:46:24 dnsmasq[10630]: /etc/pihole/gravity.list secure.footprint.net

Try those and see if they are triggering the alerts. (I'll try if I get a chance, I should have a few minutes while I'm rendering in a bit...)

**Comment by jacobsalmela** [comment]
I used a [Chrome extension to find out what domains may need to be whitelisted](http://pi-hole.net/faq/how-do-i-whitelist-or-blacklist-a-webiste-or-domain/).  This is a lot easier than `tail`ing the log.
```
www.google.com
www.cwtv.com
pagead2.googlesyndication.com
images.cwtv.com
media.cwtv.com
bs.serving-sys.com
cdn.krxd.net
b.scorecardresearch.com
www.google-analytics.com
partner.googleadservices.com
warnerbros.112.2o7.net
securepubads.g.doubleclick.net
tpc.googlesyndication.com
userdata.krxd.net
beacon.krxd.net
idpix.media6degrees.com
cm.g.doubleclick.net
pixel.advertising.com
tacoda.at.atwola.com
ajax.googleapis.com
```

Please try to whitelist those domains and re-open if it does not resolve the issue.

**Comment by dschaper** [comment]
Yeah, that extension is much easier!
