### ISSUE TITLE
Change the lighttpd web server to nginx

### ISSUE THREAD

**Issue by przemasisko** [jacobsalmela/pi-hole#131]
I'm using nginx web server.
Has anyone converted a rule of lighttpd to nginx? Next to another functioning website.
Very thanks!

$HTTP["url"] =~ "^/pihole/" {
        expire.url = ("" =&gt; "access plus 1 days")
}
 
$HTTP["host"] =~ ".*" {
     url.rewrite = (".*" =&gt; "pihole/index.html")
}

**Comment by jacobsalmela** [comment]
I'm not familiar with nginx. Have you look [at this](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite)?

**Comment by przemasisko** [comment]
I tried to write different rules rewrite, but to no avail.
I solved it in a simple way. Under a 404 I strapped a blank web page and it works well.

**Comment by jacobsalmela** [comment]
Yes, that will work, too.  I have that in my config file to catch any sites that might 404.
