### ISSUE TITLE
Blacklist not working 

### ISSUE THREAD

**Issue by greg5678** [jacobsalmela/pi-hole#132]
I wanted to blacklist a site say www.example.com and I put it in the blacklist.txt file and then ran the gravity.sh file. It didn't work. I went to www.example.com and it loaded the page but it should have been blocked.

**Comment by dschaper** [comment]
There's a couple of troubleshooting step we can take to see if there are any problems. What kind of machine is the client (the machine that you are browsing to `example.com`)? You might need to flush the DNS cache if you visited the site, then blacklisted and finally revisited the site. The address for the site could be in your DNS cache and you're visiting the site with the old DNS information.

**Comment by greg5678** [comment]
I have cleared my computers cache(mac) Chrome. It still loads the site.

**Comment by dschaper** [comment]
Okay, lets take a look at a couple of other items. First, can you `cat /etc/pihole/gravity.list | grep example.com` and see if `example.com` is listed in the `gravity.list`?

**Comment by jacobsalmela** [comment]
@dschaper's suggestions will help us the most.  Your `blacklist.txt` should have one domain per line without any http:// or anything like that.

**Comment by greg5678** [comment]
My blacklist.txt file consists of two domains. They look like this (each domain is different).
www.example.com
www.example.com

**Comment by greg5678** [comment]
Both of the sites use https.

**Comment by jacobsalmela** [comment]
That could be the issue.  We haven't quite nailed down https sites yet...

**Comment by greg5678** [comment]
That may explain it.

**Comment by greg5678** [comment]
Thanks for all you help!

**Comment by greg5678** [comment]
Have you thought of just forcing the connection over http instead of https(the sites won't be viewable anyway)?

**Comment by dschaper** [comment]
@jacobsalmela Can you add an HTTPS milestone? In a pure DNS system it shouldn't matter what the protocol is, all attempts to resolve the domain should return the PiHole IP. Now setting up a pixel-server is another matter, but I'll try to take a look at just blocking the domain completely.

**Comment by dschaper** [comment]
It's looking like the issue may not be https. I set up a `blacklist.txt` with an entry of `www.amazon.com`. Ran `gravity.sh` to repopulate the `gravity.list` and confirmed that `www.amazon.com` is in `gravity.list`. 

Pulled up `https://www.amazon.com` and got the Connection Refused error, which is what Chrome should be showing, as we are not running an https server on the pihole.

/var/log/pihole.log shows:

     Dec 23 22:31:43 dnsmasq[24311]: query[A] www.amazon.com from 192.168.1.100
     Dec 23 22:31:43 dnsmasq[24311]: /etc/pihole/gravity.list www.amazon.com is 192.168.1.165

A `dig` for `www.amazon.com` also shows the IP of the PiHole.

It's what I kind of expected... However note that `amazon.com` and `www.amazon.com` are two different domains, and if you only have one of the variants in the blacklist.txt, you could still pull up the A records for the other variant. 

Lol, I knew eventually my B.S. in Network Engineering would come in handy, although it's been years...

**Comment by jacobsalmela** [comment]
Yeah, each subdomain would also need to be blocked.  I'm sure a lot of the larger sites have multiple domains and/or subdomains that redirect to the main site.  @greg5678 if you want to share the real domains, we might be able to figure it out for sure.

**Comment by jacobsalmela** [comment]
@greg5678 were you able to use the [DNSthingy Whitelist Assistant](http://pi-hole.net/faq/how-do-i-whitelist-or-blacklist-a-webiste-or-domain/) to find out what domains to block?

**Comment by greg5678** [comment]
The domains I want to block use ssl so it wouldn't work even if I blocked
the sub domains.

**Comment by dschaper** [comment]
I'm trying to work on the SSL aspect, would you be willing to help me out and give me one of the domains that you are trying to block? You can email them to me if you'd like, dschaper@ganymeade.com.

**Comment by greg5678** [comment]
Sure

**Comment by dschaper** [comment]
@greg5678 Thanks for the domains, I'll get to working on them. (I need to pick up a new Pi this afternoon, my testbed was re-purposed into a Minecraft server, I guess I'm the only one on the planet that doesn't get the whole Minecraft thing...)

**Comment by jacobsalmela** [comment]
This should be fixed by #180.
