### ISSUE TITLE
By default, all interfaces get selected if there is more than one

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#138]
<img width="393" alt="screen shot 2015-12-27 at 6 03 40 pm" src="https://cloud.githubusercontent.com/assets/3843505/12028323/41e26d0c-ad9b-11e5-9dee-4a0e9888ec4f.png">
It's kind of weird how I had to detect the interfaces for display in the dialog.  I loop through any available ones and then in the dialog I [set them all to on](https://github.com/jacobsalmela/pi-hole/blob/master/automated%20install/basic-install.sh#L80).  I did this so it wouldn't try to proceed without an interface selected.

Many users will probably never have an issue as it seems most just use a stock Pi with an Ethernet cable.  Even if there are multiple interfaces, you can just press Space to enable/disable each one, so it's not critical, but it would be nice to get it fixed.  I'm just not quite sure how to do this [inside the loop](https://github.com/jacobsalmela/pi-hole/blob/master/automated%20install/basic-install.sh#L78-L81).

**Comment by iblamefish** [comment]
What's the desired behaviour? Is it select exactly one or select at least one?

**Comment by jacobsalmela** [comment]
Probably just the first interface since it will probably be the primary one anyway.

**Comment by iblamefish** [comment]
Alrighty then. I'll see if I can get this done later today.

**Comment by iblamefish** [comment]
If you could test this on your device and let me know if there are any problems that would be great https://github.com/jacobsalmela/pi-hole/pull/146

**Comment by jacobsalmela** [comment]
Fixed by #146
