### ISSUE TITLE
Use whitelist.sh instead of built-in function

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#139]
The last update to `whitelist.sh` works really well.  I would like run this script within `gravity.sh` and eliminate the function.  They work essentially the same, but it will help simplify the main script and also reduce its complexity.

**Comment by Mcat12** [comment]
How easy would it be to add a blacklist script?

**Comment by jacobsalmela** [comment]
Easy enough.  You basically just need to append a domain to the list and then restart `dnsmasq`.

**Comment by Mcat12** [comment]
I have no real experience in bash. Would you be able to create a blacklist.sh?

**Comment by jacobsalmela** [comment]
Yes.  I have a lot of other things to do first.  Bug fixes take priority and I have a few long-term issues.  Feel free to make it into another issue so we can track it.

**Comment by jacobsalmela** [comment]
Fixed by #180
