### ISSUE TITLE
gravity_reload() kill -HUP errors if no dnsmasq process is running.

### ISSUE THREAD

**Issue by dschaper** [jacobsalmela/pi-hole#142]
kill -HUP errors out with `kill: invalid argument H` if dnsmasq is not running. Need to detect if `pidof dnsmasq` returns false then start dnsmasq instead of kill hup'ing it.

**Comment by jacobsalmela** [comment]
I noticed this, too.  I think it happened after #136

**Comment by dschaper** [comment]
I think that's where it changed, but it's probably a good idea to implement the scheme of HUP if we can, otherwise start dnsmasq. Doing it that way pretty much guarantees that dnsmasq is operational with the updated list after the function completes its run.

**Comment by iblamefish** [comment]
please ignore the first reference - the commit included code which it shouldn't have. I think that the second one does what you're after :)

**Comment by jacobsalmela** [comment]
I just merged it...it looked like the right one.

**Comment by iblamefish** [comment]
:+1: yep :)

**Comment by jacobsalmela** [comment]
But now the bane of my existence: [fixing conflicts](https://github.com/jacobsalmela/pi-hole/pull/144)--I don't know why but I just don't `git

**Comment by dschaper** [comment]
Lol, if two separate commits both edit the same line you'll get a merge conflict. Have to manually go in and tell `git` which version you want to keep. Most of it's done command-line style but there are a few conflict GUI's (I haven't used one yet, just nano to fix and commit)

**Comment by jacobsalmela** [comment]
This should be a simple one to figure it out on.  I have to learn at some point.  =)

**Comment by iblamefish** [comment]
I just tried the merge and the good news is that it's a conflict over nothing except whitespace in gravity.sh somewhere around lines 257-260 - so should be an easy one to get started with!

**Comment by iblamefish** [comment]
<img width="780" alt="screen shot 2016-01-02 at 00 35 41" src="https://cloud.githubusercontent.com/assets/74027/12072764/db113d1e-b0e8-11e5-9df4-26ebbebe9456.png">

**Comment by jacobsalmela** [comment]
Haha.  Well, I did _something_ and it worked.  I'm not sure why that stuff is so confusing for me.  lol

**Comment by iblamefish** [comment]
Things always are until they aren't any more :)

**Comment by dschaper** [comment]
Sign up for the Lynda.com 10 day free trial and take the Git Essential Training course. It's a really good course and it covers git and github, really clears up things. Helped me a bunch.

**Comment by jacobsalmela** [comment]
I'll `git` on that.  I have used Lynda.com before--didn't know there was a git course.

**Comment by dschaper** [comment]
Nice... I've got a full sub from a previous employer, if you need the exercise files, let me know, I don't remember if the exercise files are available to trial members or not?

**Comment by dschaper** [comment]
@iblamefish How did you get that drop shadow on your screenie?

**Comment by iblamefish** [comment]
@dschaper `cmd` + `shift` + `4` then press `space` and you can select an application window to take a screenshot of. The drop shadow is an added bonus that comes with it.
