### ISSUE TITLE
stty: standard input: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#145]
The automated installer gives some errors while trying to determine the screen size to set the appropriate rows and columns.  It doesn't seem to affect anything, but it would be nice to not have the errors displayed.

```
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
```

**Comment by meliton** [comment]
I use `tput` to get the lines and columns on the Pi without throwing those errors
`rows=$(tput lines)`
`columns=$(tput cols)`

`# Divide by two so the dialogs take up half of the screen`
`r=$(( rows / 2 ))`
`c=$(( columns / 2 ))`
`}`

**Comment by jacobsalmela** [comment]
It's so elegant!  Thanks.  I'll add it in.

**Comment by bolausson** [comment]
There seems to be a similar "bug":

When I run "pihole -up >> /dev/null" via cron, I get the following output in the cron log: 
`stty: standard input: Inappropriate ioctl for device`

This is caused by the below line in "/etc/.pihole/automated install/basic-install.sh"
`screen_size=$(stty size || printf '%d %d' 24 80)`

It can easily be silenced by converting it to the following:
```--- basic-install.sh	2019-07-24 14:19:45.630409793 +0200
+++ basic-install_fixed.sh	2019-07-24 14:19:37.510436898 +0200
@@ -85,7 +85,11 @@ fi
 
 
 # Find the rows and columns will default to 80x24 if it can not be detected
-screen_size=$(stty size || printf '%d %d' 24 80)
+if [ -t 0 ] ; then
+  screen_size=$(stty size)
+else
+  screen_size="24 80"
+fi
 # Set rows variable to contain first number
 printf -v rows '%d' "${screen_size%% *}"
 # Set columns variable to contain second number```

Cheers,
Bjoern

**Comment by dschaper** [comment]
Thanks bolausson! Do you want to open a PR for that change for us?

**Comment by pokono** [comment]
+1 
Is driving me nuts with cron errors emails!!

**Comment by bolausson** [comment]
> Thanks bolausson! Do you want to open a PR for that change for us?

Done! --> Check if tty exist before we get screen size #2859 

Cheers,
Bjoern
