### ISSUE TITLE
Installer script is served via HTTP

### ISSUE THREAD

**Issue by Terr** [jacobsalmela/pi-hole#150]
The instructions for the automated install call for a curl-pipe-into-bash of an installer script. While this practice is common nowadays despite the possible security risks, in this case I think there are two additional risks:

1. ```curl``` is called with the ```-L``` parameter because ```install.pi-hole.net``` responds with a 301 redirect. Should the server ever be compromised, the user could become redirected to a malicious script because curl will just follow without questions asked.

2. The URL is not served via HTTPS. This allows, how unlikely it may be, for requests being intercepted and a different redirect or script to be injected.

The second point is probably the easiest to mitigate and probably for free thanks to Let's Encrypt. 

The first point is more difficult: even if you would host the installation script directly on the server, it getting compromised would mean that someone can modify the script.

Maybe it's just better to put the full GitHub URL (```https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/automated%20install/basic-install.sh```) in the installation instructions. It might be lengthy, but people probably copy/paste anyway. And it would solve the HTTP issue.

**Comment by jacobsalmela** [comment]
I agree completely with everything you brought up.  I *was* previously directing users to `curl` the install script right from Github.  But I wanted an install/uninstall command that was easy to remember (mostly just for myself when I test the install after making changes).  

Homebrew uses a similar method of installation, which is where I got the idea from.  There is inherent risk in blindly `curl`ing and executing a script without knowing what it is in the first place.  I'm not trying to justify anything--just giving some background.  

HTTPS shouldn't be too much of an issue.  I planned on putting the donation money towards a certificate, but I'll have to check out Let's Encrypt.  Thanks for that resource.

**Comment by dalanmiller** [comment]
+1 for Let's Encrypt, very easy to setup.

**Comment by jacobsalmela** [comment]
I couldn't use Let's Encrypt, but the site is now available via https.
