### ISSUE TITLE
File missing, or crontab schedule not needed anymore ?

### ISSUE THREAD

**Issue by fmjensen** [jacobsalmela/pi-hole#151]
/usr/local/bin/dailyLog.sh is configured to execute every day, but the script does not exist as far as i can figure out. !?

**Comment by jacobsalmela** [comment]
[Not yet](http://pi-hole.net/donate/), it doesn't.  It's part of an upcoming project I have for long term stats.  There's nothing there yet, but it's going to be in [this branch](https://github.com/jacobsalmela/pi-hole/tree/enhanced-stats).

**Comment by fmjensen** [comment]
Okay, i will remove it from the crontab then :-)
