### ISSUE TITLE
Web interface showing incorrect stats

### ISSUE THREAD

**Issue by jaytay79** [jacobsalmela/pi-hole#158]
My admin console shows 371 "ads blocked today" and 21,288 "DNS queries today" but if I run chronometer.sh I get:

Queries:       7210 / 3018
Pi-holed:      95  (.920%)

I would guess that the web figures are showing an "all-time" count and not the "today" that the text is actually saying.....

Hmm, since I raised this issue the stats have reset to a daily figure so the issue instead appears to be that the stat refresh is happening at the "wrong" time of day

**Comment by jacobsalmela** [comment]
I have the log set to flush just before midnight [at 11:58](https://github.com/jacobsalmela/pi-hole/blob/master/advanced/pihole.cron#L26) (unless of course I don't know how to write cron files, which is entirely possible).

**Comment by dschaper** [comment]
Question about that, are we targeting a systemD environment or SysV? (This would be good for a systemD timer unit instead of dealing with crons.) Basically, is Raspbian Jessie the only platform, or is there a need/want for more distributions/platforms?

**Comment by jacobsalmela** [comment]
I think I'd like to keep it exclusive to Raspbian unless the project takes off and I can make a career out of it.  The community has already taken to porting it to other platforms and doing all sorts of stuff with it (as I have been adding to the README page).  I think a narrower scope is better for me to not get overwhelmed and ultimately make the commits less stable.  

I have also always been a fan of things that are the same across platforms.  You can pretty much always find `cron`, `grep`, and others.

**Comment by dschaper** [comment]
All good points. The only thing about the systemD aspect is being able to use the timers instead of cron, but cron still works from all of my tests. Keep it simple and stable, and then branch out once it's pretty rock solid? I can understand that approach.

**Comment by jaytay79** [comment]
This line?

58 11   * * *   root    /usr/local/bin/piholeLogFlush.sh

You need 23 instead of 11 as at the moment it's running at 11:58am :)
