### ISSUE TITLE
Botched install, then reinstalled, Web UI is broken.

### ISSUE THREAD

**Issue by dalanmiller** [jacobsalmela/pi-hole#159]
Currently pihole is working in blocking ads, but nothing is showing up for the Web UI. I've confirmed `lighttpd` is running. Is there anything else I should check?

**Comment by alpha1125** [comment]
I seemed to have the same issue yesterday, but a reboot of the rpi, it started to work.  probably nginx/http server was not (re)started.

**Comment by jacobsalmela** [comment]
I was going to point you to [this FAQ](http://pi-hole.net/faq/why-does-the-web-dashboard-show-zero-for-queries-and-ads-blocked/) but since your ads are getting blocked, it makes me think it is just something weird or a failing SD card.  Please let me know if it is working or not after a restart.

**Comment by dalanmiller** [comment]
I'll restart it when I get home and report back :+1:

**Comment by MonkeyBiz** [comment]
I have the same issue
1.) New image flash (Raspbian Jessie, November 2015)
2.) sudo su
3.) apt-get update and upgrade
4.) Run the curl install script
5.) Reboot

Advertisements appear to be blocking correctly, dnsmasq and lighttpd services are running, but the pihole.log is always blank. Even after doing a chmod 777 on the log and reboot it never updates the pihole.log.

**Comment by dschaper** [comment]
Is the log blank if you try an install without the `sudo su` step? I'll try an install with that step and see if I get the same thing...

**Comment by dschaper** [comment]
Okay, I did your install exactly in the order that you described and I have the following permissions:

```
root@raspberrypi:/var/log/lighttpd# ls -lac /var/log/pihole.log
-rw-r--r-- 1 dnsmasq root 566 Jan 12 19:49 /var/log/pihole.log
```

I do have the typical startup logging showing via `tail /var/log/pihole.log`. 

Are you `curl`ing the latest version of the script when you install? There have been some changes to the `sudo` process...

**Comment by dschaper** [comment]
What does your output of the following command look like?

```
pi@raspberrypi:~ $ cat /etc/dnsmasq.conf |grep pihole
addn-hosts=/etc/pihole/gravity.list
log-facility=/var/log/pihole.log
```

**Comment by MonkeyBiz** [comment]
My command history for the Jessie November Install
sudo su
apt-get update
apt-get upgrade
curl -L install.pi-hole.net | bash
reboot

**Comment by MonkeyBiz** [comment]
I think I solved the issue.

1.) Uninstalled using "curl -L install.pi-hole.net | bash"

2.) by default Raspbian Jessie limits the disk space, so I used raspi-config to open up all available space (8 gigs)

3.) Installed using 
sudo su
curl -L install.pi-hole.net | bash
reboot

Stats appear to be updating correctly now. The full Jessie image must take up too much space for the default settings.

**Comment by dschaper** [comment]
Ah, yeah, I didn't notice that you didn't run `raspi-config` and resize the root partition. That will cause issues, the new Jessie needs all the space available. 

@jacobsalmela Do you think we should add a function to check for available disk space? Or just update the install instructions to include resize root?

**Comment by jacobsalmela** [comment]
I have thought about that a few times on and off.  The `raspi-config` process is open source, so we could modify [these lines](https://github.com/asb/raspi-config/blob/master/raspi-config#L36-L116) to suit our needs.  It needs a reboot, however. 

Lately, I have been testing using the minimal Jessie image and I never have to expand the FS.  Even on the regular version I haven't had to do that.  Either way, I think it's a good enhancement.  Since this issue doesn't have to do with the Pi-hole itself, I will close this and create a new issue for checking available disk space.
