### ISSUE TITLE
Ads appear and disappear

### ISSUE THREAD

**Issue by braddo99** [jacobsalmela/pi-hole#16]
First, terrific utility and a nice way to use an extra RPi I had around.

I have the system up and running and it works pretty well. But everyonce in a while I'll open a page and the ads are all there, quite shocking to see when it happens after the relative bliss of clear pages.

However, usually if I refresh the page, they will disappear. Then if I refresh many times, they'll sometimes reappear and disappear again.

I'm sure something is choking the RPi somewhere and causing the secondary DNS to be used, but I'm not sure how to troubleshoot this.

**Comment by jacobsalmela** [comment]
What site did you notice this on?

I wonder if the site somehow rotates the domains it pull ads from and those domains are not on the list.  

I suppose the first step to troubleshoot would be to see if I can replicate the issue.  Did you use the one-command install or did you set it up from scratch?

**Comment by braddo99** [comment]
Actually it's your blog site :-)

http://jacobsalmela.com/raspberry-pi-block-ads-adtrap/

For install I used the one liner but then went back and did the advanced chron'd list. The ads are simple banners coming from www.googleadservices.com - it's in the list and, as I said, sometimes the ads show and other times they are filtered. I can look at the tail of the log and see the ads as they are queried and forwarded to google. The only thing I know doesn't follow your guides is that the Raspi was originally based on OctoPi, a 3d printer OS build with a web viewer and some camera stuff on it. I did uninstall those but didn't start from a fresh raspbian. I could try that but it is working, just not consistently, would love to know if there's something to check before blasting the whole pi again.

**Comment by braddo99** [comment]
I actually think the secondary DNS was causing this issue, once turned off the behavior seems very consistent. Another contributor to my suspicions was behavior while watching my phone (which is the primary beneficiary of this!) It seems the phone would sometimes drift out of wifi connectivity and start using the cell network, which would immediately put ads back in.

**Comment by jacobsalmela** [comment]
That would make sense since the celluar network wouldn't block the ads.  It may be possible to point your phone to your own DNS server.  The AdTrap does it somehow, which I would love for the Pi-hole to do so you can reduce your data usage.

Thanks for the update!

**Comment by braddo99** [comment]
Well the phone typically grabs known wifi as soon as it can and for that I've already set the dns using a static/reserved IP on my network. Can't even believe how much smoother browsing on the phone is. I expect it to be even better on the iPad since that's sluggish regardless.
