### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by Kajpio** [jacobsalmela/pi-hole#160]
Hi guys,
Just love this idea. But I have a question, can i got this server on a wireless, because each time I choose wlan0 it's saying that I've chosen eth0. So it's a bug ? 
Thank you

**Comment by dschaper** [comment]
Where are you seeing it display that you've chosen eth0? It should just list your IP addresses, not the actual interfaces. Can you screenshot what you are seeing?

**Comment by dschaper** [comment]
Okay, I think I know what you mean. I set up a Pi2 with a USB-Ethernet adapter and a UBS Wifi adapter so I have 3 choices at the whiptail prompt. However, if I chose an interface other than `eth0` the IP address pulled is still the address from `eth0` since PiHole is set to get the IP address of the interface that has WAN access. 

So, should we need to allow the user to override and chose the IP address of the interface even if it has no WAN access?

**Comment by Kajpio** [comment]
Yes almost that!
It's when I run the instalation script, It's asking for which interface he
need to setup on, even if I choose wlan0, he choose for me eth0. And both
are available. I have a WAN connection in both.
Thanks!

**Comment by dschaper** [comment]
Okay, I see it. I removed the cable from `eth0` and hooked up `eth1` and the script grabs the first available WAN accessible address and uses that. So we do need to allow users to override the automatic detection and select their own. There is the step that allows the user to enter a specific IP address, but it would be nice to pull the IP of the interface chosen for ease of use.

**Comment by dschaper** [comment]
And @Kajpio, if you need a workaround, run the script and when you get to the `Static IP Address` page that asks `Do you want to use your current network settings`, you can say `No` and you'll have the option to manually input the correct IP address... Thanks for the report!

**Comment by jacobsalmela** [comment]
So would it be [these lines](https://github.com/jacobsalmela/pi-hole/blob/master/automated%20install/basic-install.sh#L32-L33) we would have to reassess?

**Comment by dschaper** [comment]
I'm not sure. Those lines work for most installs, as most are going to only have one route to the outside world. It's just in the rare cases that there is a multi-homed Pi with more than one route to the Internet. 

Maybe we should pull that code into a function itself that sets the `$IPv4dev` as it does now and takes an argument that is the interface selected. If the user selects a different interface we then set `$IPv4dev` to the selected interface and then pull the IPv4 address.

**Comment by jacobsalmela** [comment]
That could work.  

So many bugs popped up!  Bummer, now I can't work on the [fun stuff](https://github.com/jacobsalmela/AdminLTE/pull/9) until these are done.

**Comment by dschaper** [comment]
Okay, I've got part of a working solution for this, wasn't too bad but I'm having a bit of trouble getting the gateway. @Kajpio can you post the output of your `route` command? I can get the `ip` of the interface once its selected, and that cleans up the code a little bit, but I don't have a good test scenario for a Pi with more than one route to the WAN. (I may be able to rig up something with my cellular phone, and I'll try that later...)

**Comment by dschaper** [comment]
Looking over things again, @jacobsalmela do we really need the gateway? I think all that's needed is the IP address, the gateway and routing information isn't needed, or am I missing something?

**Comment by jacobsalmela** [comment]
Probably not.  However, while unlikely for most home users, they may set a different gateway, so that variable would be needed when setting it statically.   Probably 99% of the people will just leave their default gateway as-is.

**Comment by dschaper** [comment]
Heh, so we have 1% that need the gateway, and 1% that have multi-homed... I'm kind of inclined to leave things as they are and let the user update the IP's via the existing capabilities. Otherwise we're going to start chasing corner cases. @Kajpio did the workaround of entering your IP directly help you out?

**Comment by Kajpio** [comment]
Guys !
I think that I didn't express myself clearly, it's when it's ask to choose an interface
![screenshot from 2016-01-13 19 20 30](https://cloud.githubusercontent.com/assets/13314529/12303480/deeee2d8-ba2a-11e5-95e9-80a3e05116cb.png)


Even if I click on wlan0 it's select eth0 (see second screen)
![screenshot from 2016-01-13 19 21 13](https://cloud.githubusercontent.com/assets/13314529/12303481/def2725e-ba2a-11e5-9a2d-e2f973a3e9c8.png)

So I wanted to ask if it's a bug or I have no choice ? :)

**Comment by Kajpio** [comment]
That's my only problem but if discovered a new bug, I'm happy too :p

**Comment by dschaper** [comment]
I'm inclined to say it's a bug, I think I know where in the code it is... Thanks for the report!

**Comment by Kajpio** [comment]
Ah if you could tell me which line I need to edit that would be awesome ! :+1: 
You welcome

**Comment by dschaper** [comment]
Take a look at the lines that are changed in the PR I just submitted.

**Comment by Kajpio** [comment]
Just a question (I'm newbie), but when i lauch it whith the scipt changed it saying that is still using eth0 :/. So do i need to change a variable to wlan0 or ...?
Thank's for your help

**Comment by dschaper** [comment]
It's purely a cosmetic change. The Pi-hole actually functions via the IP addresses so that's the key piece of information. Can you test the pi-hole installation? (We use osxdaily.com as the test site, they have quite a few ads and it's easy to tell if the pi-hole is working or not by visiting that site.)

**Comment by Kajpio** [comment]
Not working... I need to put in pi.ip.l.an/24 or pi.ip.l.an ? :/

**Comment by dschaper** [comment]
When you set up via `basic-install.sh` and you get the screen that asks if the IP is correct, select `no` and enter the IP address that you'd like to use. Just use the IP in `1.2.3.4` form, you don't need to add the network mask (the /24). Are you using an IP in the `192.168.0.0` range?

**Comment by Kajpio** [comment]
Yes I do you think that there's  conflict ? :/

**Comment by dschaper** [comment]
There shouldn't be, as long as you are pointing the clients to use the Pi-Hole as their DNS server. You can `tail -f /var/log/pihole.log` to see if the clients are requesting DNS information from the Pi-Hole. 

You also may have some of the advertising domains DNS addresses cached. What OS are the client computers?

**Comment by Kajpio** [comment]
No I think that's the problem of my pi-hole, because if I change the DNS in my Iphone it cannot reach sites. I cannot ping it too. I've setup it to be on 192.168.1.40 not 192.168.0.40
My ads are not cached for sure.
Thank's for your patience.

**Comment by Kajpio** [comment]
I have a OpenVPN server running on my raspberry pi, do you think that's matter ?

**Comment by dschaper** [comment]
Since you are using private IP addresses, can you give us the IP's for the interfaces on the Pi? I'm trying to set up a similar Pi but I'm not exactly sure how your Pi and network is configured. It's not a typical Pi-Hole configuration, but I'm sure we can find a way to support your network. Is it just the one iPhone that is using the Pi-Hole or are there other machines?

**Comment by dschaper** [comment]
OpenVPN could complicate things, since I believe it assigns a DNS server address when it sets up the tunnel.

**Comment by jacobsalmela** [comment]
So @Kajpio, your Pi has the regular Ethernet port (`eth0`), a wireless dongle maybe? (`wlan0`), and a tunnel of some sort (`tun0`)?

@dschaper, that PR looks good.  I'll test is as usual before merging.  It works for you though?

**Comment by dschaper** [comment]
Yeah, works okay on my tests. It really is just a cosmetic fix, there's not much changed substantially. Although it does bring things in line so that were using fewer variables and re-using the proper variable.

**Comment by Kajpio** [comment]
@dschaper it assign a DNS but I was thinking to assign my own VPN. What information do you need ?
@jacobsalmela My raspberry has eth0 but it's not connected, yeah wireless dongle, yeah tun0 is for my OpenVPN server.

**Comment by Kajpio** [comment]
And guys, my eth0 is not connected that maybe is the problem, what do you think about ?

**Comment by dschaper** [comment]
The Pi-Hole is IP based, not interface based, so as long as the clients are getting the correct IP address for the DNS server then the Pi-Hole should work. Can you post what your setup is? (Intefaces and IP addresses for the Pi and what kind of clients you have and how they connect.) I don't quite understand your setup, and it's a bit more complex than the typical Pi-Hole installation.

**Comment by jacobsalmela** [comment]
So the `dnsmasq.conf` file sets `interface=`, which would limit it to listening only on the specified interface.  But if it was the correct one, it should still work.

@Kajpio, more information on your setup would help.

**Comment by Kajpio** [comment]
Yeah so, I have a raspberry pi 2 model B, on this raspberry pi a OpenVPN is running on it (I can connect on the OpenVPN with all my devices : PC, iphone, android...) and so my raspberry is connected throw a wifi dongle (wlan0). The IP of the PI-hole is 192.168.1.1 I was trying to run Pi-hole and after in my server conf of my vpn choose the 192.168.1.1 DNS. It didn't work. I tried just changing my DNS in my computer and my IOS devices it still doesn't working...
Please be free to ask more specific things.
And I thank you for this support !

**Comment by jacobsalmela** [comment]
What is the IP of your router/gateway?

**Comment by Kajpio** [comment]
192.168.0.1

**Comment by Kajpio** [comment]
So I just connected it in eth0, on my Iphone it doesn't seems to work it does not load sites...

**Comment by dschaper** [comment]
I don't have any iDevices, so forgive me if I'm asking an odd question. Can you see what the IP configuration is with the iPhone? See what IP address it has and what IP address it's using for DNS?

**Comment by Kajpio** [comment]
Yes you can like on android, I've tested with my computer and it doen't seems to load site ...

**Comment by dschaper** [comment]
From your computer try `ping 8.8.8.8` and then if that works, try `ping www.yahoo.com`. This will tell us if you have internet connectivity, and if you do the second ping will tell us if you have DNS resolution capability. You have quite the complex setup and we need to start from the bottom and not change a bunch of variables at the same time. Let's find out what we have, what we need and were we need to go.

**Comment by Kajpio** [comment]
I reinstalled id, now I can ping 8.8.8.8 (google's server) and I have DNS resolution capabilty. But
when I load osx.daily.com the ads are still there.
I have cleared the cache.
Thanks for your patience

**Comment by dschaper** [comment]
What IP address is set for your computer, and what IP address is set for the DNS server on that computer? (Is is a Windows or a Macintosh?)

**Comment by Kajpio** [comment]
192.168.0.x I don't remember but that doesn't really matter, does it ? 
192.160.0.40, I' using Linux..

**Comment by dschaper** [comment]
And lastly, what IP is the Pi-Hole listening on?

**Comment by Kajpio** [comment]
It should listen on 192.168.0.40, Can I check it somehow ?

**Comment by dschaper** [comment]
Can you do a `cat /etc/dnsmasq.conf` for me?

**Comment by Kajpio** [comment]
I haven't got this file, for it's a directory and in this directory there's a README file...

**Comment by dschaper** [comment]
What does `ls -lac /etc/ |grep dnsmasq` look like on the Pi?

**Comment by Kajpio** [comment]
http://puu.sh/mDSC7/36fbd982ca.png

**Comment by Kajpio** [comment]
Yeah so I need to go root to see it ?

**Comment by Kajpio** [comment]
So the cat /etc/dnsmasq.conf is : http://puu.sh/mDSH8/165e4a8fb1.png

**Comment by jacobsalmela** [comment]
After you run the installation choosing `wlan0` as your interface, can you run 
`cat /tmp/piholeINT`
`cat /etc/dnsmasq.conf | grep interface`

**Comment by Kajpio** [comment]
for the first it says wlan0
and second it's says interface=wlan0

**Comment by dschaper** [comment]
Your screenshot shows `interface=eth0`, did you re-run `basic-install.sh` since the screenshot was taken?

**Comment by extremeshok** [comment]
If i have time later, busy extended pi-hole to add real time dns record 
rewriting.

  ie. if you want to change a specific cname or ip for all dns records 
to a different value.

eg A record 88.77.66.55 could become CNAME www.someplace



__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by Kajpio** [comment]
Yep sorry, so now I've managed to connect it with an eth0 cable, and I am reinstalling it i think that's was a problem with OPenVPN and pi-hole sorry !

**Comment by dschaper** [comment]
Let us know if you get things working, or if you still have issues. Thanks!

**Comment by Kajpio** [comment]
There's no more ads on osxdaily. I will figured it out how to make it work with OpenVPN

**Comment by dschaper** [comment]
If there's no more ads on osxdaily, then you have the Pi-Hole configured and working properly.

**Comment by dschaper** [comment]
I'll go ahead and close out this issue then, if you run into any more problems just post again. Thank you for using the Pi-Hole.
