### ISSUE TITLE
Blocking to much

### ISSUE THREAD

**Issue by mattmill98** [jacobsalmela/pi-hole#165]
I setup pi-hole on my network and change my router setting to use it as a dns server. However it is blocking to much, its blocking things like thumbnails on facebook. But some ad's manage to get through such as ads on facebook and youtube. I installed it initially and selected ipv4 and 6 and it was over blocking so i reinstalled and just selected ipv4. Any ideas why its doing this?

**Comment by dschaper** [comment]
There are a lot of ads that come through via IPv6, so if your network is set up to use IPv6 you will notice a lot of ads getting through with IPv6 disabled on the pi-hole blocker. 

As for overblocking, you can whitelist domains that you would like to bypass the blocker, but I'm not sure why facebook would be blocked unless it is on one of the domain lists. Do you have mahalaka enabled? That blocker tends to be a bit overzealous and blocks a number of legitimate domains.

**Comment by mattmill98** [comment]
I reinstall it tomorow using both ipv4 and 6, how do i comment out mahalaka? Is that in gravity.sh? if so wheres that located (what command do i run) as im running jessie lite

**Comment by dschaper** [comment]
Mahalaka is commented out by default. It's in `gravity.sh`. Jessie lite has the nano editor, so you could run `nano /usr/local/bin/gravity.sh` to see. There is a stanza of lists that are pulled in to bake the blocklist, but I think you'll find that one list already pounded out. 

Let us know if you have blocking issues or strange results so we can help troubleshoot them and get the blocking correct. 

Thanks!

**Comment by mattmill98** [comment]
I'll give that a try! Also does pi-hole use google dns? if so is there any way i can change this to opendns as thats slightly quicker for me.

**Comment by dschaper** [comment]
Yes, Pi-Hole uses Google's DNS servers. You can change that in `/etc/dnsmasq.conf`. The section you need to change is `server=8.8.8.8` to `server=` and then the IP's for OpenDNS. You may need to `sudo nano /etc/dnsmasq.conf` to edit the file, and then `sudo systemctl restart dnsmasq` to reload the configuration after you do the updates.

**Comment by meliton** [comment]
I wonder if adding an option to select the DNS server during the installation would be something handy. That way, end users wouldn't need to mess with configuration files.

**Comment by dschaper** [comment]
I was thinking about DNSCrypt in the future too, so ISP's couldn't intercept the forwarders lookups and send altered responses. If @jacobsalmela wants, we could open a new issues in regards to DNS forwarder customization. Besides Google and OpenDNS, are there any major players? (I run my own Unbound/NSD Authoritative server stack on a VPS so I don't use intermediaries.)

**Comment by jacobsalmela** [comment]
Yeah, I'm open to that.  I know some people don't like the public Google servers.  I just put them in there because I knew them via memory and they are always up.

**Comment by jacobsalmela** [comment]
Also, as @dschaper mentioned, more and more ads have been coming over IPv6, so it's probably best to use both protocols.  But depending on your browsing habits, you might have to fine-tune a good whitelist.

**Comment by jacobsalmela** [comment]
Let us know if you were able to change the DNS servers and how it works and I will close the issue.

**Comment by mattmill98** [comment]
Im going to reinstall either later today or tomorow, i have a busy schedule at the moment, but i'll let you know what happens as soon as i reinstall

**Comment by ajp2k13** [comment]
I would love to see DNSCrypt or maybe DNSSec. On my router (AC68U with Merlin FW) I use DNSSec with dns.watch.
https://duckduckgo.com/?q=public+dns+servers&t=ffab&ia=answer

**Comment by mattmill98** [comment]
Just reinstalled it all, changed to open dns no problem. But its still blocking things it shouldn't and letting things through it should block. This is what my gravity.sh looks like, shouldnt mahalaka be blue if commented out?
<img width="1280" alt="screen shot 2016-01-14 at 15 13 21" src="https://cloud.githubusercontent.com/assets/10357263/12328048/8de31a56-bad1-11e5-85a4-00e6216e1e5f.png">

**Comment by dschaper** [comment]
It looks like the quoting coloring is taking precedence over the commenting coloring. Mahakala does look like it's commented out, the pound sign is in the right place. Do you have a site that is not behaving as it should that we could use to test out?

**Comment by mattmill98** [comment]
This is a screenshot of my facebook, this is one of the sites it acts weird on 
<img width="1280" alt="screen shot 2016-01-14 at 15 09 51" src="https://cloud.githubusercontent.com/assets/10357263/12331062/dc9dfb44-badf-11e5-94d8-d6ba22d5eede.png">

**Comment by dschaper** [comment]
Thanks, I'll take a look. Is it only the sponsored articles that are being blocked?

**Comment by mattmill98** [comment]
No things like this are blocked to
<img width="496" alt="screen shot 2016-01-14 at 17 18 22" src="https://cloud.githubusercontent.com/assets/10357263/12331741/dfd762ac-bae2-11e5-985e-1afc6282b031.png">

**Comment by dschaper** [comment]
@ajp2k13 Could you open a new issue for DNSCrypt? I don't want it to get lost in this issue thread.

**Comment by dschaper** [comment]
@mattmill98 I can't seem to replicate the issue. Can you tail `/var/log/pihole.log` and see if the are hits when you browse Facebook. I get the full image when I browse, but I'm in the United States. 
![capture](https://cloud.githubusercontent.com/assets/2782850/12334076/dd0dff12-baac-11e5-9569-301610359f0a.PNG)

**Comment by mattmill98** [comment]
Yes they do and ive looked in the pihole.log and i cant see anything untoward. Can i copy from nano editor attatch the log here?

**Comment by dschaper** [comment]
If you want, you can zip up the log and attach it to an email. My address is dschaper@ganymeade.com

**Comment by mattmill98** [comment]
I only have jessie lite so it doesnt have a file browser. Can i copy from the nano editor?

**Comment by dschaper** [comment]
That will work also.

**Comment by mattmill98** [comment]
This maybe a dumb question but how do i copy out of nano to my clipboard?

**Comment by dschaper** [comment]
Not a dumb question, but one I don't know the answer to. You're on a Mac, so @jacobsalmela may be able to give you some tips. (I'm in PC/Linux world and don't have access to a Mac yet...)

**Comment by mattmill98** [comment]
I have a windows PC which im on now haha

**Comment by dschaper** [comment]
You could FileZilla into the Pi and download `/var/log/pihole.log' and email that.

**Comment by mattmill98** [comment]
Why didn't i think of that, emailed you the log

**Comment by dschaper** [comment]
Okay, it looks like hosts-file.net is blacklisting the following domains that are Facebook Content Delivery Network nodes:
```
127.0.0.1       creative.ak.fbcdn.net
127.0.0.1       external-lhr0-1.xx.fbcdn.net
127.0.0.1       external-lhr1-1.xx.fbcdn.net
127.0.0.1       external-lhr10-1.xx.fbcdn.net
127.0.0.1       external-lhr2-1.xx.fbcdn.net
127.0.0.1       external-lhr3-1.xx.fbcdn.net
127.0.0.1       external-lhr4-1.xx.fbcdn.net
127.0.0.1       external-lhr5-1.xx.fbcdn.net
127.0.0.1       external-lhr6-1.xx.fbcdn.net
127.0.0.1       external-lhr7-1.xx.fbcdn.net
127.0.0.1       external-lhr8-1.xx.fbcdn.net
127.0.0.1       external-lhr9-1.xx.fbcdn.net
127.0.0.1       fbcdn-creative-a.akamaihd.net
```
Try commenting out that list in `gravity.sh` and see if that fixes the problem. Remember to re-run `gravity.sh` and restart `dnsmasq` after that so the domains are picked up correctly.

If you `cat /var/log/pihole.log | grep gravity.list` you'll see which domains are being served by the Pi-Hole...

**Comment by mattmill98** [comment]
This doesnt work either :/ i give up now, well i'll have a play around, shall i close this issue now?

**Comment by dschaper** [comment]
You might have the Pi-hole address cached for those domains. Try `ipconfig /flushdns` at a Windows command prompt to flush out the Pi-Hole address and reboot the Pi.

**Comment by jacobsalmela** [comment]
Flushing the DNS cache is an important step.  I think you should also try using the [DNSthingy Whitelist Assistant to discover what domains to whitelist](http://pi-hole.net/faq/how-do-i-whitelist-or-blacklist-a-webiste-or-domain/).  It's usually a little easier than parsing the log.

@dschaper, I wonder if it also may have something to do with the [`url.rewrite` issue](https://github.com/jacobsalmela/pi-hole/issues/161#issuecomment-171177122) we were working on the other day, as it looks similar with the little placeholder icon.

**Comment by dschaper** [comment]
@jacobsalmela It's `http://hosts-file.net/`. They added FBCDN addresses to their list (it's on the homepage). Once that is removed/whitelisted and the cache flushed then everything should be good. I don't know how to contact hosts-file to let them know of the breakage.

**Comment by jacobsalmela** [comment]
They used to have a form, but it looks like any modification requests should be [sent via email](http://hosts-file.net/?s=Help#submission).

**Comment by mattmill98** [comment]
I've flushed through the dns but it still has the same problem, heres what dns thingy says when i refresh facebook.
![capture](https://cloud.githubusercontent.com/assets/10357263/12346976/0cfbc5c0-bb51-11e5-821f-01fe1a81a928.PNG)

**Comment by dschaper** [comment]
What does `cat /etc/gravity.list | grep fbcdn` show?

**Comment by mattmill98** [comment]
No such file or directory?
![capture](https://cloud.githubusercontent.com/assets/10357263/12347012/742fc9e4-bb51-11e5-9d70-98c127766c69.PNG)

**Comment by dschaper** [comment]
Sorry, `/etc/pihole/gravity.list`, and while you're at it `cat /var/log/pihole.log | grep gravity.list`

**Comment by mattmill98** [comment]
/etc/pihole/gravity.list:
![capture](https://cloud.githubusercontent.com/assets/10357263/12347059/f2ad37e8-bb51-11e5-8a9c-91a46a537e3e.PNG)

cat /var/log/pihole.log | grep gravity.list:
![capture](https://cloud.githubusercontent.com/assets/10357263/12347070/11a39868-bb52-11e5-8ffb-84d6aba31c50.PNG)

**Comment by dschaper** [comment]
You are still blocking the domains from `hosts-file.net` it looks like. 

What does your `/usr/local/bin/gravity.sh` sources look like?

Should be:

```
sources=('https://adaway.org/hosts.txt'
'http://adblock.gjtech.net/?format=unix-hosts'
#'http://adblock.mahakala.is/'
#'http://hosts-file.net/ad_servers.txt'
'http://www.malwaredomainlist.com/hostslist/hosts.txt'
'http://pgl.yoyo.org/adservers/serverlist.php?'
'http://someonewhocares.org/hosts/hosts'
'http://winhelp2002.mvps.org/hosts.txt')
```

**Comment by mattmill98** [comment]
It may of helped if i had relaoded gravity.sh oops, but yeah it works now! :) Unfortuantley
![capture](https://cloud.githubusercontent.com/assets/10357263/12347140/f7c1d792-bb52-11e5-9fcc-11d4e640a730.PNG)
 there are still ads getting through

**Comment by dschaper** [comment]
Well, we know that `xx.fbcdn.net` are the content servers that you do want to get through, so you could uncomment the `host` list again and `whitelist.sh` the `xx.fbcdn.net` address and see if that strikes a balance of blocking bad and letting in good? Just depends on how much you want to play with it to get it right for your situation. But we know where the problem is, and the ways to work around the problem...

**Comment by mattmill98** [comment]
Okay thank you for all your help, ads on other sites are blocked so it is just facebook that has the problem, i'll close this issue now:)

**Comment by dschaper** [comment]
Not a problem, glad we were able to come up with a solution to the issue. If you'd like, you can send a small donation to @jacobsalmela since he develops this software... Thanks!

**Comment by mattmill98** [comment]
I'll probably do that when i get paid as the support from you both has been brillaint

**Comment by dschaper** [comment]
It's greatly appreciated!

**Comment by ajp2k13** [comment]
@dschaper I'll create a new issue for DSNCrypt later, thanks!

**Comment by mattmill98** [comment]
I still cant get this to work for me :( Some ad's are blocked fine, some are blocked but then chrome says 'server refused connection and some aren't blocked at all. I have changed the webpage to a 1x1 gif and the ad space is still visable, do you think this is now a network config issue? or has this happened before? sorry to reopen it but i dont know what else to try

**Comment by jacobsalmela** [comment]
So it's just Facebook that is giving you issues?
@mattmill98 

I think we just need to isolate what domains are being queried while on Facebook.  We know a bunch alerady, but maybe you have only Facebook open (turn off other things like Dropbox, or anything else that might go out the the Internet automatically).  Then flush your log:

```
sudo truncate -s 0 /var/log/pihole.log
```

Then browse Facebook for a few minutes and see what domains are queried.  Then we can start putting a list together to rule out legit ones.

This will probably be something like Hulu, as they have all sorts of different domains and if you block too many, it just breaks, but if you block to few, nothing happens.

**Comment by mattmill98** [comment]
I'm not running a clean install of pi-hole. Facebook is the main problem yes, however some ads that are blocked leave alot of blank space or messages like this: 
![capture](https://cloud.githubusercontent.com/assets/10357263/12373391/c35656cc-bc6f-11e5-8432-3a1e657387ad.PNG)
Is there anyway to hide these white spaces and messages, i've changed the index.html page to a 1x1 gif but that still wont get rid of it.

I have browsed facebook for a few minutes how can i tell what it was querying?

**Comment by dschaper** [comment]
The ad's with the sad face are typically ads that are served via HTTPS/SSL and those are hard to block. Check #167 and see if you get the same behavior as the others have found.

**Comment by mattmill98** [comment]
Ahh i see, so is it best to have pi-hole and abp for example?

**Comment by dschaper** [comment]
I'm not sure if ABP can block HTTPS ads? I'd think you'd get a security exception trying to intercept secured traffic.

**Comment by mattmill98** [comment]
ABP must just hide it then, as this is what youtube looks like with abp and pi-hole
![capture](https://cloud.githubusercontent.com/assets/10357263/12373741/5d35e7de-bc7b-11e5-9a7e-fdd3f04b8d32.PNG)

**Comment by jacobsalmela** [comment]
ABP and Pi-hole go well together.  Especially for sites that host their own ads.  Pi-hole can't block those without blocking the entire site (although there might be a way using some logic in `lighttpd.conf`).  I'm not quite sure how we could add an element-hider with Pi-hole.

**Comment by mattmill98** [comment]
Would be a great feature if it could happen in the future but obviously everything isn't possible. But i think i've found the best combination for me which is uncommenting host-files.net (to sort out the facebook issue) and running ABP to hide the empty spcae and any other ads. At least now with pi-hole my phone and tablet will have alot less ads on them. Once again thanks for all your help and i'll be sure to donate and update pi-hole in the future :)

**Comment by jacobsalmela** [comment]
Cool, I appreciate that.  It is motivating to keep working on it.

**Comment by PromoFaux** [comment]
Any Facebook may want to update their whitelist..

host-file.net have added scontent-lhr3-1.xx.fbcdn.net which is basically renders the site unreadable.
