### ISSUE TITLE
pihole.log filled with www.google.com queries from RPi itself

### ISSUE THREAD

**Issue by Smultie** [jacobsalmela/pi-hole#166]
Hey, my log is getting pretty big, 90% with lines as below:

Jan 13 20:44:12 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.103
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.147
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.104
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.105
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.106
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.99
Jan 13 20:44:12 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.99
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.103
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.147
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.104
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.105
Jan 13 20:44:12 dnsmasq[1922]: cached www.google.com is 64.233.166.106
Jan 13 20:44:13 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.106
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.99
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.103
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.147
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.104
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.105
Jan 13 20:44:13 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.105
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.106
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.99
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.103
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.147
Jan 13 20:44:13 dnsmasq[1922]: cached www.google.com is 64.233.166.104

10.0.1.5 is the internal IP address of my RPi that's running pi-hole.
Does anyone know why it's querying www.google.com so often?

**Comment by Smultie** [comment]
And a |grep 10.0.1.5 to show the frequency:

Jan 13 20:55:46 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:55:46 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:55:47 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:55:47 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:56:39 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:56:39 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:56:41 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:56:41 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:57:31 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:57:31 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:57:33 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:57:33 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:58:26 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:58:26 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:59:17 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 20:59:17 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 21:00:08 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 21:00:08 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 21:00:11 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5
Jan 13 21:00:11 dnsmasq[1922]: query[A] www.google.com from 10.0.1.5

**Comment by dschaper** [comment]
What processes are running on the Pi? Something is requesting all that... Can you run a `top` or `htop` and see what's running?

**Comment by Smultie** [comment]
It's a pretty new XBian install. So, Debian with built-in Kodi. On top of that, it's running CouchPotato and SickRage. Is there a way to find out what process is doing those queries?

**Comment by dschaper** [comment]
Tail the log and disable the processes individually and see when the queries stop. I would suggest looking at `byobu` so you can have multiple terminal windows open at the same time. Is XBian a Jessie or Wheezy install?

**Comment by Smultie** [comment]
It's Jessie. I'll try what you suggested. Good idea, thanks. 
Will come back to tell what it was!

**Comment by dschaper** [comment]
Thanks, just use the `sudo systemctl stop` function to stop the individual services. I'd be interested to know what is spamming the queries like that (and probably the software developers too!)

**Comment by Smultie** [comment]
Well, it's obviously Kodi itself (or one of it's addons).
Now to find a way to see which of the addons/settings triggers all the
queries.

**Comment by jacobsalmela** [comment]
Sounds like it is probably unique to your system.  I'll close the issue, but please re-open if necessary.  Also, update with what you do find in case other users see the same thing.
