### ISSUE TITLE
YouTube ads/doubleclick issue...

### ISSUE THREAD

**Issue by jsank** [jacobsalmela/pi-hole#167]
Script seems to work nicely, but I noticed on YouTube (and other doubleclick ad networks) that I get the "Unable to Connect" error instead of just the white image/page. Any ideas? I did a fresh install on my pi zero.

**Comment by dschaper** [comment]
Glad to hear the Zero is working! Besides YouTube can you give us a couple of pages where you are seeing the issue?

**Comment by jsank** [comment]
Seems like some issues also on: http://www.theguardian.com

Thanks for the reply, and yes it runs great on my Pi Zero!!

**Comment by jsank** [comment]
btw, not complaining! i would rather see Unable to Connect than an ad =p

**Comment by dschaper** [comment]
We'll take a look and see. Thanks for the report!

**Comment by jacobsalmela** [comment]
Are you blocking IPv6 and IPv4?

(Also, I'm glad to hear it's working on the Zero.  I don't have one yet, but I figured it would probably work.  Are you using a USB-to-Ethernet adapter)?

**Comment by hpincket** [comment]
At the risk of exposing my music tastes, here are some screenshots:

The first is pi hole + adblockpro:
![screen shot 2016-01-14 at 8 31 15 pm](https://cloud.githubusercontent.com/assets/6645114/12343019/fc2b95c0-bafd-11e5-928f-a13621a8d062.png)

This is just pi hole:
![screen shot 2016-01-14 at 8 31 43 pm](https://cloud.githubusercontent.com/assets/6645114/12343020/fc2c3778-bafd-11e5-9bff-f70ac427937d.png)

**Comment by dschaper** [comment]
Thanks, this is on the list of things to review. I appreciate the screencaps so I can see what it is that we need to target.

**Comment by dschaper** [comment]
Looks like that ad is server up via `https` which we aren't able to intercept. It would be considered a Man-in-the-middle attack, and would require a proxy. I think you may have to resort to other means to block secured http traffic.

**Comment by jsank** [comment]
Got it, thank you! And yes that YouTube screenie is what I see too (btw, Gambino will always be donglover to me!). I was using IPv4 and 6, would disabling 6 stop this and allow that ad through?

**Comment by dschaper** [comment]
Disabling IPv6 network wide would stop a lot of ads getting through, but if any of your host systems can access the net via IPv6 then you'll have ad traffic. The real way to check is to try it out and see what your result are, and configure the Pi-Hole to be the best for your specific situation.

**Comment by jsank** [comment]
Ok, thanks. You rock!
