### ISSUE TITLE
How to resolve missing sudo

### ISSUE THREAD

**Issue by ghstwhl** [jacobsalmela/pi-hole#169]
In trying to install on a fairly bare fresh install, the script failed on every command that invoked sudo.

To resolve, I would suggest running 'apt-get install sudo' fairly early on in your script, to make sure it is present.

**Comment by dschaper** [comment]
Which distribution are you running? (Some distro's have sudo installed and some don't...)

**Comment by ghstwhl** [comment]
Well, in my case I was installing to a bare Debian 8.x install in a VM; so I'm not really your true target audience.  :)

Still, installing sudo, or at least checking to see if it is installed, would resolve the issue of it not being part of base in some distros.

-Sent from my Pip-Boy 3000

**Comment by fmjensen** [comment]
```apt-get -y install sudo``` did the trick for me when i installed pi-hole on minibian distro :-)
http://munkjensen.net/wiki/index.php/See_my_Pi-Hole#Minibian_Pi-hole

**Comment by dschaper** [comment]
I thought we had a fix in for the `sudo` issue, but I'm not sure... Some of the minimal distro's don't ship with `sudo`, so we do need to see if it's installed.

**Comment by ghstwhl** [comment]
Yes, same here. But the script would not error out if sudo was automatically installed.

My ticket is to report an error that I saw, and suggest a resolution that would ideally be implemented in the tool itself. :)

-Sent from my Pip-Boy 3000

**Comment by ghstwhl** [comment]
dschaper: To be fair, I was running the install command from the main website, which I did not verify is running the same version here on github; so there might be a fix you've implemented that wasn't in the version I am testing.  I can test the latest code from github, in a fresh VM, if that would help.

**Comment by jacobsalmela** [comment]
I tried a Minibian install a while back and ran into the `sudo` issue.  One solution I started working on was checking if it was installed:

```
dpkg-query -s -f='${Status}' sudo
```

I think this will fall in with the `sudo` priveleges milestone, but I'll also classify it as a bug.

**Comment by ghstwhl** [comment]
A simple bash -f test against the location of the binary would suffice as well. 

-Sent from my Pip-Boy 3000

**Comment by jacobsalmela** [comment]
What is the `-f` option?

**Comment by ghstwhl** [comment]
-f is a bash file test operator, useful in conditional tests.

http://www.tldp.org/LDP/abs/html/fto.html

**Comment by jacobsalmela** [comment]
I would actually like to get it to work in Debian, which would make testing easier.  Then I could use a VM instead of re-writing SD cards every 10 minutes.  There are a few guides to emulate a Raspberry Pi in a VM but they seem to be a bit convoluted.

**Comment by ghstwhl** [comment]
I have it working in Debian. The only issue I had was the missing sudo package, which was easy enough to resolve. If you move the sudo command to a variable, and only populate the variable if the user is not root, and sudo is installed, it would eliminate that issue. 

-Sent from my Pip-Boy 3000

**Comment by jacobsalmela** [comment]
That's kind of what we were talking about [here](https://github.com/jacobsalmela/pi-hole/pull/153).  I have been testing this out and it seems to work:
```
SUDO=""
if [[ $EUID -ne 0 ]]; then
    SUDO="sudo"
fi
```
