### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by ajitam** [jacobsalmela/pi-hole#17]
Hi, I successfully installed pi-hole on Raspberry (B) for the first time, just to test it out, then I formated SD card to fresh image a now when I run installation script I always get

```
[....] Restarting DNS forwarder and DHCP server: dnsmasq
dnsmasq: cannot fork into background: Cannot allocate memory
 failed!
Restarting services...
No resolv.conf for interface lo.dnsmasq
[....] Restarting DNS forwarder and DHCP server: dnsmasq
dnsmasq: cannot fork into background: Cannot allocate memory
 failed!
[ ok ] Stopping web server: lighttpd.
[ ok ] Starting web server: lighttpd.
```

I also tried on B+ with same result. Any ideas?

**Comment by jacobsalmela** [comment]
You might be out of memory.  Can you lower the amount given to the GUI via `sudo raspi-config`?

**Comment by ajitam** [comment]
hmm that actually worked. I don't remember setting this the first time (when installation was successful)

thx

**Comment by enjunear** [comment]
I've run into the same problem, even after allocating the minimum memory (16) to the gui.
