### ISSUE TITLE
Not working with nginx

### ISSUE THREAD

**Issue by magarto** [jacobsalmela/pi-hole#171]
Hi,

I have installed nginx to work with 80 and 443 ports.
After installing pi-hole, i can see that lighttpd is not started due to it tries to open port 80 which is already started by nginx. So I can see that:
- Ads removed displays 0 value but domains blocked shows correct data.
- It seems that because lighttpd is not started, Pi-Hole is not working.

I tried to change lighttpd port to another like 81 and now service is started but I can see that ads are not blocked.

Some time before I managed to make Pi-Hole working but some pop-up ads are still displayed like the one if you open gnula.nu
I tried to find a hosts file to add which stops those pop-ups with no luck.

**Comment by iblamefish** [comment]
The reason that changing the port won't work in this case. Pi hole blocks ads by getting in the way and pretending to be the server which hosts the ad - it therefore need to be running on port 80.

**Comment by dschaper** [comment]
Are you running another website with nginx? I'll have to see how the configuration works for nginx to see if there is a way to run the Pi-hole along with another hosted site at the same time. I'm not sure if it's compatible, but we'll check and see and add that functionality if it's possible. We have some bugs to take care of first, so it may take some time to add that functionality. 

As @iblamefish noted, the way the Pi-Hole works is to redirect calls to external ad domains back to the Pi-Hole and that needs port 80 to work properly. Is it possible to run your website on a different IP address (eth0:0) on the Pi and then forward calls at your router to the new address for your existing domain?

**Comment by magarto** [comment]
Yes, I have another sites running in Nginx and I cannot use another port :(
I hope you managed to have nginx features

**Comment by dschaper** [comment]
Does your site have a domain name? And Is nginx set up to serve via that domain name? (Is it possible to see the nginx configuration you are using for the site(s)?)

**Comment by magarto** [comment]
Yes, of course, two sites (with domain name):

First one, mysite.com:

server {
    listen 80 default_server;
#    listen [::]:80 default_server;
    rewrite ^ https://$host$request_uri permanent;
    server_name mysite.com;
    ## Only requests to our Host are allowed i.e. nixcraft.in, images.nixcraft.$
    if ($host !~ ^(mysite.com)$ ) {
        return 444;
        }
    }

server {
    listen 443 default_server;
#    listen [::]:443 default_server;
    ssl on;
    ssl_certificate	/etc/letsencrypt/live/mysite.com/fullchain.pem;
    ssl_certificate_key	/etc/letsencrypt/live/mysite.com/privkey.pem;

    server_name mysite.com;

	proxy_redirect          off;
	proxy_set_header        Host            $host;
	proxy_set_header        X-Real-IP       $remote_addr;
	proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

    location / { 
        try_files $uri $uri/ @htmlext;
    }   

    location ~ \.html$ {
        try_files $uri =404;
    }   

    location @htmlext {
        rewrite ^(.*)$ $1.html last;
    }   

	server_tokens off;

	##
	## Only allow these request methods ##
	if ($request_method !~ ^(GET|HEAD|POST)$ ) {
		return 444;
	}
	## Do not accept DELETE, SEARCH and other methods ##
	## Block download agents ##
	if ($http_user_agent ~* LWP::Simple|BBBike|wget) {
		return 403;
	}
	##
	## Block some robots ##
	if ($http_user_agent ~* msnbot|scrapbot) {
		return 403;
	}
	## Deny certain Referers ###
	if ( $http_referer ~* (babes|forsale|girl|jewelry|love|nudit|organic|poker|porn|sex|teen) )
		{
		# return 404;
		return 403;
	}
	##

	access_log  /var/log/nginx/mysite.access.log;
	error_log /var/log/nginx/mysite.error.log;
	root   /home/pi/www/mysite.com/public_html/;
	index index.php index.html;

	location ~ \.php$ {
	       # With php5-fpm:
                fastcgi_pass unix:/var/run/php5-fpm.sock;
#		fastcgi_pass 127.0.0.1:9000;
		try_files $uri =404;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
		}

        location /robots.txt {
                return 200 "User-agent: *\nDisallow: /";
                }

	location /phpmyadmin {
		auth_basic "Admin Login";
		auth_basic_user_file /etc/nginx/pma_pass;
    }
}

**Comment by dschaper** [comment]
Just off the top of my head, Pi-Hole would have to be the default server because it is set to catch any domain that is sent to it, so you would need to change `listen 80 default_server` to `listen 80 mysite.com`. I don't know of a way to do that via a bash script, so you would have to set it up manually to fit your configuration.

**Comment by magarto** [comment]
I have edited the comment above

**Comment by magarto** [comment]
Ok, I can do it, but anyway lighttpd cannot be started in 80 port so I think it would not help enough

**Comment by dschaper** [comment]
That is correct, the Pi-Hole server would have to be set up to use `nginx` instead of `lighttpd`. If you look at the `lighttpd.conf` you can probably duplicate how it functions inside `nginx`. I'll try to take a look later and see if I can write up a configuration, but it may take a while to do...

**Comment by magarto** [comment]
Thanks, I'm so sorry but I don't have enough nginx/lighttpd/apache knowledge to handle it...
The only thing I did was ln -s /var/www/html/pihole to my site/pihole directory

**Comment by jacobsalmela** [comment]
@magarto it's also possible to change the `lighttpd` port...not sure if that helps you or not.

```
server.port = 3000
```
or

```
$SERVER[“socket”] == “:81” {
server.document-root = “/var/www/html/pihole”
}
```

Either way it sounds like a customization you might need to work on.  We can certainly try to help, but I will close this issue as it's out of the scope of a problem with Pi-hole itself.

**Comment by hatcreek68** [comment]
can we re-open this until there is a firm solution for people who want to run nginx and pi-hole?

I see potential solutions on the net but seem to get them working.
- add extra ip on the pi to split serives
- move nginx to another port
- disable lighttpd, setup nginx/pi-hole together

Is there an accepted solution ([this maybe](https://github.com/pi-hole/pi-hole/wiki/Nginx-Configuration)?)? 
hard to tell what are ideas and what is the 'official unofficial' answer since pihole+nginx is not officially supported.

**Comment by dschaper** [comment]
The official answer is that `nginx + pihole` is not supported. If you would like to discuss this on https://discourse.pi-hole.net you may find other users that have other solutions. We will not be reopening this issue.
