### ISSUE TITLE
SSL encryption puts kibosh on Pi Hole?

### ISSUE THREAD

**Issue by gaaah** [jacobsalmela/pi-hole#172]
Sorry for posting this noob question here, but pi-hole.net/help is not accepting posts.  

I read in an Amazon review of the AdTrap that ever since Dec 2015 it hasn't worked so well because now the advertisers started using SSL encryption to pipe their ads.  Does this change also put the kibosh on Pi Hole in any way?

**Comment by dschaper** [comment]
Pi-Hole will still block the ads. You may see broken link placeholders instead of blank gifs if the ad is served via HTTPS, but the ad will still be blocked. You can see what that looks like at #167

**Comment by jsank** [comment]
Yep, it's better than serving up the ad in my opinion. Great work!

**Comment by jacobsalmela** [comment]
@gaaah, pi-hole.net does accept the FAQs you submit, but they often are vague in nature and I cannot figure out what is being asked so I apologize if your question was missed.
