### ISSUE TITLE
NAS can't access outside world (DDNS) on default settings when running pihole

### ISSUE THREAD

**Issue by Smultie** [jacobsalmela/pi-hole#178]
My router (Apple Airport Extreme) is 10.0.1.1 I changed the router's DNS settings to 10.0.1.5 primary (rpi running pi-hole) and 8.8.8.8 secondary.

With the default settings on my NAS (10.0.1.2) it can't connect to the outside world, at least, not the DDNS settings. It times out, and I don't see the query in the pi-hole.log
If I set the DNS settings manually on my NAS (10.0.1.5 and 8.8.8.8) it can connect to the DDNS server.

BUT...... when set like that, my NFS server doesn't work :(

What to do??

**Comment by DonLexos** [comment]
Are you sure you did not set your gateway wrong and mixed that up? I believe the pi-hole setup assumes 192.168.1.x like networks, which you can change but you need to make sure you change the gateway to (in your case) 10.0.0.1, otherwise it will fail (because 192.168.1.1 (default) leads to nowhere in your network).

**Comment by jacobsalmela** [comment]
That's probably the best place to start.  It just uses your default gateway, unless you changed it during the install.

**Comment by Smultie** [comment]
Funny enough, all other devices work without problems.
How would I change the pihole's gateway when it's already installed?

**Comment by jacobsalmela** [comment]
It's set at the bottom of `/etc/dhcpcd.conf`:
```
static routers=192.168.1.1
```

**Comment by Smultie** [comment]
It's already correct I guess?

interface eth0
static ip_address=10.0.1.5/24
static routers=10.0.1.1
static domain_name_servers=10.0.1.1

**Comment by jacobsalmela** [comment]
Is your NAS and/or your NFS statically assigned an address?

**Comment by Smultie** [comment]
All my devices are statically set in my router

**Comment by jacobsalmela** [comment]
via DHCP reservation?

**Comment by Smultie** [comment]
Static

**Comment by Smultie** [comment]
So, I guess?

**Comment by jacobsalmela** [comment]
If using reservations, all you should need to do is [set the DNS server in the DHCP options section of your router](http://pi-hole.net/faq/can-i-set-the-pi-hole-to-be-the-dns-server-at-my-router-so-i-dont-have-to-change-settings-for-my-devices/).

**Comment by Smultie** [comment]
Thanks. I ain't home, so can't check my router to see if  has that setting. What if it doesn't have it though?!

**Comment by Smultie** [comment]
https://drive.google.com/file/d/0B0aPFEhjzf34ckU4SHYxdUpfTjQ/view?usp=sharing

**Comment by Smultie** [comment]
Right, just checked it, I don't think I can set the DNS server in my router.
Any other option to get my NAS connected to the outside world, while keeping the option to run the NFS server internally?

**Comment by Smultie** [comment]
I also noticed I can't use the NAS's VPN service with above settings

**Comment by Smultie** [comment]
These are the settings in my NAS:

https://drive.google.com/file/d/0B0aPFEhjzf34MXlhSFpiakU3RE0/view?usp=sharing

**Comment by DonLexos** [comment]
If you would add the pi-hole in your router as dns server DHCP should work since it will provide all details to your nas, there is no need to override that (except maybe for a static IP on the NAS)

**Comment by Smultie** [comment]
I can't. My router doesn't have that option it seems.

**Comment by Smultie** [comment]
Right, made some progress.

On my NAS I set DNS1 to 10.0.1.1 (which is the router) and DNS2 to 8.8.8.8

That way I have both NFS and external access on my NAS.

One small thing remains though; no internet through my VPN, which I find strange. I'll dive into that as well.

**Comment by DonLexos** [comment]
Could be that since your DNS is set to an internal IP as soon as you connect to your VPN you should get external DNS (like google 8.8.8.8 or more likely their own DNS) however since you did an override to a local IP that is not in the new network (which you get when connecting to a VPN) it cant be found. Try to dig/ping some sites when you connect to see where you end up (either local, failed, etc).

**Comment by jacobsalmela** [comment]
Can you show a screenshot of your DHCP server settings on the router?

**Comment by Smultie** [comment]
Sure:

https://drive.google.com/file/d/0B0aPFEhjzf34VVdwQTU0THM0RDg/view?usp=sharing

Got even bigger problems now. Tried resetting the IP/DNS settings of the NAS, and now I can't find the NAS in the network anymore ><

**Comment by Smultie** [comment]
Update!
Reinstalled the software on my NAS, and all seems to be working as it should now!

Thanks for all the help guys, much appreciated!

**Comment by dschaper** [comment]
Great to hear!

**Comment by Smultie** [comment]
Damn, spoke too soon! :(
After a reboot the NAS is no longer part of the network.
This one is really making me pull out my hair.

I imagine I can't be the only one with a Synology NAS, right?

**Comment by dschaper** [comment]
Why do you have the NAS set as the Default Gateway?

**Comment by dschaper** [comment]
Have you tried setting the Synology NAS to DHCP mode, and at the Airport Extreme, go to the `Network` tab and set a `DHCP Reservation` for the NAS to have a Static DHCP Reservation.

**Comment by Smultie** [comment]
@dschaper I don't think I have the NAS set as Default Gateway? Could you show me where that would be the case?

To be clear
Router = Airport Extreme = 10.0.1.1
NAS = Synology DS213 = 10.0.1.2
DNS server = RPi2 = 10.0.1.5

Please let me know if I've set anything wrong anywhere.
I'm pretty sure 10.0.1.1 should stay the Gateway (as set in the NAS's settings, right?)

Also, my NAS already has a static IP (10.0.1.2) as set in my router. I'm not at home right now, so can't give you the screenshot.

After resetting the NAS yesterday, this is what the NAS set itself:
https://drive.google.com/file/d/0B0aPFEhjzf34MXlhSFpiakU3RE0/view

**Comment by dschaper** [comment]
There's a check in the Default Gateway box, so I assumed (perhaps incorrectly) that was done manually.

**Comment by Smultie** [comment]
But on first sight: anything set wrong?

**Comment by dschaper** [comment]
So the router (the Airport Extreme) has a MAC address based Reservation for the Synology? And the Synology is set to receive it's address via DHCP?

**Comment by Smultie** [comment]
First Q: yes
Second Q: it's set manual, but I can also set it on auto, see https://drive.google.com/file/d/0B0aPFEhjzf34MXlhSFpiakU3RE0/view

**Comment by dschaper** [comment]
Try setting the Synology to get it's address via DHCP then.

**Comment by Smultie** [comment]
That's in the NAS's settings, right (just to be sure!)

**Comment by dschaper** [comment]
Yes, click the button for `Get Network Configuration Automatically (DHCP)`

**Comment by Smultie** [comment]
Right, will do that after I'm home.

Will first have to reinstall the NAS (again) cause there's no way for me to
connect to it right now :)

**Comment by Smultie** [comment]
Also: one more question.
What should the DNS server actually be at the NAS? 10.0.1
1 (which should redirect it to 10.0.15) or 10.0.1.5?

**Comment by dschaper** [comment]
If you have the router set up to serve the DNS address then the NAS will pick it up via DHCP just like all the other clients on the network.

**Comment by Smultie** [comment]
Right, and I have dont that right (set the router to server DNS)?
https://drive.google.com/file/d/0B0aPFEhjzf34VVdwQTU0THM0RDg/view

**Comment by dschaper** [comment]
Your IPv4 looks okay, but the IPv6 looks a bit off?

**Comment by Smultie** [comment]
Yeah, I tried "translating" from IPv4 to IPv6. I'll set them back to blank, as they were before.

**Comment by dschaper** [comment]
Did you run the `basic install.sh` and enable IPv6? It should give you the IPv6 address to put in the router.

**Comment by dschaper** [comment]
`ip -6 route get 2001:4860:4860::8888 | awk -F " " '{ for(i=1;i<=NF;i++) if ($i == "src") print $(i+1) }'` 

That will also give you the IPv6 address. Copy and run that command on the Pi at a terminal prompt.

**Comment by Smultie** [comment]
@dschaper any way to run basic install.sh again?
I installed pi-hole with 'curl -L install.pi-hole.net | bash'

**Comment by dschaper** [comment]
Run the `curl` command again, and it will run the latest version of `basic install.sh`.

**Comment by Smultie** [comment]
Alright, will do that tonight when I'm home!

Thanks for all the help, @dschaper !!

**Comment by Smultie** [comment]
Right, back to troubleshooting.

I've rerun the curl+bash thingie, set up like below.
https://drive.google.com/file/d/0B0aPFEhjzf34RGdBX0Rya0U0R0U/view?usp=sharing
https://drive.google.com/file/d/0B0aPFEhjzf34bWFQcjFCNW1jSVk/view?usp=sharing
Nothing wrong there, I guess?

I've changed my router's DNS settings to only have the Pi-hole mentioned 10.0.1.5
https://drive.google.com/file/d/0B0aPFEhjzf34U25WQVBPY0wwaXc/view?usp=sharing
The 2nd IP address is the one from my ISP I guess, but I didn't set up. You can see it's grey instead of black.

Next up: reinstalling the NAS!

**Comment by Smultie** [comment]
After the reinstall of the NAS's software/firmware, the settings as is related to network/DNS are:
https://drive.google.com/file/d/0B0aPFEhjzf34cWRFbVB0V20wWVU/view?usp=sharing
https://drive.google.com/file/d/0B0aPFEhjzf34WkdENnlVME5lM0E/view?usp=sharing
Nothing wrong there I guess?

Now, I'm going to further install the NAS (download station, NFS, etc)

**Comment by dschaper** [comment]
Are you able to clear the checkmark from the Default Gateway box on the second page? I think that setting may be causing problems.

**Comment by Smultie** [comment]
When I clear it, it automatically gets re-enabled.

**Comment by dschaper** [comment]
Okay, I may have to do some reasearch on that config flag. For now let's proceed and see how the configuration goes. Can you post a screenshot of your Airport Express Network Tab? I'd like to see the Static Reservation information just to make sure that's all looking good, if you don't mind?

**Comment by Smultie** [comment]
Sure: don't hack my shit ;)

https://drive.google.com/file/d/0B0aPFEhjzf34aXFwUjNOMW9qN1U/view?usp=sharing

**Comment by dschaper** [comment]
Don't worry, and I don't know your public IP anyways.

**Comment by dschaper** [comment]
Okay, looks good... Let's see what happens!

**Comment by dschaper** [comment]
And not to be the School Principal, but can you edit your comment for language, I promise I won't hack your stuff... :)

**Comment by Smultie** [comment]
Well, gonna reboot the NAS, wish me luck :)

**Comment by Smultie** [comment]
Wow, so far so good
!

**Comment by dschaper** [comment]
That's good news!

**Comment by Smultie** [comment]
Welp... 
YOU GOTTA BE KIDDING ME!!!

I had the NAS on my desk to reset the thing. All worked.
I turned it off, back on again, all worked.

I turn it off, put it back on it's place.
Doesn't work

I'm going crazy!!!!

**Comment by dschaper** [comment]
Are you using different ethernet cables from when you have it plugged in at your desk versus plugged in where it's home is?

**Comment by Smultie** [comment]
No...

**Comment by dschaper** [comment]
Okay, and the NAS works okay without PiHole?

**Comment by Smultie** [comment]
Well, it did, but I'm starting to think it's more of a NAS-issue now ><

**Comment by dschaper** [comment]
Sorry, I edited the comment, didn't see you were on email. Does the NAS work okay if you put it back on the desk?

**Comment by Smultie** [comment]
Just installing it now on the right spot....
Maybe the cable was a bit flaky ??? 
Plugged in another one just to be sure.

I'm pretty exhausted right now, so I think I'll just set it up so I can VPN tomorrow.

**Comment by dschaper** [comment]
We'll solve it somehow. I also had the thought that the cable or the keystone jack may be off. When it's at it's intended location how is it connected? Do you plug into a keystone in the wall or to a switch? If it's a switch there may be some port blocking going on...

**Comment by Smultie** [comment]
From the NAS straight into the router. Lights were blinking on both sides, even when the NAS wasn't reachable over the network...

**Comment by dschaper** [comment]
Okay, if it persists in being problematic, we may need to do some ARP work to track down on a lower level of the network...

**Comment by Smultie** [comment]
Sounds interesting ;)
Yet I hope it won't be necessary

As again, thanks for your help Dan! Really appreciate it!
Get back to you tomorrow!

**Comment by Smultie** [comment]
Well, new day, new opportunities ;)

Turned out my NAS decided to auto-restart due to an update it had to install. All worked after it!!
Currently setting up firewall rules for my NAS. 
Still a bit scared to reboot the NAS.
Also, should I enter a second DNS server (8.8.8.8?) ony my NAS, cause if the Pi crashes, no connection to my NAS = no VPN, etc etc.

**Comment by dschaper** [comment]
I'd leave the NAS configuration set as DHCP and add the secondary DNS to the Airport Extreme DHCP Server configuration. If things are stable we next need to check and see if you need IPv6 support on your network. A good way to check is to visit `osxdaily.com` and see if you are served any ads. That's one of our test sites and they serve a lot of ads via IPv6.

**Comment by dschaper** [comment]
Did the firmware update for the Synology have a changelist? I wonder if they updated/fixed something to do with the networking aspect. If it's still working after a reboot, then hopefully we're close to getting you all set up and sorted out.

**Comment by Smultie** [comment]
I've had the newest firmware update installed on my previous 'sessions' as well; also when the NAS wasn't reachable after putting it back on it's usual spot, so it's not the firmware that's fixing it.

NAS is still on Auto DHCP and the Router has 10.0.1.5 manually entered as primary DNS server and auto populates the second DNS server from my ISP, as shown yesterday. I'm still not 100% certain that my NAS has a secondary DNS server to fall back to when my RPi2 decides to crash...

**Comment by dschaper** [comment]
@Smultie How is the situation going? Anything else we need to troubleshoot?

**Comment by Smultie** [comment]
So far everything it working, still!
Gotta admit though, I'm not restarting the NAS until I absolutely 100% I have to ;)

**Comment by dschaper** [comment]
Great to hear! Do you mind if I close this out for now then?

**Comment by Smultie** [comment]
Not at all.
One last time; just to be sure.
Thank you very much for all your help in the matter, Dan!
