### ISSUE TITLE
Version number + installation question

### ISSUE THREAD

**Issue by DonLexos** [jacobsalmela/pi-hole#179]
Curious about all the progress since 2.0 I bought a new SD card, installed Wheezy and used the fancy new script to install the latest version of PiHole. Installation sure got easier, good work!

To my surprise the admin interface shows version 2.1 even though latest version should be 2.2. Not sure if that is some variable in the admin interface or that it actually fetches it somewhere. I checked /usr/bin/local/gravity.sh and could not find the version number mentioned there. 

Does the automated installer flush the 'ads blocked' in a daily cron or is that something that should be added manually (I can't find it).

**Comment by jacobsalmela** [comment]
The Pi-hole is a culmination of different software (`lighttpd` and `dnsmasq`) and [scripts](https://github.com/jacobsalmela/pi-hole/tree/master/advanced/Scripts), so there isn't really a `piholed` daemon or anything.  

That said, the version number in the Web interface is just a manually set number.  This can probably be resolved with the `[webinterface.sh` script](https://github.com/jacobsalmela/pi-hole/blob/master/automated%20install/webinterface.sh), which uses `git` to keep things up-to-date.  So as long as we set the version number in the interface at the same time it is changed in the releases, this should fix it.

I suppose we could also add version numbers to the scripts, but that's probably more trouble than it's worth.

Yes, the "ads blocked" gets flushed daily via [this `cron`](https://github.com/jacobsalmela/pi-hole/blob/master/advanced/pihole.cron#L26).

**Comment by DonLexos** [comment]
Ok sounds good. For me no need to have version numbers anywhere but since 2.2 is out for a week I was curious if I did something wrong on my end. No clue what best practice is but if there is a folder that contains the pihole files a verion.txt could be used that just contains the version (or date) of installation. 

Regarding the cron: excellent!

**Comment by jacobsalmela** [comment]
No, you didn't do anything wrong.  It's just me not being able to keep up with this growing project!
