### ISSUE TITLE
blacklist.sh has erroneous CRLF items, causing it to malfunction

### ISSUE THREAD

**Issue by shadowkhas** [jacobsalmela/pi-hole#181]
Hi guys,

Thanks for the awesome fixes on the whitelist/blacklist stuff! It fixed my problem that I was having. :)

blacklist.sh looks like it has some troubles though - it's got CRLF items in the line breaks, which is causing problems executing the script. A "cat -v whitelist.sh" and "cat -v blacklist.sh" will show the differences - whitelist.sh doesn't  have any of the "^M" items, blacklist.sh does. Taking those out with vi seemed to get blacklist.sh working again for me.

**Comment by PromoFaux** [comment]
I'll take a look at this In  the morning, might be something to do with the settings In my editor before I committed.  Although to use an old coding trope...  "it worked on my machine"  :)

**Comment by PromoFaux** [comment]
This is what happens when you develop on windows, and forget to save in UNIX mode...

Should be fixed now @shadowkhas

**Comment by jacobsalmela** [comment]
I believe this is fixed by #189 now.
