### ISSUE TITLE
Error When Running gravity.sh to Update List - Raspian Jessie

### ISSUE THREAD

**Issue by gh0stshell** [jacobsalmela/pi-hole#188]
New install of Raspian Jessie on a Pi 2 and Pi B, using one for testing and one for live. When adding a list and running ./gravity.sh I get the following:

./gravity.sh
./gravity.sh: line 59: syntax error near unexpected token `;'
./gravity.sh: line 59: `if [[ -r $piholeDir/pihole.conf ]];then'
** Local calibration requested...
./gravity.sh: line 61: /pihole.conf: No such file or directory
./gravity.sh: line 62: syntax error near unexpected token `fi'
./gravity.sh: line 62: `fi'

Should I not be using the latest Raspian Jessie? I see one issue regarding that version of Raspian. I just created the pi-holes a couple of hours ago.

**Comment by dschaper** [comment]
Can you run the `curl` command again and grab the latest version of the install script?

**Comment by gh0stshell** [comment]
I will wipe both pi's and reinstall from scratch.

should I be using raspian jessie or raspian wheezy?

**Comment by gh0stshell** [comment]
I installed both pi-hole pi's a few hours ago, did the script change since I last installed it?

**Comment by jacobsalmela** [comment]
It looks like you are using a local config file.  I wonder if that has something to do with it.  There have been a decent amount of changes in the last day or two.

**Comment by gh0stshell** [comment]
should I be using raspian jessie or raspian wheezy?

I installed Raspbian Jessie and then ran curl -L install.pi-hole.net | bash

**Comment by gh0stshell** [comment]
I am prepared to reflash both Pi's once the above questions have been answered.

**Comment by dschaper** [comment]
You can run Jessie. I do all my testing with the Raspbian Jessie Lite version of the distribution, less overhead. If you need the desktop environment I'd go for the full Raspbian Jessie version.

**Comment by dschaper** [comment]
Before you do that, what is the contents of your `pihole.conf` file?

**Comment by jacobsalmela** [comment]
Yeah, I use Jesse miminal for speed and I do everything headless.

**Comment by gh0stshell** [comment]
I already have both Pi's off and both cards right next to me. Should I power one on before I reflash and get you that conf? I will get you the conf from the one I ran the ./gravity.sh on. I will reflash the card for the Pi 2 and download jessie lite. What do I need to do to get the LCD working?

**Comment by gh0stshell** [comment]
Flashing Raspian Jessie Lite now for the Pi 2, powering up the Pi to get you the conf, will post the conf shortly.

**Comment by gh0stshell** [comment]
Apprently I do not have a pihole.conf under /etc/pihole

If I run a lookup for the pihole.conf file it says it is in /etc/pihole but there is no conf file

**Comment by dschaper** [comment]
Okay, that could be a problem. Did you edit the `pihole.conf` file when you were setting up the added blocklist site?

**Comment by gh0stshell** [comment]
pi@pi-hole:~ $ whereis pihole.conf
pihole: /etc/pihole
pi@pi-hole:~ $ ls /etc/pihole/
gravity.list                              list.5.someonewhocares.org.domains
gravity.list.01172016                     list.6.winhelp2002.mvps.org.domains
install.log                               pihole.0.matterandlight.txt
list.0.adaway.org.domains                 pihole.1.supernova.txt
list.1.adblock.gjtech.net.domains         pihole.2.eventHorizon.txt
list.2.hosts-file.net.domains             pihole.3.accretionDisc.txt
list.3.www.malwaredomainlist.com.domains  whitelist.txt
list.4.pgl.yoyo.org.domains

**Comment by gh0stshell** [comment]
No per this article:  http://jacobsalmela.com/block-millions-ads-network-wide-with-a-raspberry-pi-hole-2-0/

I am to edit the gravity.sh file

**Comment by gh0stshell** [comment]
These are the steps I followed:
Flash Raspbian Jessie
Expand File System
Rename Host
Reboot
Login again
Run curl command from github/pi-hole.net site
Follow prompts and let it finish

Then the following to gravity.sh

Added 1 entry to the list of sites, added entry to case section and saved
Then ran ./gravity.sh

**Comment by dschaper** [comment]
Can you do a `ls -lac /etc/pihole/`?

**Comment by gh0stshell** [comment]
pi@pi-hole:~ $ ls -lac /etc/pihole/
total 27052
drwxrwxrwx   2 root root    4096 Jan 17 15:38 .
drwxr-xr-x 111 root root    4096 Jan 17 00:58 ..
-rw-rw-rw-   1 root root 6159622 Jan 17 02:12 gravity.list
-rw-r--r--   1 root root 6159622 Jan 17 15:38 gravity.list.01172016
-rw-rw-rw-   1 pi   pi     34710 Jan 17 01:59 install.log
-rw-rw-rw-   1 root root   13643 Jan 17 01:59 list.0.adaway.org.domains
-rw-rw-rw-   1 root root   23846 Jan 17 01:59 list.1.adblock.gjtech.net.domains
-rw-rw-rw-   1 root root 1795072 Jan 17 01:59 list.2.hosts-file.net.domains
-rw-rw-rw-   1 root root   48945 Jan 17 01:59 list.3.www.malwaredomainlist.com.   omains
-rw-rw-rw-   1 root root   41186 Jan 17 02:07 list.4.pgl.yoyo.org.domains
-rw-rw-rw-   1 root root  373083 Jan 17 01:59 list.5.someonewhocares.org.domain
-rw-rw-rw-   1 root root  508717 Jan 17 01:59 list.6.winhelp2002.mvps.org.domai   s
-rw-rw-rw-   1 root root 2740781 Jan 17 02:11 pihole.0.matterandlight.txt
-rw-rw-rw-   1 root root 1886118 Jan 17 02:11 pihole.1.supernova.txt
-rw-rw-rw-   1 root root 1712051 Jan 17 02:12 pihole.2.eventHorizon.txt
-rw-rw-rw-   1 root root 6159622 Jan 17 02:12 pihole.3.accretionDisc.txt
-rw-rw-rw-   1 root root       0 Jan 17 01:59 .useIPv6
-rw-rw-rw-   1 root root     125 Jan 17 01:59 whitelist.txt

**Comment by dschaper** [comment]
And do you mind putting up a copy of the `sources` list?

**Comment by gh0stshell** [comment]
which sources?

**Comment by gh0stshell** [comment]
This pi is the only one I changed at all with the above entries I listed above

**Comment by dschaper** [comment]
I'm trying to figure out why you have a `-rw-r--r-- 1 root root 6159622 Jan 17 15:38 gravity.list.01172016` entry. That's throwing things off, so I think there may be something about the list you are adding, or how you added the list. So if we could see the configuration we may be able to solve the issue without needing to reflash the SDCard.

**Comment by gh0stshell** [comment]
I dont mind starting from scratch. I did it a few times today and I already reflashed the Pi 2 card. That entry you see is from me cp the gravity.list as a backup in case adding more domains as shown in another article from that same site caused poor performance. I wanted to backup the initial list so I had something to go back to. Now that I think about it I could have just taken the one from the Pi 2 instead of cp the file.

**Comment by dschaper** [comment]
Okay, then go ahead with the reflash, and let us know how it goes.

**Comment by gh0stshell** [comment]
I only added 1 entry to the source list, added 1 entry to the case section, and cp the gravity.list as a backup.

**Comment by gh0stshell** [comment]
How can I get the LCD to show what the web gui admin page shows?

**Comment by jacobsalmela** [comment]
The line
```
./gravity.sh: line 59: syntax error near unexpected token ;' ./gravity.sh: line 59:if [[ -r $piholeDir/pihole.conf ]];then'
```
is looking for a pihole.conf file, which is how people can further customize their install.  I don't know of too many people who use it, but I agree that `gravity.list.01172016` entry is doing something.

**Comment by gh0stshell** [comment]
I am firing up the Pi 2 now and doing the steps I listed above.

**Comment by gh0stshell** [comment]
I will reflash the Pi card whiling working on the Pi 2

**Comment by jacobsalmela** [comment]
That is accomplished via [`chronometer.sh`](https://github.com/jacobsalmela/pi-hole/blob/master/advanced/Scripts/chronometer.sh).  Instructions for getting that to work can be found [here](http://pi-hole.net/faq/install-the-real-time-lcd-monitor-chronometer/).

**Comment by gh0stshell** [comment]
Great thanks!

I have just expanded the filesystem, renamed the hostname, change the timezone and just rebooted the PI 2.

I will be running curl -L install.pi-hole.net | bash once it is back up

**Comment by dschaper** [comment]
The install script runs `gravity.sh` once, so if the install goes okay then we know that everything is good to go at a stock install.

**Comment by gh0stshell** [comment]
running curl -L install.pi-hole.net | bash now on the Pi 2

just finished flashing the Pi card

**Comment by gh0stshell** [comment]
Question on adding to the sources case section.

In the article is shows the case section with this: 
                       "pgl.yoyo.org")
			cmd="curl -d mimetype=plaintext -d hostformat=hosts"

When I went to add to the case section all the cmd entries showed without curl, am I suppose to add that in or did you add it into the script so all I need is the additional command to filter the list correctly?

**Comment by dschaper** [comment]
The only thing that should be added to the scripts is a `"new.source.list"` to the `sources` array.

**Comment by dschaper** [comment]
Do you know how the new list is formatted? Can you tell us what the new list is?

**Comment by jacobsalmela** [comment]
I mention in that article that the code has been refactored quite a bit, so that the explanation of how the script works is a bit outdated, but it should provide a basic understanding of the script.  Don't follow it step by step.

You only need to add it to the `case` statement if the list needs special formatting.

**Comment by gh0stshell** [comment]
This is the list I was going to add from the article as a test: https://hosts.neocities.org/

It was updates recently if you click on the link and check the top date

**Comment by gh0stshell** [comment]
It does need to be formatted to remove the first line and only pull the domain as listed in the article

**Comment by dschaper** [comment]
Formatting is handled by `gravity.sh` already, since the list is in `hosts` format it should be fine as it is.

**Comment by gh0stshell** [comment]
That list shows as 

0.0.0.0 0.r.msn.com
0.0.0.0 000007.ru
0.0.0.0 0000mps.webpreview.dsl.net
0.0.0.0 0001.2waky.com
0.0.0.0 000webseucadastro.vai.la

**Comment by gh0stshell** [comment]
OK, I will after install just add that URL

**Comment by gh0stshell** [comment]
Pi is up and online and I am running the pre-install steps now

**Comment by gh0stshell** [comment]
what the difference in running the command of the web site/github AS

sudo curl -L install.pi-hole.net | bash

vs

curl -L install.pi-hole.net | bash

??

**Comment by dschaper** [comment]
There used to be permissions problems that required the script to be called via `sudo`, but that's been patched. You can use either, but the preferred is `curl -L install.pi-hole.net | bash`

**Comment by gh0stshell** [comment]
Pi and Pi 2 now installing pi-hole via curl -L install.pi-hole.net | bash

**Comment by gh0stshell** [comment]
Both setup, to confirm I just add this address

https://hosts.neocities.org/

To the source in /usr/local/bin/gravity.sh

and then while in that dir run ./gravity.sh and all should be good?

**Comment by dschaper** [comment]
Yes, you can add the source to the `sources` array and then run `/usr/local/bin/gravity.sh`

**Comment by gh0stshell** [comment]
My LCD is just white on the Pi 2, I went through this article:

http://pi-hole.net/faq/install-the-real-time-lcd-monitor-chronometer/

I think I need to install the drivers for the LCD before the above will work.

**Comment by dschaper** [comment]
Yes, you need the drivers installed and working first.

**Comment by gh0stshell** [comment]
I figured, wishful thinking that it would just work, I had to do the same on another distro, I will install them now

**Comment by gh0stshell** [comment]
Having trouble with the auto login, I have no /etc/inittab file, do I just create it?

**Comment by gh0stshell** [comment]
I was able to get it figured out, using Jessie or Jessie lite the inittab file is no longer available.

Here is how to do it on these versions:

I made this file: /etc/systemd/system/getty@tty1.service.d/autologin.conf
And put this in it:
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin pi --noclear %I 38400 linux

After that, i ran this:
sudo systemctl enable getty@tty1.service

**Comment by dschaper** [comment]
Raspbian Jessie doesn't use the `/etc/inittab` you need to use systemD

**Comment by dschaper** [comment]
You can also just run `raspi-config` and select the `Console Autologin` option.

**Comment by gh0stshell** [comment]
I already ran my fix and it worked perfectly. I may try using the config tomorrow.

I am done for the night and will try adding my other source tomorrow and then try updating to see if it works now.

**Comment by gh0stshell** [comment]
Some research I found when people tried the auto-login using the raspi-config said it still asked for a login

**Comment by gh0stshell** [comment]
My LCD was working and now is black and I adjusted the setting to 0 for it not to turn off. Any ideas?

**Comment by dschaper** [comment]
You have to define 'login'. SSH and Serial will require a user/pass, HDMI will auto-login... I don't know about the LCD, I haven't received mine yet so I don't have one to test. @jacobsalmela knows that part way better than I.

**Comment by gh0stshell** [comment]
When I reboot the screen shows up as shown the picture in the article, but after a while the screen is just black. If I reboot it comes up for a while then goes black again.

**Comment by gh0stshell** [comment]
I think I got it figured out, testing fix now.

**Comment by gh0stshell** [comment]
Question on web console. When I installed it manually it would show how many domains are being blocked. When just installing the pi-hole by script and doing nothing else the admin console shows data but the domains blocked is not showing any data.

**Comment by gh0stshell** [comment]
![image](https://cloud.githubusercontent.com/assets/1724215/12408199/6837d786-be1b-11e5-9aef-7763e02cc79e.png)

**Comment by jacobsalmela** [comment]
We just fixed this.  If you were to re-install now, it would be fixed.  You can also run the `updateDashboard.sh` script, but you might also need the `chronometer.sh` script.

**Comment by gh0stshell** [comment]
How do I fix this or correct it so it shows how many domains are being blocked?

If I install the web panel using the article on Pi 2 #2 i see it shows domains being blocked, on PI and Pi 2 #1 just doing a clean flash, installing via script and going to the panel I see no number for domains being blocked. Now that I will be adding lists that would be very helpful.

**Comment by gh0stshell** [comment]
Sigh, reinstall it is......I will reinstall both and get the LCD working on the Pi 2 and redo everything.

**Comment by jacobsalmela** [comment]
If you re-install from scratch, it should work now.

**Comment by gh0stshell** [comment]
Off I go.

**Comment by jacobsalmela** [comment]
Eventually, we will get an update mechanism working...

**Comment by gh0stshell** [comment]
Any idea on the black LCD? I tried a fix and it did not work, the LCD stays up for a bit then goes black. Now that I am starting fresh I would like to get that fixed.

**Comment by jacobsalmela** [comment]
It doesn't have anything to do with the Pi-hole.  It's a setting for the LCD:

https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/using-the-console

Set `BLANK_TIME=0` in `/etc/kbd/config`

**Comment by gh0stshell** [comment]
Did that and also try disabling this as well

POWERDOWN_TIME=0

**Comment by gh0stshell** [comment]
Lemme get all setup again and work on it, just finished flashing the sd card and running raspi-config

**Comment by gh0stshell** [comment]
running curl -L install.pi-hole.net | bash now

**Comment by gh0stshell** [comment]
Gonna only setup the Pi 2 at this time to make sure everything works by default without the LCD, I was using the Pi as a test to see how adding 2 more lists affects performance, but you mentioned you revamped gravity.sh and adding more blocked domain should no longer be an issue, is this correct?

**Comment by gh0stshell** [comment]
Should I try raspi-config for autologin on raspbian jessie lite? I found this info which is why I used my fix above.

"I've used sudo raspi-config --> Boot Options --> Console Autologin but after rebooting I'm still asked to enter my username and password.

I can image it has something to do with the fact that inittab is not available anymore."

**Comment by gh0stshell** [comment]
I guess trying and it not working wont hurt anything and I can confirm this auto login method will not work on jessie lite

**Comment by gh0stshell** [comment]
If more info on the web console suppose to do anything?

**Comment by jacobsalmela** [comment]
Your questions are leaving the scope of the issue, so I am closing it.  

LCD instructions can be found [here](http://pi-hole.net/faq/install-the-real-time-lcd-monitor-chronometer/).

**Comment by gh0stshell** [comment]
OK will I am just setting up the pi and testing default config to add more lists so I feel that my issue is not resolved as I have not even got to add my list and try running gravity.sh which I just did and it still gives the same error

**Comment by gh0stshell** [comment]
My issue is not resolved and your LCD steps are missing quite a few steps which I am writing my own article to fix the missing pieces and will not mention the LCD again

**Comment by gh0stshell** [comment]
New flash, new install, get the same error after just adding the one new list to sources

./gravity.sh
./gravity.sh: line 59: syntax error near unexpected token ;' ./gravity.sh: line 59:if [[ -r $piholeDir/pihole.conf ]];then'
** Local calibration requested...
./gravity.sh: line 61: /pihole.conf: No such file or directory
./gravity.sh: line 62: syntax error near unexpected token fi' ./gravity.sh: line 62:fi'

**Comment by gh0stshell** [comment]
I confirm the domains blocked on the web console is fixed
