### ISSUE TITLE
adList.conf corrupted?

### ISSUE THREAD

**Issue by HunterNyan** [jacobsalmela/pi-hole#19]
It seems a bunch of lines in this file are corrupted, I think there should be a basic check to make sure that  only normally characters are allowed in.

**Comment by jacobsalmela** [comment]
Can you give me some examples?  It's possible your SD card could be failing.

**Comment by HunterNyan** [comment]
It does this on my atom server as well, ill see what I can get tomorrow, i found a command which has fixed it so far.

**Comment by jacobsalmela** [comment]
Any progress on some examples?  Also, what was the fix?

**Comment by jacobsalmela** [comment]
Closing for lack of communication
