### ISSUE TITLE
Sometimes very few hosts are pulled in when running gravity.sh

### ISSUE THREAD

**Issue by PromoFaux** [jacobsalmela/pi-hole#195]
Occaisionaly, when I rerun <code>gravity.sh</code> I only get ~2000 domains in <code>gravity.list</code>

The only way of getting it back up to a respectable number is to delete everything in <code>/etc/pihole/></code> and rerun <code>gravity.sh</code>

See below screenshot.

![image](https://cloud.githubusercontent.com/assets/1998970/12406120/288e5034-be42-11e5-964a-673343b03921.png)

**Comment by dschaper** [comment]
Looking at the screen shot, it looks like both `gravity.sh` runs pulled the full content of all the lists, did you clear out `/etc/pihole/` before both of the runs?

**Comment by PromoFaux** [comment]
No, just the second. I can take a look at trying to replicate it more effectively later on, just something I noticed before going to bed!

**Comment by jacobsalmela** [comment]
I have seen this happen, but rarely--probably only a few times in the past year.  I never really figured it out and it didn't happen often enough to debug.

**Comment by PromoFaux** [comment]
Lucky for some! It happens quite frequently for me. 

It's usually fine after clearing out <code>/etc/pihole/</code> or running <code>sudo service dnsmasq stop</code> before running <code>gravity.sh</code>. Or both.

**Comment by jacobsalmela** [comment]
I won't classify it as a bug just yet, but I'll leave it open in case others start seeing it more often.

**Comment by PromoFaux** [comment]
I'm wondering if it's worth having <code>gravity.sh</code> clear down the folder (with the exception of <code>whitelist.txt</code> and <code>blacklist.txt</code> once it's ran anyway.

<code>pihole.*</code> - as far as I can tell are no longer needed after <code>gravity.list</code> is generated (stats in <code>chronometer.sh</code> are pulled from <code>gravity.list</code> 

<code>gravity.list</code> - obviously this needs to stay in after the script has run, but could be deleted at the beginning of the script to make double sure there are no conflicts writing to it

<code>list.*</code> - Now, obviously we only update these on running <code>gravity.sh</code> if they are any different to save time, but we might as well just junk them at the the end of the script as in theory <code>gravity.sh</code> only needs to be run once a day on a schedule. The scripts have to be downloaded to compare them anyway, right? Might as well take out the compare step. 

 <code>whitlist.txt</code> and <code>blacklist.txt</code> - these need to be preserved.

**Comment by dschaper** [comment]
The way the update list logic works is to grab the header information from the sites and see the `last modified` date. It then compares that date to the individual file dates and if there is a match then the file is skipped. The whole host files aren't pulled on each update, only the header information. That's why the `curl` command is called with the `-z` flag.

**Comment by PromoFaux** [comment]
Ah right, OK. I might try running locally with the `pihole.*` files removed by the script, see what happens.

**Comment by dschaper** [comment]
Sound good. I think everything should run just fine, the `pihole.*` files were mainly for debugging purposes, to be able to see what happens to the files at each step in the process. But the Pi-Hole has definitely evolved since that scheme was useful. @jacobsalmela may have some input when he gets a moment or two, but I don't really see a need to keep them now, we have a pretty good idea how the script flows now. I'm really not for or against keeping them, it's up to you all...

**Comment by PromoFaux** [comment]
The root of the issue appears to be running the install script over an existing installation.

To replicate:
run install script over an existing installation. 

PR #205 attempts to fix this by blanking out the master lists before running the gravity.sh.

**Comment by dschaper** [comment]
I think this may be able to close out also. The fix seems pretty solid, both in execution and in concept.

**Comment by PromoFaux** [comment]
> The fix seems pretty solid, both in execution and in concept.

Sweet talker.

**Comment by dschaper** [comment]
Closing out, merged #205.
