### ISSUE TITLE
LCD Goes Black After A Few Minutes

### ISSUE THREAD

**Issue by gh0stshell** [jacobsalmela/pi-hole#197]
I followed your guide and the guides attached to your guide and after another fresh install and following everything the other issue I have is after about 5-10min my LCD goes black. If I reboot it shows the pi-hole console again and then after some time it goes black. I have another issue still with lists and will open a separate ticket for that issue.

**Comment by gh0stshell** [comment]
This was tried and still screen goes black after a short period of time.

BLANK_TIME=0

**Comment by dschaper** [comment]
Which OS are you running again? Are you on Raspbian Jessie? (Minimal or full?) We need to figure out the screen blanking...

**Comment by PromoFaux** [comment]
[This link](https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=122112) may provide some useful info.

I don't have an LCD, to my shame, to test, but the research seems solid.

**Comment by jacobsalmela** [comment]
Thank you for opening a new issue.

1. I was also curious if you are using Adafruit's distribution of Raspbian (they had special setting pre-configured for the LCD)?  
2. Are you using the Adafruit 2.8" screen or a different brand?
3. Do you have `pi` set to log in automatically?

I'll try it out on my LCD tonight on a fresh install.  I haven't used it for a while but I know I had it working, so I'll give it a shot.

**Comment by gh0stshell** [comment]
OS: Raspbian Jessie Lite

I downloaded it from the Raspian site. I followed the steps I have from adafruit to get the LCD working. I got the console login working from raspi-config and saw it was auto logging in and then added the script for the pi-hole to .bashrc. I will remove the script and see if it still happens with just the console screen.

**Comment by gh0stshell** [comment]
Another issue and I do not know if this needs to be separate from this ticket is the pi-hole script for showing the data shows my domains as 130K+ while the web gui shows 65K+

**Comment by jacobsalmela** [comment]
You should download Adafruit's image and try it on that:

https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/easy-install

**Comment by gh0stshell** [comment]
PromoFox, I have that article and tries both of those settings with no difference

**Comment by gh0stshell** [comment]
Sigh, another fresh install......so it shall be.....I have that article saved as it has the steps to get the LCD working in the DIY section. I will download that raspbian and try it after I remove the pi-hole script from .bashrc.

**Comment by gh0stshell** [comment]
That download is Jessie and not Jessie Lite from what the title shows.

**Comment by dschaper** [comment]
Then make sure your SDCard is 8MB or greater...

**Comment by gh0stshell** [comment]
Yup its a pre-setup step for me

**Comment by PromoFaux** [comment]
>Another issue and I do not know if this needs to be separate from this ticket is the pi-hole script for showing the data shows my domains as 130K+ while the web gui shows 65K+

Probably should be a separate issue - I'll open it up and have a look

**Comment by gh0stshell** [comment]
Opened a separate ticket.

**Comment by gh0stshell** [comment]
I will confirm in the new ticket when I get home and have the pi-hole in front of me.

**Comment by dschaper** [comment]
Thanks everybody!

**Comment by gh0stshell** [comment]
see you all in about 4 hours

**Comment by gh0stshell** [comment]
Removing Pi-Hole script now and then rebooting.

**Comment by gh0stshell** [comment]
Still does it without the script, console only. Downloading the adafruit with the LCD drivers now and reflashing.

**Comment by jacobsalmela** [comment]
Yeah, I can confirm the display goes dark after some time despite using Adafruit's distro and followed all their steps.

I really don't think it is a problem with Pi-hole, though.  As you can watch the script over `ssh` for unlimited time.

**Comment by gh0stshell** [comment]
well i just got done wiping and reflashing

**Comment by gh0stshell** [comment]
I have not installed pi-hole yet. I just finished my pre-install steps. I will see if it goes black with just the default flash

**Comment by dschaper** [comment]
Good idea! Let's go step by step and check at every step just to make sure where the problem pops up.

**Comment by gh0stshell** [comment]
One moment, need to check the LCD to see if it went black with a clean install, no mods yet

**Comment by dschaper** [comment]
@jacobsalmela Do you know if there is an issue open in the AdaFruit users forum for that behavior?

**Comment by gh0stshell** [comment]
I could not find this issue anywhere except here, but I may have found a fix, but the file I need to add code to did not exist on jessie lite, maybe its there on this version.

**Comment by dschaper** [comment]
Which file?

**Comment by gh0stshell** [comment]
One moment, I tried adding 3 separate code fixes, lets see if the LCD stays on now.

**Comment by gh0stshell** [comment]
FYI LCD still went black on a default flash of Adafruit Jessie. All I did was adjust timezone, change hostname, and expand the file system.

**Comment by gh0stshell** [comment]
Well holy ______ , the LCD is still fricken on! Now I will just add each fix one at a time until it stays on unless it takes all 3. I think I know which one it is.

**Comment by jacobsalmela** [comment]
Which files are they?

**Comment by gh0stshell** [comment]
Its def not fix one as I tried that last night multiple times. Its got to be 2 or 3 and I just found 3 today.

**Comment by gh0stshell** [comment]
@jacobsalmela, to be honest I added all 3 at once and I cannot tell you what worked. give me 30min please

**Comment by gh0stshell** [comment]
Nope, still went black

**Comment by dschaper** [comment]
Which model AdaFruit screen do you have?

**Comment by gh0stshell** [comment]
2.8

**Comment by gh0stshell** [comment]
I timed it and something is making it go dark at 10min. I think I may have an idea, trying it now

**Comment by gh0stshell** [comment]
well 3 ideas, trying one at a time, starting test 1 now

**Comment by dschaper** [comment]
Can you post a link to the AdaFruit page that lists it? I can check with them further if I know which exact model you are having trouble with. But in the meantime, keep trying!

**Comment by gh0stshell** [comment]
https://www.adafruit.com/products/1601

Test 1 = fail ( had little confidence that it would work, it was worth a try)

Confirmed at 10min the screen goes dark.

I was running another OS on this before I started with the pi-hole project and I think I did not have this issue with that OS. I may try that OS again if all else fails since my Pi 2 #2 has that OS running on it and I can just switch the cards.

**Comment by dschaper** [comment]
https://forums.adafruit.com/viewtopic.php?f=50&t=86760&p=436887&hilit=pitft+screen+blank#p436887

Is that one of the fixes you've tried?

**Comment by gh0stshell** [comment]
That is test 2 which is in progress and going strong at 4 min and counting

**Comment by gh0stshell** [comment]
I have one last fix I have found that is after this one, after each fix I reboot and start my timer

**Comment by gh0stshell** [comment]
I have successfully found a supposed fix that actually made the screen blank out faster

**Comment by gh0stshell** [comment]
Test 2 is 2 phase, one is adding to the cmdline.txt the other is adjusting the kernel itself

**Comment by gh0stshell** [comment]
Just so everyone know this is a default install of the adafruit distro with only the hostname, timezone and filesystem expand changed. I have not changed anything else so it is booting to the GUI

**Comment by gh0stshell** [comment]
once I get this fixed I will switch to console only and make sure it works as no matter whether it was GUI or console the screen acted the same

**Comment by gh0stshell** [comment]
adding console=0 to the cmdlist.txt did not work

trying test 2 phase 2

**Comment by jacobsalmela** [comment]
@dschaper's [fix worked for me](https://github.com/jacobsalmela/pi-hole/issues/197#issuecomment-173073322).  The display stays awake and does not go blank.

1. Adafruit distro
2. Ran `curl -L install.pi-hole.net | bash`
3. Enabled `pi` to auto login to console via `raspi-config`

I have updated [the FAQ](https://pi-hole.net/faq/install-the-real-time-lcd-monitor-chronometer/) with some better instructions and screenshots.

**Comment by gh0stshell** [comment]
I confirm it works

**Comment by gh0stshell** [comment]
I just had to change from GUI

**Comment by dschaper** [comment]
My Google-Fu is Strong!

**Comment by gh0stshell** [comment]
This also works for me

https://www.raspberrypi.org/forums/viewtopic.php?p=433728#p433728

**Comment by gh0stshell** [comment]
Should I go back to jessie lite as some will add an LCD later and not at first?

**Comment by dschaper** [comment]
If you feel up to it. I'd keep the existing SD Card as it is and try Jessie Lite on a new SD Card, so if it doesn't work you can just go back to this card.

**Comment by gh0stshell** [comment]
Good idea, just pulled a new card and flashing that one now, I do notice the touch does not work while using the adafruit steps to install on another OS the touch worked, but I am using  it for display only so I really dont mind, BUT it makes me curious why

**Comment by dschaper** [comment]
Well, keep us up to date on what you find, I'll be adding more info to the Wiki and having multiple solutions to issues always helps. So thanks for all your help so far in tracking down this one!

**Comment by gh0stshell** [comment]
Thanks, I really appreciate that and I hope to be of any assistance I can to this project. Anything I can do to test or help just let me know. I have 4 Pi's, 2 PI 2's, 1 B and 1 B+. Willing to test anything you need. If I can assist with the wiki in anyway just let me know. Oddly enough I enjoy writing articles to help others not have to search and dig to get things fixed or answers they are looking for.

**Comment by gh0stshell** [comment]
I wrote a script to install all the LCD "stuff" and add the line to the cmdlist.txt. I will see if it works. I will be running my pre-install steps first then running the script to install the LCD.

**Comment by gh0stshell** [comment]
Out of all fixes the article you found as I was testing is the simplest and easiest, lets stick with that

**Comment by dschaper** [comment]
Okay, if it works, lets go with it. And feel free to edit the Wiki, it's open to anyone that wants to contribute!
