### ISSUE TITLE
Facebook issues

### ISSUE THREAD

**Issue by PromoFaux** [jacobsalmela/pi-hole#206]
Just to preempt a whole heap of issues when everyone's gravity.sh runs and updates the lists...

[hosts-file.net have added `scontent-lhr3-1.xx.fbcdn.net`](http://hosts-file.net/default.asp?s=scontent-lhr3-1.xx.fbcdn.net), which basically renders Facebook unbrowsable (e.g profile pictures, and various photos are blocked)

If you use Facebook, I recommend adding any fbcdn domains to the whitelist using the following command:

`whitelist.sh creative.ak.fbcdn.net external-lhr0-1.xx.fbcdn.net external-lhr1-1.xx.fbcdn.net external-lhr10-1.xx.fbcdn.net external-lhr2-1.xx.fbcdn.net external-lhr3-1.xx.fbcdn.net external-lhr4-1.xx.fbcdn.net external-lhr5-1.xx.fbcdn.net external-lhr6-1.xx.fbcdn.net external-lhr7-1.xx.fbcdn.net external-lhr8-1.xx.fbcdn.net external-lhr9-1.xx.fbcdn.net fbcdn-creative-a.akamaihd.net scontent-lhr3-1.xx.fbcdn.net`

**Comment by dschaper** [comment]
I sent in a note that they were breaking a lot of things when they added the CDN for the European network. (I'm guessing you've seen the other issue we had open...) Not sure why they are going for the Nuclear Approach?

**Comment by PromoFaux** [comment]
Because Facebook is evil, obviously. /s

**Comment by dschaper** [comment]
Don't they have the copyright to everything anybody posts on there? ;)

**Comment by PromoFaux** [comment]
looks like `scontent-lhr3-1.xx.fbcdn.net` has now been [removed from hosts-files.net](http://hosts-file.net/default.asp?s=scontent-lhr3-1.xx.fbcdn.net)

**Comment by dschaper** [comment]
Okay, I'll close for now, but if there's a re-add we can re-open.
