### ISSUE TITLE
Whitelisting through textfile fails?

### ISSUE THREAD

**Issue by DonLexos** [jacobsalmela/pi-hole#209]
Hi,

Wanted to check my Google Analytics and the domain seems blacklisted, figured I need to whitelist it again. Checked howto again here:
https://pi-hole.net/faq/how-do-i-whitelist-or-blacklist-a-webiste-or-domain/
.... I added the domain (analytics.google.com) in 
/etc/pihole/whitelist.txt
... which is the only line there, and then ran sudo /usr/local/bin/gravity.sh
This is the output:

pi@pi-hole ~ $ sudo /usr/local/bin/gravity.sh
** Neutrino emissions detected...
  Getting adaway.org list: No changes detected, transport skipped...
  Getting adblock.gjtech.net list: No changes detected, transport skipped...
  Getting hosts-file.net list: List updated, transport successful...
  Getting www.malwaredomainlist.com list: List updated, transport successful...
  Getting pgl.yoyo.org list: List updated, transport successful...
  Getting someonewhocares.org list: List updated, transport successful...
  Getting winhelp2002.mvps.org list: No changes detected, transport skipped...
** Aggregating list of domains...
** Whitelisting 0 domains...
** Whitelisting 7 ad list sources...
** 77425 domains being pulled in by gravity...
** 68397 unique domains trapped in the event horizon.
** Formatting domains into a HOSTS file...
** Refresh lists in dnsmasq...

Seems the whitelist.txt is ignored. Right now user pi owns, it, but gravity.sh runs in root mode so I would expect it to be able find it. Am I doing something wrong

**Comment by DonLexos** [comment]
And I just CHOWNed the file to root, ran grafity.sh again, that did not fix it.

Must admit I did a fresh install a few days ago and then learned (through many email notifications) there were quite a few changes again already. Should I try to upgrade first?

**Comment by DonLexos** [comment]
And to complete my search, I tried this:
pi@pi-hole /usr/local/bin $ sudo whitelist.sh analytics.google.com
Whitelisting analytics.google.com...
Modifying hosts file...
** 1 domain(s) whitelisted.

That did not fix it, nor did a "sudo service dnsmasq restart" to see if that was the issue.

Puzzled now.

**Comment by DonLexos** [comment]
Cancel that last statement, apparently my cache failed first, I can login now, seems that whitelisting did work (not sure what step did make it happen though). Off to check analytics now ;-)

**Comment by DonLexos** [comment]
Thinking steps to reproduce this, even though the whitelist.sh script is probably easiest (also for the FAQ) maybe gravity.sh does not restart dnsmasq when it's done?

**Comment by PromoFaux** [comment]
Hey! When was the last time you ran the install script? I made some significant changes to the whitelisting in `gravity.sh`.

`whitelist.sh` was also updated/improved, and `blacklist.sh` was added too.

Judging by your output in the initial comment, it looks like you're running out of date files! :)

run `curl -L install.pi-hole.net | bash` to get everything up to date.

**Comment by DonLexos** [comment]
I think the last time was a whopping 3-4 days ago :-)

I am reinstalling the pi with Jessy Lite now and get the 'latest' in a few minutes (stuck with a GB keyboard that does not have the | sympol since I have a US keyboard, figuring that out and then get the very latest latest).

Thanks for the follow up.

**Comment by PromoFaux** [comment]
Just copy and paste the command into the terminal window! A right click should paste whatever is in your clip board...

**Comment by DonLexos** [comment]
Yeah well this need fixing for other things aswell, eventually I plan to upgrade by just running the script again instead of completely installing the pi from scratch. Thanks for the tip though, thats a very clever fallback :-)

**Comment by PromoFaux** [comment]
> eventually I plan to upgrade by just running the script again instead of completely installing the pi from scratch.

Are you talking about updating pi-hole, or raspbian? You can get away with running the install script over the top of an existing install, no need to reflash your SD card. :)

**Comment by DonLexos** [comment]
Yes I know, but switched from Wheezy to Jessy at the same time :-)

**Comment by dschaper** [comment]
If you still have problems after the re-flash let us know, or if the re-flash and re-install fixes things let us know also. I'll keep this open until I hear back from you.

**Comment by DonLexos** [comment]
I whitelisted the domain again and that worked fine (even though I managed to get it working on the 3-day old installation on Wheezy aswell (not sure how)). Anyway, everybody that does an installation now should not get any troubles, feel free to close this (and thanks for the follow up!).

**Comment by dschaper** [comment]
Thanks!

**Comment by PromoFaux** [comment]
It was the whitelisting not working that motivated me to contribute to the project!
