### ISSUE TITLE
Best Raspbian for pi-hole?

### ISSUE THREAD

**Issue by DonLexos** [jacobsalmela/pi-hole#210]
I use the pi-hole as only service on a pi and wondered, in the latest ipv6 docs here
https://pi-hole.net/block-more-ads-ipv6-support-with-pi-hole/

It is referenced that Raspbian Jessie Lite is out. What would be the best Rapsbian to run pi-hole on? Right now I installed Wheezy (which seems a bit older but also runs). 

I checked the docs (o:-)) but could not find anything about a recommended version. Is there one?

**Comment by jacobsalmela** [comment]
I'm a bit slow on the documentation end of things.  My personal preference is Jessie Lite and is what I recommend for most users.  It's lightweight, quick-to-install, and a good match for Pi-hole.

**Comment by DonLexos** [comment]
Excellent cheers!!

Btw that documentation was with a big ;-) I know you are SUPER busy with the project!
