### ISSUE TITLE
File Ownership issues

### ISSUE THREAD

**Issue by PromoFaux** [jacobsalmela/pi-hole#211]
It came to our attention earlier that the files in `/etc/pihole/` are owned by root, which is not ideal as the whitelist/blacklist/chronometer scripts do no have access to them. I beleive it has to do with the install script running `gravity.sh` as sudo.

I'll submit a pull request to address this

**Comment by PromoFaux** [comment]
This can be closed if and when #212 is merged.

**Comment by dschaper** [comment]
Merged #212 to development.

**Comment by gh0stshell** [comment]
Do I have to reinstall again?

**Comment by dschaper** [comment]
Not yet, it's still in the development branch, it hasn't been moved to the general release master branch. And even then you should be able to just update the existing and not reinstall from scratch.

**Comment by gh0stshell** [comment]
Lemme know when it is completed so I can update.

**Comment by dschaper** [comment]
Will do, keep an eye here and I'll keep this updated with the progress.

**Comment by gh0stshell** [comment]
This explains my LCD numbers

**Comment by dschaper** [comment]
If you wan't I can walk you through installing the development branch on one of your Pi's to test it out. We'd just clone the repository, change to the development branch and then run the `basic-install.sh` script.

**Comment by gh0stshell** [comment]
sure, Ill be a tester

**Comment by gh0stshell** [comment]
I wondered why my LCD numbers were way off, I was going to report it until I saw this ticket and though it maybe related.

**Comment by dschaper** [comment]
Okay, first you'll need to be in your home directory: `cd ~`. 
Next:
```
git clone https://github.com/jacobsalmela/pi-hole.git
```
`cd pi-hole`
`git checkout development`
`cd automated install`
`./basic-install.sh`

**Comment by gh0stshell** [comment]
uno momento, need to get a fresh pi ( pun intended )

**Comment by gh0stshell** [comment]
Quick off-topic question, is jessie lite a common install? What do you recommend to users for their raspbian install?

**Comment by dschaper** [comment]
If you are running a headless server, then Jessie Lite is great. If you need the desktop then go for the full Jessie. I pretty much just run the Lite version, I ssh in. If I need Wolfram Mathematica then I have a uSD that has the full install and x11vnc for a remote desktop.

**Comment by dschaper** [comment]
You should be able to do this install over an existing install, no need to reflash a new uSD image...

**Comment by jacobsalmela** [comment]
Yeah, I usually image it with Jessie Lite as I also do it headless and everything over ssh (easier copy/pasting from my Mac)

**Comment by gh0stshell** [comment]
OK, I was just trying to decide when I make a new pi-hole if I should stay with jessie lite, all my pi's are headless, but 2 have LCD's and it only takes me about 15min to install the LCD drivers and get it running.

**Comment by gh0stshell** [comment]
The only reason I was debating was that it is so quick to flash jessie lite

**Comment by dschaper** [comment]
That's a big bonus too... Especially if you're not using a fast uSD.

**Comment by gh0stshell** [comment]
Where should I add new info about the LCD/screen timeout/console?

**Comment by dschaper** [comment]
You mean like a Wiki entry? Just start up a Wiki page and add the information.

**Comment by gh0stshell** [comment]
Just a few things I learned about the console and jessie lite, does not apply to jessie or the adafruit jessie, how to get the touch screen working and not needing the timeout since I can tap the screen to make it come up again to see the stats instead of it always being on which may save the life of the LCD not having to be on 24/7. Just a couple things. I tend to tinker.

**Comment by dschaper** [comment]
Then the Wiki is the place! It's always open to tinkering...

**Comment by gh0stshell** [comment]
before I post about the console autologin and jessie lite I just tested my theory 3 times, thanks I will post, following your steps now to try the dev branch, will post when complete

**Comment by gh0stshell** [comment]
pi@pi-2:~ $ git clone https://github.com/jacobsalmela/pi-hole.git
Cloning into 'pi-hole'...
remote: Counting objects: 1427, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 1427 (delta 9), reused 0 (delta 0), pack-reused 1401
Receiving objects: 100% (1427/1427), 552.25 KiB | 814.00 KiB/s, done.
Resolving deltas: 100% (774/774), done.
Checking connectivity... done.
pi@pi-2:~ $ cd pi-hole/
pi@pi-2:~/pi-hole $ git checkout development
Branch development set up to track remote branch development from origin.
Switched to a new branch 'development'
pi@pi-2:~/pi-hole $ cd automated install
-bash: cd: automated: No such file or directory
pi@pi-2:~/pi-hole $

**Comment by dschaper** [comment]
`cd automated\ install`

**Comment by gh0stshell** [comment]
I should have not be lazy and copied and pasted, I should no better in terminal

**Comment by dschaper** [comment]
Heh, it's the space in the directory name that throws linux off.

**Comment by gh0stshell** [comment]
I LOVE the new install script!

::: Updating apt-get package list
 [/] ( this is animated on my terminal )

**Comment by dschaper** [comment]
Are things going well?

**Comment by gh0stshell** [comment]
so far so good, just finished, adding LCD chrono code now

**Comment by gh0stshell** [comment]
I will post after letting it run for a while

**Comment by dschaper** [comment]
Okay, are the numbers matching up so far?

**Comment by gh0stshell** [comment]
yup, everything is looking good, anything you would like me to test besides comparing LCD and web interface numbers?

**Comment by gh0stshell** [comment]
LCD is showing well and correctly

**Comment by dschaper** [comment]
Is there anything else that was problematic that you can think of? This might be ready for merging if all is well.

**Comment by dschaper** [comment]
Closing this issue, follow up in #212

**Comment by gh0stshell** [comment]
Should I open a new ticket for the chrono script? My stats as I just checked when I got home are:

Query: 1
Ads Blocked: 18 (1800%)

After browsing for 15min to sites I know have ads and ones with tons of ads it shows

Query: 1
Ads Blocked: 42 (4200%)

There is still something going on with permissions or the chrono script. It was fine yesterday, this happened once the script reset.
