### ISSUE TITLE
Small addition to gravity.sh

### ISSUE THREAD

**Issue by JaredWith1r** [jacobsalmela/pi-hole#228]
So I don't claim to know (literally) anything about writing scripts, or Linux at all, but I've been adding a line to Gravity.sh to log whenever it gets restarted. In the gravity_reload section, I believe.

echo "Resetting force of gravity at $(date)" >> /var/log/piholereload.log
(no idea how to add code, either)

I guess let me know if this is already being done somewhere else. Thanks for all of the great work!

**Comment by dschaper** [comment]
It's not currently being worked on, but it's a good idea. Thanks for the submission!

**Comment by JaredWith1r** [comment]
Awesome, thanks! I for one am pretty interested in logging things, since I have no idea what to look for. 

Keep up the good work.

**Comment by dschaper** [comment]
is your idea that a single line like `Pihole v?.? restarted` is added to the log, or would you like to see other information logged on start/restart?

**Comment by JaredWith1r** [comment]
Well the only thing I am currently doing is the single line restart appending to a log. I know that there is currently a lot of work being done for logging blocking stats, which is going to be excellent. But I don't have any other specific ideas. Possibly adding a gravity.sh specific version to the restart log, but it does probably get updated quite often.

**Comment by dschaper** [comment]
We have a lot of great features in the works, thanks for using the Pi-Hole!
