### ISSUE TITLE
Blacklist count may not be correct in some cases

### ISSUE THREAD

**Issue by mospaeda** [jacobsalmela/pi-hole#25]
If there is blank line in blacklist.txt, these lines are counted as blacklisted domains which is wrong.
In my case, I have 35 lines among then 4 empty lines but reported as 

** Neutrino emissions detected...
Skipping adaway.org list because it does not have any new entries...
Skipping adblock.gjtech.net list because it does not have any new entries...
Skipping adblock.mahakala.is list because it does not have any new entries...
Skipping hosts-file.net list because it does not have any new entries...
Skipping www.malwaredomainlist.com list because it does not have any new entries...
Skipping pgl.yoyo.org list because it does not have any new entries...
Skipping someonewhocares.org list because it does not have any new entries...
Skipping winhelp2002.mvps.org list because it does not have any new entries...
** Aggregating list of domains...
** Blacklisting 35 domain(s)...
** 398451 domains being pulled in by gravity...
** 377619 unique domains trapped in the event horizon.
** Formatting domains into a HOSTS file...

**Comment by jacobsalmela** [comment]
I think this can be solved with something like this:

`numberOf=$(cat $blacklist | sed '/^\s*$/d' | wc -l)`

I'll test it some more

**Comment by jacobsalmela** [comment]
I tested a lot on the Mac and was using this `sed 's/^[ \t]*//'` to eliminate the tab in front of the number when using `wc`.  It doesn't seem that the Raspbian version of `wc` has that, so the solution above should work for all the `numberOf` variables, while accounting for blank lines if they happen to exist.
