### ISSUE TITLE
optimalization

### ISSUE THREAD

**Issue by ttr** [jacobsalmela/pi-hole#3]
Hey, not a big problem but you can skip `sort' calls in every curl - you're sorting anyway later when you're looking for duplicates.

Also, not sure what you're trying to do here:
grep -v "#" | sed '/^$/d' | sed 's/\ /\\ /g' | grep -v '^\\' | grep -v '\\$' | awk '{print $2}' | grep -v '^\\' | grep -v '\\$'

but this is quite overkill - how about:
awk '{if ($1 !~ "#" && $1 !~ "/" && $2 !~ "#" && $2 !~ "/" && $0 != "^$" && $2 != "")  { print $2}}'

If i'm seeing right, those files are similar to /etc/hosts (ip hostname, and comments (# and / based ?)) and you're only interested in 2nd column if line is valid - if so this should do it (might need few more conditions)

In fact you could 'dump' all those files to one file and process it in end - will be much faster.

Then, /tmp/matter.txt and /tmp/andLight.txt could be moved to /dev/shm (ramfs) so you do not operate on SD card (unless /tmp is already ram based - did not checked for a while how it is in Pi now)

**Comment by ttr** [comment]
oops (forgot) - all those are in gravity-adv.sh file

**Comment by jacobsalmela** [comment]
I have only used awk for basic parsing, printing single columns, etc.  Could you explain how your awk command works?

**Comment by jacobsalmela** [comment]
So I ran it using /run/shm instead of /tmp and it was about 2-3 seconds faster overall on my Pi. Using /dev/shm yielded similar results. 

I would still like to understand your awk command in detail

**Comment by ttr** [comment]
Running in shm also reduce usage of SD card.

Now awk... well (g)awk is more complex tool then printing certain fields from lines (feel free to look up any tutorial).
In my example it does condition check (if (...) ) and 
- check if first and second field is not starting with certain  characters (# or / which can be comments)
- if line is not empty ($0 match whole line)
- if 2nd field not empty
there is logical and for each of those conditions, as when they all are true, it will print second field.
This should reduce need to use all those grep (and not sure why you need those sed in there?). I did not check how this will behave in case of white-space in beginning of line but that should not be a problem.
Reason to do so is to limit amount of sub-calls (and pipes) as each of it will take some time and CPU cycles to execute.

Also - side note (and quite separate thing): if you do checksum comparison of old and new file (i.e. md5sum of $eventHorizion and then same for /tmp/andLight.txt before mv) and trigger dnsmasq restart when files (checksums) are different, you can put this as cronjob (i.e. every day) so lists will be always up to date but dnsmasq will be restarted only when there was update.

**Comment by jacobsalmela** [comment]
Thanks for explaining it.  It makes more sense now.  I always knew awk was much more, but have never really utilized it.  I love open source for this reason as I learned something and your skill will be able to make the code better and try things I never even thought about.  

I will mess around with implementing this and see what I can come up with.

**Comment by jacobsalmela** [comment]
You are definitely right that it does not need the ```sort``` on each line.  I did some testing with it using the ```time``` command and it seems a little faster only using it on the last line.  In my brain, I was thinking it would be easier for the computer to sort a few sorted lists, but I guess the computer doesn't care (it's smarter than me)!

There is also a slight improvement in using RAM as opposed to the SD card, so that will make it in, too.

I'm still looking into your other suggestions.

**Comment by jacobsalmela** [comment]
Using my Mac as a test machine, the average time I can run the existing gravity-adv.sh script is 20-30 seconds.  I will use that as the baseline for determining speed improvements.

**Comment by jacobsalmela** [comment]
I have made some significant improvements based on your suggestions.  After some more testing to ensure it works, I will commit them.

**Comment by ttr** [comment]
Cool.
(was on longer holidays so did not reply before)

**Comment by jacobsalmela** [comment]
I am on vacation at the moment and will have to look at this in a couple of weeks.

**Comment by jacobsalmela** [comment]
I implemented your suggestions in another branch, that will be merged with the master soon.

**Comment by jacobsalmela** [comment]
Your suggestions were implemented in the release this evening.
