### ISSUE TITLE
no ping response when testing

### ISSUE THREAD

**Issue by Symbiot78** [jacobsalmela/pi-hole#30]
hi

I installed your adblocking script on a unix based machine.
I previously installed using your old guide and it worked perfectly.
Now I am trying to use the newer guide and am falling short.
I've followed the guide but when testing (ping 247media.com) and dig a-ads.com I am failing.
the ping command doesn't return anything and the dig command just returns the actual site and is not redirected to the "pihole". 

ping : PING 247media.com (54.221.208.242) 56(84) bytes of data.
and it hangs until I cancel...

dnsmasq is running but returning
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /etc/resolvconf/run/resolv.conf
when I restart the service

dnsmasq.conf is:

domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300

I tried creating the resolv.conf file but that didn't change anything..

Any help is much appreciated!

**Comment by Symbiot78** [comment]
Just tried a complete reinstall of OS and adblocking scripts but still same issue.

**Comment by Symbiot78** [comment]
ok, tried some more ping -

root@adblocker:~# ping google.com
PING google.com (77.68.251.234) 56(84) bytes of data.
64 bytes from 77.68.251.234: icmp_req=1 ttl=59 time=2.10 ms
64 bytes from 77.68.251.234: icmp_req=2 ttl=59 time=2.60 ms
^C64 bytes from 77.68.251.234: icmp_req=3 ttl=59 time=2.77 ms

--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 10066ms
rtt min/avg/max/mdev = 2.102/2.492/2.775/0.288 ms
root@adblocker:~# ping 247media.com
PING 247media.com (54.221.208.242) 56(84) bytes of data.


247media.com doesn't respond but google did...

**Comment by Symbiot78** [comment]
tried pinging a-ads.com

PING a-ads.com (162.159.251.9) 56(84) bytes of data.
64 bytes from 162.159.251.9: icmp_req=1 ttl=53 time=21.1 ms
64 bytes from 162.159.251.9: icmp_req=2 ttl=53 time=20.7 ms
64 bytes from 162.159.251.9: icmp_req=3 ttl=53 time=20.6 ms
64 bytes from 162.159.251.9: icmp_req=4 ttl=53 time=20.8 ms
64 bytes from 162.159.251.9: icmp_req=5 ttl=53 time=20.8 ms
64 bytes from 162.159.251.9: icmp_req=6 ttl=53 time=20.4 ms
64 bytes from 162.159.251.9: icmp_req=7 ttl=53 time=20.8 ms
64 bytes from 162.159.251.9: icmp_req=8 ttl=53 time=20.6 ms
64 bytes from 162.159.251.9: icmp_req=9 ttl=53 time=20.8 ms
64 bytes from 162.159.251.9: icmp_req=10 ttl=53 time=20.9 ms
64 bytes from 162.159.251.9: icmp_req=11 ttl=53 time=20.6 ms
^C64 bytes from 162.159.251.9: icmp_req=12 ttl=53 time=20.8 ms

**Comment by jacobsalmela** [comment]
It sounds like you haven't changed your DNS server to point to the Pi.  You are still getting out to the Internet but it is returning the real Website.  

Also, if you are running the commands on your Pi, it won't work because the DNS server for the Pi, is not itself.  

I do not think that this is an issue with the actual software, but I can help troubleshoot.  Did you manually set up the Pi-hole or did you use the the automated install?

**Comment by Symbiot78** [comment]
Hi Jacob.

just tried on my windows machine (I have DNS set in router to the adblocker.)
when pinging 247media.com I still just get a timeout...
google answers just fine.. 

testing via http://simple-adblock.com/faq/testing-your-adblocker/ also shows that adblocking is not working..
tried manually entering pi IP address in wifi settings on laptop and this had no effect. 

I assume you want to have a look at some files.. let me know which :)

as noted above I had the old adblock running fine. I really just wanted to update my adblocker and start adding some whitelist sites.

this: http://www.bhg.com/gardening/flowers/perennials/power-perennials/?sssdmh=dm17.813823&esrc=nwgn080615c

for instanse has slideshow and other images blocked when using adblocker. so I was looking to add it to the whitelist but couldn't get it to work so thought I'd try the new guide.

I've installed a fresh OS on a VM and did the whole guide to the letter.. I thought :-)

**Comment by jacobsalmela** [comment]
Did you manually set this up or did you use the automated installer?

Send me the output of the following commands (run on your Pi):
`ifconfig`
`cat /etc/dnsmasq.conf`
`cat /etc/lighttpd/lighttpd.conf`
`ls -l /etc/pihole`
`head /etc/pihole/gravity.list`
`head /etc/hosts/`
Also send me a screenshot of your Windows IP settings

**Comment by Symbiot78** [comment]
ifconfig - 
root@adblocker:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:87:ae:14
          inet addr:192.168.1.176  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:51210 errors:0 dropped:0 overruns:0 frame:0
          TX packets:19072 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5676443 (5.4 MiB)  TX bytes:2279373 (2.1 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:15412 errors:0 dropped:0 overruns:0 frame:0
          TX packets:15412 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:5206997 (4.9 MiB)  TX bytes:5206997 (4.9 MiB)

==================================================
cat /etc/dnsmasq.conf  -

domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300

==================================================
cat /etc/lighttpd/lighttpd.conf

cat /etc/lighttpd/lighttpd.conf
server.modules = (
        "mod_expire",
        "mod_compress",
        "mod_redirect",
        "mod_rewrite"
)

server.document-root        = "/var/www"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80


index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

# Set access to 1 day for better query performance when the list gets so large
# http://jacobsalmela.com/raspberry-pi-block-ads-adtrap/#comment-2013820434
$HTTP["url"] =~ "^/pihole/" {
        expire.url = ("" => "access plus 1 days")
}

# Rewrites all URLs to the /var/www/pihole/index.html
$HTTP["host"] =~ ".*" {
     url.rewrite = (".*" => "pihole/index.html")
}
==================================================
ls -l /etc/pihole

 ls -l /etc/pihole
total 195768
-rw-r--r-- 1 root root 41071465 Aug  7 08:47 gravity.list
-rw-r--r-- 1 root root     7646 Aug  7 08:46 list.0.adaway.org.domains
-rw-r--r-- 1 root root    16190 Aug  7 08:46 list.1.adblock.gjtech.net.domains
-rw-r--r-- 1 root root 22761000 Aug  7 08:47 list.2.adblock.mahakala.is.domains
-rw-r--r-- 1 root root   388086 Aug  7 08:47 list.3.hosts-file.net.domains
-rw-r--r-- 1 root root    29632 Aug  7 08:47 list.4.www.malwaredomainlist.com.domains
-rw-r--r-- 1 root root    39379 Aug  7 08:47 list.5.pgl.yoyo.org.domains
-rw-r--r-- 1 root root   223562 Aug  7 08:47 list.6.someonewhocares.org.domains
-rw-r--r-- 1 root root   289835 Aug  7 08:47 list.7.winhelp2002.mvps.org.domains
-rw-r--r-- 1 root root 23731072 Aug  7 08:47 pihole.0.matter.txt
-rw-r--r-- 1 root root 23731072 Aug  7 08:47 pihole.1.andLight.txt
-rw-r--r-- 1 root root 23731067 Aug  7 08:47 pihole.2.supernova.txt
-rw-r--r-- 1 root root 23352351 Aug  7 08:47 pihole.3.eventHorizon.txt
-rw-r--r-- 1 root root 41071465 Aug  7 08:47 pihole.4.accretionDisc.txt

==================================================

head /etc/pihole/gravity.list

head /etc/pihole/gravity.list
192.168.1.176 0.0000000000000000000000.com
192.168.1.176 00000000000000000001.free.fr
192.168.1.176 0000000000000000000sex.com
192.168.1.176 0000000000000001sexe.free.fr
192.168.1.176 000000000000000.info
192.168.1.176 000000000000000sexe.free.fr
192.168.1.176 0-0-0-0-0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-0-0-0.info
192.168.1.176 0-0-0-0-0-0-0-0-0-0-0-0-0-12-0-0-0-0-0-0-0-0-0-0-0-0-0.info
192.168.1.176 0-0-0-0-0-0-0-0-0-0-0-0-0-13-0-0-0-0-0-0-0-0-0-0-0-0-0.info
192.168.1.176 0-0-0-0-0-0-0-0-0-0-0-0-0-14-0-0-0-0-0-0-0-0-0-0-0-0-0.info

==================================================

head /etc/hosts

 head /etc/hosts
127.0.0.1       localhost
127.0.1.1       adblocker.local adblocker

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

============================


![wifi](https://cloud.githubusercontent.com/assets/3314249/9142261/d4c81784-3d3e-11e5-9991-c4db6674a0e6.png)

![router](https://cloud.githubusercontent.com/assets/3314249/9142264/d9aa60cc-3d3e-11e5-9bf1-1d7246f297b8.png)

**Comment by Symbiot78** [comment]
i did the setup manually.

**Comment by Symbiot78** [comment]
as mentioned when I restart dnsmasq I get the following warning:

root@adblocker:~# service dnsmasq restart
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /etc/resolvconf/run/resolv.conf
Restarting DNS forwarder and DHCP server: dnsmasq.
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /etc/resolvconf/run/resolv.conf

**Comment by jacobsalmela** [comment]
Everything looks right.  Try these commands to delete the file and make a new symlink.
```
sudo rm /etc/resolv.conf
sudo ln -s ../run/resolvconf/resolv.conf /etc/resolv.conf
```
What flavor of *nix are you running?

**Comment by Symbiot78** [comment]
I did the above:
rm /etc/resolv.conf
ln -s /etc/resolvconf/run/resolv.conf /etc/resolv.conf

restarted dnsmasq
no warnings.. but still ping times out hitting 247media.com

unix version: Linux adblocker 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u2 x86_64

it's a NAS distro named OpenMediaVault.. I had the iso and it doesn't really use that much processing power etc. so I figured it'd be a good distro to use.

it's the same as the one I used for the old version of the ad blocker.

it appears to NOT be redirecting anything.. to anywhere :-(

**Comment by Symbiot78** [comment]
just removed the static dns server from Windows wifi settings and ran ipconfig /all

DNS Servers . . . . . . . . . . . : 192.168.1.176
                                       8.8.8.8
                                       192.168.1.1

so it's picking up the adblock IP set in the router.

**Comment by jacobsalmela** [comment]
Can you try installing via the automated install.  That will determine if it is your OS or something in the Pi-hole.

**Comment by Symbiot78** [comment]
I tried that first but I had a lot of errors..

will try again though..

**Comment by Symbiot78** [comment]
ok, did the automated install (basic install.sh)

after installing curl and running the script everything went through with success.

now I cannot ping anything :-(

google times out and everything else the same..

**Comment by Symbiot78** [comment]
but.. when I ping a-ads.com from my laptop I get ping result from 192.168.1.176..
so the filtering seems to work but the adblocker machine seems to be cut off from normal inet?
I cannot apt-get install anything either..

**Comment by jacobsalmela** [comment]
What does `traceroute` tell you?

**Comment by Symbiot78** [comment]
root@adblocker:~# ping www.google.dk
ping: unknown host www.google.dk
root@adblocker:~# ping google.dk
ping: unknown host google.dk
root@adblocker:~#

===

traceroute google.dk
google.dk: Name or service not known
Cannot handle "host" cmdline arg `google.dk' on position 1 (argc 1)


===

root@adblocker:~# traceroute www.google.dk
www.google.dk: Name or service not known
Cannot handle "host" cmdline arg `www.google.dk' on position 1 (argc 1)
root@adblocker:~#

**Comment by Symbiot78** [comment]
root@adblocker:~# traceroute 8.8.8.8
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
 1  0.0000000000000000000000.com (192.168.1.176)  2999.905 ms !H  2999.908 ms !H  2999.905 ms !H

**Comment by Symbiot78** [comment]
google.dk ip 77.68.251.241
===========================================
root@adblocker:~# ping 77.68.251.241
PING 77.68.251.241 (77.68.251.241) 56(84) bytes of data.
From 192.168.1.176 icmp_seq=1 Destination Host Unreachable
From 192.168.1.176 icmp_seq=2 Destination Host Unreachable
From 192.168.1.176 icmp_seq=3 Destination Host Unreachable
From 192.168.1.176 icmp_seq=4 Destination Host Unreachable
From 192.168.1.176 icmp_seq=5 Destination Host Unreachable
From 192.168.1.176 icmp_seq=6 Destination Host Unreachable
From 192.168.1.176 icmp_seq=10 Destination Host Unreachable
From 192.168.1.176 icmp_seq=11 Destination Host Unreachable
From 192.168.1.176 icmp_seq=12 Destination Host Unreachable


=============================
root@adblocker:~# traceroute 77.68.251.241
traceroute to 77.68.251.241 (77.68.251.241), 30 hops max, 60 byte packets
 1  0.0000000000000000000000.com (192.168.1.176)  2997.509 ms !H  2997.505 ms !H  2997.499 ms !H

**Comment by Symbiot78** [comment]
hi Jacob..
It seems that the adblocking is working as it should but my host seems unable to ping anything.. could this be because of some dns loopback thing? 
but if so.. I can't help wonder how it can download the blocked sites lists.. :-|

**Comment by jacobsalmela** [comment]
Try setting your router back to default and then manually set the DNS on your client.  That will remove the router as a variable.

**Comment by jacobsalmela** [comment]
I don't think this is an issue with the software, rather your specific OS.  Right now, it is only supported on Raspbian.  All the settings look fine, so you may have to do some more troubleshooting.
