### ISSUE TITLE
Add data validation to prevent rogue entries

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#32]
Sometimes entries from the third-party lists have errors, [such as adlog..com](http://jacobsalmela.com/raspberry-pi-block-ads-adtrap/#comment-2180476491) (two periods instead of one).

This will probably require some <code>sed</code> and <code>awk</code> skills to check for the proper formatting of:

**subdomain(s) (if applicable), a period (.), the domain, another period (.), and finally, the top level domain.**

**Comment by korhadris** [comment]
Here's a see command to remove duplicated '.' characters:

`sed 's/\.\+/./g/'`

**Comment by kurumushi** [comment]
The real challenge is to see if these can be combined into one, I'm not very good at simplification.
Here's a few more useful ones:
`sed -e 's/ \.//g'`: remove periods at the start and the middle of domains.
`sed -e 's/\[. ]+$/$/g'` remove domains ending in a period, and trailing white space.

**Comment by korhadris** [comment]
Yeah, simplifying regexp statements to be optimized is rough. As long as I really don't require the speed I usually combine statements like this:

**Comment by jacobsalmela** [comment]
It looks pretty good, but it's a bit out of my skill level.  Maybe someone could make a pull request and I can test it out.
