### ISSUE TITLE
Pi 1 512 RAM needed swap

### ISSUE THREAD

**Issue by chesterdkat** [jacobsalmela/pi-hole#36]
I was getting the following errors when updating the database:

pi@pihole ~ $ sudo /usr/local/bin/gravity.sh
** Neutrino emissions detected...
Skipping adaway.org list because it does not have any new entries...
Skipping adblock.gjtech.net list because it does not have any new entries...
Getting adblock.mahakala.is list...
/usr/local/bin/gravity.sh: fork: Cannot allocate memory

I added 512 MB's of Swap and that seemed to fix this issue.

**Comment by jacobsalmela** [comment]
Cool.  I have had a few other people with this error and the solution has been to reduce the amount of memory allocated to the GUI.  I will add this to a list of fixes and maybe find some way to implement it into the script so it doesn't happen.

**Comment by jacobsalmela** [comment]
How did you increase the swap size?  I was reading that the `CONF_SWAPSIZE` option `/etc/dphys-swapfile` would be the one to set.  I am trying to figure out a way to prevent this error from happening as the aggregated list has now grown to 1.6million entries.

**Comment by chesterdkat** [comment]
Hi Jacob,

I used this post to create a swap file:

http://jermsmit.com/my-raspberry-pi-needs-a-swap/ <http://jermsmit.com/my-raspberry-pi-needs-a-swap/>

It works perfectly so now when I update the 1.6 million sites all goes smoothly. In the future I’d make a swap partition when setting up a new SD card.

Do you have any idea how I can create a persistent whitelist file? There are some sites that make no sense like one I use for my business “zooprinting.com <http://zooprinting.com/>” and I’d love to be able to place them in a whitelist that persists after an update.

Thanks for a great addition to my network.

Beat…
Dave

**Comment by jacobsalmela** [comment]
Thanks for that link.  I will check it out.

If you create `/etc/pihole/whitelist.txt` with one domain per line, `gravity.sh` will automatically and persistently remove it from the list.
