### ISSUE TITLE
Error fork: Cannot allocate memory

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#37]
Many users are having trouble downloading the mahakala list and running out of memory.  Giving the GPU 16MB seems to work for a lot of people, but as the list grows larger, I'm looking for a long-term solution.

**Comment by enjunear** [comment]
I've commented out the mahakala for now. Works fine without it, but obviously you don't get to block all those 1.6 million domains. That's well over 900,000!!!

**Comment by jacobsalmela** [comment]
Yeah this annoying error has been coming up a lot more recently.  I'm looking into increasing the swap size somehow via `gravity.sh`

**Comment by jpearsall** [comment]
I was able to get around this by bypassing the assignment to the data variable and piping the curl to awk (shamelessly pulled from the if/then conditional on data further down) and directing it then redirecting it to the destination file.

**Comment by jacobsalmela** [comment]
I actually used to have it [setup that way](https://github.com/jacobsalmela/pi-hole/pull/15/files), but we changed it for a few reasons:

- to limit writing to the SD card (reduces the likelihood of corruption)
- to be a respectful netizen by not downloading the entire list needlessly every time `gravity.sh` runs

so I would like to keep it as is and either find a way to increase the memory or come up with a new solution all together.

**Comment by korhadris** [comment]
If I maintain 2. in your list above and decrease file read/writes, can I rearrange some of the intermediate files that are at the end of gravity.sh, in gravity_advanced()? There are some sed sections that are no longer needed, or could be moved, with some of my latest commits. If so, I'd like to store the data from the curl requests to disk, that way $data isn't holding the whole mahakala list in memory at one time. Although, I'd still assume it would still use a bit of memory when it gets to the sort | uniq section later.

**Comment by jacobsalmela** [comment]
If we can increase the swap size to 500 or more, if needed,  we can still limit the writing to the SD card since the swap will only be used when needed.  I was thinking of something like this:
```
dphys-swapfile swapoff
echo -e "CONF_SWAPSIZE=500" > /etc/dphys-swapfile
dphys-swapfile setup
dphys-swapfile swapon
```

**Comment by jacobsalmela** [comment]
I made a more streamline **development** branch so try it out and let me know if you still get the memory allocation error.

https://github.com/jacobsalmela/pi-hole/blob/development/gravity.sh#L47-L70

**Comment by x20mar** [comment]
I'm getting this issue, but I wanted to check if this is just limited to certain versions of the rpi? I have Raspberry Pi 1 Model B (512MB)

**Comment by jacobsalmela** [comment]
I think it is more prevalent on the original B, but it depends on what people have running on their Pi.  I think this is a good all around fix.
