### ISSUE TITLE
gravity.sh: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by shresthassh** [jacobsalmela/pi-hole#39]
I get this error:
pi@rp1 /usr/local/bin $ sudo sh gravity.sh 
gravity.sh: 5: gravity.sh: Syntax error: newline unexpected

This is raspberry pi2 with raspbian
pi@ rp1 /usr/local/bin $ cat /proc/version 
Linux version 3.18.11+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #781 PREEMPT Tue Apr 21 18:02:18 BST 2015

pi@rp1 /usr/local/bin $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 2.00
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2708
Revision	: 0010
Serial		: 0000000040f0a897

pi@rp1 /usr/local/bin $ sudo rm gravity.sh 
pi@rp1 /usr/local/bin $ ls
chronometer.sh  indiecity
pi@rp1 /usr/local/bin $ sudo wget https://github.com/jacobsalmela/pi-hole/blob/master/gravity.sh
--2015-08-27 13:25:31--  https://github.com/jacobsalmela/pi-hole/blob/master/gravity.sh
Resolving github.com (github.com)... 192.30.252.129
Connecting to github.com (github.com)|192.30.252.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `gravity.sh'

    [ <=>                                                                                                                  ] 74,921      --.-K/s   in 0.1s    

2015-08-27 13:25:37 (562 KB/s) - `gravity.sh' saved [74921]

pi@rp1 /usr/local/bin $ sudo sh gravity.sh 
gravity.sh: 5: gravity.sh: Syntax error: newline unexpected
pi@rp1 /usr/local/bin $ ls -ls
total 84
 4 -rwxr-xr-x 1 root staff      1392 Aug 12 22:35 chronometer.sh
76 -rw-r--r-- 1 root staff     74921 Aug 27 13:25 gravity.sh
 4 drwxrwsr-x 2 root indiecity  4096 May  6 18:17 indiecity
pi@rp1 /usr/local/bin $ 
pi@ rp1 /usr/local/bin $ uname -a
Linux eautapi 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux

**Comment by jacobsalmela** [comment]
Try downloading the raw format instead of the regular file:

`https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/gravity.sh`

**Comment by shresthassh** [comment]
pi@ rp1 /usr/local/bin $ sudo wget https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/gravity.sh
--2015-08-27 13:43:06--  https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/gravity.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.40.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.40.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5701 (5.6K) [text/plain]
Saving to: `gravity.sh'

100%[====================================================================================================================>] 5,701       --.-K/s   in 0.006s  

2015-08-27 13:43:11 (987 KB/s) - `gravity.sh' saved [5701/5701]

pi@ rp1 /usr/local/bin $ sudo sh gravity.sh 
gravity.sh: 9: gravity.sh: Syntax error: "(" unexpected
pi@ rp1 /usr/local/bin $

**Comment by jacobsalmela** [comment]
It still works for me.  It looks like you're using `sh` and this is a `bash` script so maybe there is some small difference? Also, are you running Raspbian or something else?

**Comment by shresthassh** [comment]
bash indeed. It works.
Yes, I am using Raspbian.

Thank you for your flash reply.

pi@ rp1 /usr/local/bin $ sudo bash gravity.sh 
** Neutrino emissions detected...
** Current swap size is 100
** Creating more swap space to accomodate large solar masses...
want /var/swap=500MByte, checking existing: deleting wrong size file (104857600), generating swapfile ... of 500MBytes
Getting adaway.org list...
Skipping adblock.gjtech.net list because it does not have any new entries...
Getting adblock.mahakala.is list...

**Comment by jacobsalmela** [comment]
Solid.  Glad it works.
