### ISSUE TITLE
Issue with blank IP address.

### ISSUE THREAD

**Issue by lailoken** [jacobsalmela/pi-hole#4]
I uncommented the line that determined the IP dynamically, and it worked mostly.

But there was one case where it happened to run (via cron) and come up with a blank IP... not sure why or how... but it corrupted the dns config file and broke my entire network.

It may have been due to a temporary problem with my connection or cable.

After that nothing works.

Proposal: Add a check for a blank IP address in the case of automated detection. I've changed to a static IP in the meantime since this is better for my case anyway...

**Comment by jacobsalmela** [comment]
I'm sorry it broke your network!!  I'll look into seeing how to better find the IP and add some error checking.

What happened to the dns file?  Was it the adList.conf or dnsmasq.conf that stopped working?

**Comment by lailoken** [comment]
It was adList.conf

The content of the file had lines:

address=/101com.com/
address=/101order.com/

instead of:

address=/101com.com/192.168.1.101
address=/101order.com/192.168.1.101

Also, it worked again subsequently... seemed to be a problem with powering
on all my devices at the same time.


Regards,
Marius

**Comment by jacobsalmela** [comment]
Has this happened anymore to you?  I'm wondering if it just didn't pick up the address since it wasn't assigned one yet.  Based on your output that you pasted in, the variable was just empty.

**Comment by lailoken** [comment]
Nope it has not happened again, but that was because I changed the dynamic
detection to static. (Since I had my DHCP assign a static IP anyway since
how else would this work as my primary DNS)

Regards,
Marius

**Comment by jacobsalmela** [comment]
I use it as my primary DNS by just having these lines in dnsmasq.conf:
```
no-resolv
server=127.0.0.1
server=8.8.8.8
server=8.8.4.4
```
It seems to work well using the loopback as the first DNS server to query and then falling over to the public Google ones if it is not an ad domain.  That way, it doesn't matter what IP your Pi has.

There was [some discussion](http://jacobsalmela.com/raspberry-pi-block-ads-adtrap/#comment-1745472483) on whether using the loopback was more appropriate or the actual IP of the Pi.

**Comment by jacobsalmela** [comment]
I think this was just an issue of not having an IP address available.  The command works if an IP exists.
