### ISSUE TITLE
DNSmasq fails when starting up: "/etc/pihole/gravity.list" doesn't exist

### ISSUE THREAD

**Issue by Wintaru** [jacobsalmela/pi-hole#40]
My /etc/pihole directory contains 3 files:

LICENSE
list.0.adaway.org.domains
list.1.adblock.gjtech.net.domains

I did the automated setup using DietPi. Any help? Can I just cat these two lists into gravity.list, or is there some finessing involved before the addresses are added?

**Comment by Wintaru** [comment]
More information. I tried running gravity.sh again, and it kept failing when retrieving the list for one of the sites. If I comment out this line:

'http://adblock.mahakala.is/'

It works as far as building gravity.list. However startpar is still reporting a failure starting dnsmasq, and I also noticed an error when the pi was booting:

"starting DNS forwarder and DHCP server: dnsmasqchown: invalid user 'dnsmasq:nogroup'"

**Comment by Wintaru** [comment]
More information. Checking pihole.log I see dnsmasq seems to be doing it's thing, but ads are still being seen. Not sure what to try now.

**Comment by Wintaru** [comment]
Ok I *think* I've got it working. By upping the swap space ala the answer here:

http://raspberrypi.stackexchange.com/questions/70/how-to-set-up-swap-space?newreg=1ac65fccbba04aa2a4bdf9377f41c791

I am able to download the list at mahakala.is and add it to the hosts file. Some FB ads are still getting through but I see them stopping elsewhere so things must be working.

**Comment by jacobsalmela** [comment]
Yeah, increasing the swap fixes it.  I [pushed this fix](https://github.com/jacobsalmela/pi-hole/commit/fa77b7b69da4aaea1f349a015ceeba92514cefac) a few days ago.
