### ISSUE TITLE
How to log requester IP?

### ISSUE THREAD

**Issue by sergiovilar** [jacobsalmela/pi-hole#48]
Hello,

I was taking a look through the [dnsmasq documentation](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) and I would like to log the rquester IP using the `--log-queries=extra` option as described:

```
-q, --log-queries
Log the results of DNS queries handled by dnsmasq. Enable a full cache dump on receipt of SIGUSR1. If the argument "extra" is supplied, ie --log-queries=extra then the log has extra information at the start of each line. This consists of a serial number which ties together the log lines associated with an individual query, and the IP address of the requestor.
```

But when I change my `/etc/dnsmasq.conf` to this:

```
addn-hosts=/etc/pihole/gravity.list
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries=extra
log-facility=/var/log/pihole.log
local-ttl=300
```

And I try to restart using `sudo service dnsmasq restart`, I get this:

````
[FAIL] Restarting DNS forwarder and DHCP server: configuration syntax check failed!
```

Any thoughts that could help me here? 

Thank you!

**Comment by jofrep** [comment]
Hi Sergio,
I confirm the same error in both a raspberry (dnsmasq 2.62)  and in an ubuntu server (dnsmasq 2.52)

I suspect the "extra" facility is only available in the latest dnsmasq version (version 2.75) because the man page in the RPi doesn't show this option.

Jofre

**Comment by sergiovilar** [comment]
Indeed @jofrep. I've installed the 2.75 release manually and now seems to be working.

Would be great if pi-hole could install the latest version of dnsmasq.

**Comment by jacobsalmela** [comment]
Curious, what sort of extra information is provided?  Could you show a snippet of the log?

**Comment by sergiovilar** [comment]
@jacobsalmela just now I've realized that the default log shows the requester IP, closing here.
