### ISSUE TITLE
pi-hole blocking some domains

### ISSUE THREAD

**Issue by sergiovilar** [jacobsalmela/pi-hole#49]
Hello,

pi-hole is blocking some domains, I've added the domains to the `whitelist.txt` file but it doesn't seems to work.

Could someone help me?

**Comment by jacobsalmela** [comment]
First, make sure you run `/usr/local/bin/gravity.sh` so it applies the whitelist.

Next, note that some domains have multiple entries like:
```
adddomain.com
subdomain.addomain.com
www.addomain.com
```
each one needs to be whitelisted.  

Also, some sites display ads from within their own domain, which the Pi-hole will not be able to block without blocking the entire domain.

I will close this for now unless you want to tell me which domain(s) are not being blocked.

**Comment by sergiovilar** [comment]
@jacobsalmela there's no possibility to just use a wildcard?

**Comment by prov3it** [comment]
Dnsmasq doesnt support Wildcards
