### ISSUE TITLE
lighttpd root filepath changed in Raspbian "jessie"

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#50]
The version of `lighttpd` that can be installed via `apt-get` in the latest version of Raspbian ("Jessie"), is 1.4.35 and the root folder has changed.  Instead of the files being in `/var/www` they are in `/var/www/html`.  I will need to update the installer script to detect what version a user is running and then install the files in the correct place.

**Comment by korhadris** [comment]
In your lighttpd.conf file, aren't you setting the path to `/var/www` explicitly?

**Comment by jacobsalmela** [comment]
Yes.  I wonder if it still works as-is.  I'll have to try it out.

**Comment by korhadris** [comment]
I changed my stuff to point to my external hard drive instead of /var/www, and it's been fine so far.

**Comment by jacobsalmela** [comment]
I'm thinking I will just leave it at `/var/www/html/` and users on Wheezy can just adjust the path if they want.

**Comment by jacobsalmela** [comment]
I changed this [here](https://github.com/jacobsalmela/pi-hole/commit/28dd956449bb2eef268846ef77d2d4db50e24a3f) and also in the [automated installer](https://github.com/jacobsalmela/pi-hole/commit/bc3ece778d6d834ba1b2829d8b672b0d710ca2ac).  The Pi-hole now uses `/var/www/html` for  the root folder.
