### ISSUE TITLE
piholeIP not properly used when IPV4 and IPV6 are available

### ISSUE THREAD

**Issue by mospaeda** [jacobsalmela/pi-hole#51]
my conf is RPI2 with interfaces in IPV4 and IPV6 available
the detection code for piholeIP parameter is not working and result in a blank that is added in the accretiondisc.txt instead of the real IP (resulting in a list of domains only with no sink IP)

in my case result of command : hostname -I  is 
192.168.1.55 2a01:e35:xxx:xxx:xxx:xxx:xxx:xxx 2a01:e35:yyy:yyy:yyy:yyy:yyy:yyy
hostname -I |xargs is same output

Should probably select only the 1st IP for copy in accretiondisc.txt

**Comment by jacobsalmela** [comment]
Yeah, that isn't good.  I'll figure some way to better get the IP.

**Comment by korhadris** [comment]
I don't know if the order is always IPV4, then IPV6 (which a cut or awk command would work), but the following sed would keep it regardless of order:

**Comment by korhadris** [comment]
I don't know if the order is always IPV4, then IPV6 (which a cut or awk command would work), but the following sed would keep it regardless of order:
`hostname -I | sed -r -e 's/.*(\b[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b).*/\1/'`

**Comment by parnz** [comment]
I'm also have this issue but I've only one IPv4.

>pi@pidns ~ $ hostname -I |xargs
>192.168.6.212
>pi@pidns ~ $

I've to replace the whitespace in gravity.list about 1.6M lines (Thanks to Ctrl+H for that).

p.s RPi B+ running rasbian jessie :)

**Comment by jacobsalmela** [comment]
I restored the script to [how it used to be](https://github.com/jacobsalmela/pi-hole/commit/6976532ef5b52f3b0c769e35b3071c5decdbb9aa) until a better solution can be devised.

**Comment by jacobsalmela** [comment]
I started some changes [on the development branch](https://github.com/jacobsalmela/pi-hole/blob/development/gravity.sh#L6-L7) to address this issue.  Any feedback is welcome.

**Comment by mospaeda** [comment]
The version in dev is working fine with me (dated 15 oct)
my hostname is : 
192.168.1.55 2a01:e35:xxx:xxx:xxx:xxx:xxx:xxx 2a01:e35:yyy:yyy:yyy:yyy:yyy:yyy
therefore I have 1 IPV4 and 2 IPV6
script successfully extract the IPV4 and the 2nd IPV6
then accretion.txt is created with 2 lines per blocked site

it seems that if some sites are both in blacklist.txt and other lists then they are duplicate entries in accretion.txt (1IPV4 entry + 1 IPV6 entry  twice)

note: I didn't checked yet whitelisting with this version.
