### ISSUE TITLE
Log file grows too large

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#54]
`/var/log/pihole.log` can grow very large, very quickly.  In addition to taking up a bunch of space, it also slows down the Web interface as it parses the file to display statistics.  

I want to keep the log files so there can eventually be some long-term statistics integrated into the Web interface.  So maybe move the log file somewhere else each day and then truncate the log file:

`sudo truncate -s 0 /var/log/pihole.log`

I actually meant to only parse the log file for _today_ 's stats, but forgot to use the `today` variable [in the code](https://github.com/jacobsalmela/AdminLTE/blob/master/index.php#L145).

**Comment by DonLexos** [comment]
Yes, the stats might only show 'today' when you add that in the script, but that does not stop the logfile from growing. Question is do you want to keep all the data in it (elsewhere) or just the totals? I know linux does provide in a logrotation system, but that basicly means moving them over to pihole.log1/log2 etc files. 
http://www.thegeekstuff.com/2010/07/logrotate-examples/

If you only need totals would make more sense to collect them, save them and then purge the logfile.

**Comment by jacobsalmela** [comment]
So there could just be a file (`/etc/pihole/stats` or something)  that saves the totals and then those could be displayed on a long-term graph.

I think I would rather just get rid of the log file because if you have a Pi-hole running for some time and have a small SD card, you would probably run out of space at some point.

**Comment by ggiessen** [comment]
Or add a file (pihole) to /etc/logrotate.d 

/var/log/pihole.log {
    daily
    missingok
    rotate 2 
    notifempty
    delaycompress
    sharedscripts
    postrotate
        [ ! -f /var/run/dnsmasq/dnsmasq.pid ] || kill -USR2 `cat /var/run/dnsmasq/dnsmasq.pid`
    endscript
    create 0644 dnsmasq root
}

**Comment by jacobsalmela** [comment]
So having never used this, I had to look up each option.  But here is a commented version with some additions.  

1. Do you need `compress` in order to use `delaycompress`?

```
/var/log/pihole.log {
    # Rotate the log files daily
    daily

    # Don't return an error if the log file is missing
    missingok

    # Do not rotate if the log file is empty
    notifempty

    # Rotate the log file twice before deleting it
    rotate 2

    # Compress the log file using gzip
    compress

    # Delays compression when some program cannot be told to immediately close it's logfile
	delaycompress

    # Include the date in the rotated log file's name
    dateext

    # The postrotate script will only be run once (after the old
       logs  have  been  compressed), not once for each log which is rotated.
    sharedscripts

    # The  lines  between 'postrotate' and 'endscript' are executed after the log is rotated
    postrotate
        # If dnsmasq is running, kill it using the user defined signal
        [[ ! -f /var/run/dnsmasq/dnsmasq.pid ]] || kill -USR2 cat /var/run/dnsmasq/dnsmasq.pid
    endscript

    # Rotate the original file and create the new file with specified permission, user, and group
    create 0644 dnsmasq root
}
```

**Comment by 3ceepio** [comment]
Thanks for this jacobsalmela, I used the above on my Jessie pi with a small modification as it was throwing errors on the postrotate script:
```
[ ! -f /var/run/dnsmasq/dnsmasq.pid ] || kill -USR2 `cat /var/run/dnsmasq/dnsmasq.pid`
```
I've noted it did not compress the old file (yet) perhaps it only does this on second rotation? Otherwise I've missed something in the config.

**Comment by jacobsalmela** [comment]
I didn't actually test the script above yet; I just threw it together from the documentation.  Thanks for the update.  I'll have to try it out, too.

**Comment by jacobsalmela** [comment]
The log file will no longer need to stored since I have a better solution for storing the stats.  For that reason, I am just going to use `sudo truncate -s 0 /var/log/pihole.log` as a cronjob that runs daily.
![Pi-hole advanced dashboard](http://i.imgur.com/FL4lvNp.png)

**Comment by DonLexos** [comment]
That looks good! Curious how you collect the data for the stats!

**Comment by jacobsalmela** [comment]
This is fixed with #74.  The log file is flushed daily with the use of a pre-made crontab that is added during installation.

**Comment by mnott** [comment]
Could you please put the crontab entry that you would normally have added? I don't see any using crontab -l, and the file keeps growing.

**Comment by DL6ER** [comment]
See my comment of [Discourse](https://discourse.pi-hole.net/t/log-queries/1085)
