### ISSUE TITLE
A few notes on raspbian-jessie

### ISSUE THREAD

**Issue by keithdadkins** [jacobsalmela/pi-hole#56]
For the static ip in jessie (not 100% sure why this distro is recommending configuring static ip's this way, maybe because it's desktop oriented?)

For me to get it to work, I had to ensure the primary interface was set to manual:
```
#/etc/network/interfaces
...
auto eth0
allow-hotplug eth0
iface eth0 inet manual
...

```

I then added the following to the bottom of the default `/etc/dhcpcd.conf` file and rebooted
   (_change 192.168.1.254/24 to your ip/subnet of choice / and use your preferred fallback dns_)
```
#/etc/dhcpcd.conf
...

interface eth0
static ip_address=192.168.1.254/24
static routers=192.168.1.1
static domain_name_servers=8.8.8.8 8.8.4.4
```

The gravity.sh script in the article wrote to `/etc/pihole/gravity.list` and not to `/etc/hosts`, so I added `addn-hosts=/etc/pihole/gravity.list` to fix:
```
# /etc/dnsmasq.conf
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
addn-hosts=/etc/pihole/gravity.list
```
and after a
```
 sudo systemctl restart dnsmasq
```
all is well now... Thanks!

**Comment by jacobsalmela** [comment]
I didn't need the `iface eth0 inet manual` but I haven't tested it extensively.  So far, I have been able to set a static address using the method described here:

http://pi-hole.net/faq/how-do-i-set-a-static-ip-address-in-raspbian-jessie-using-etcdhcpcd-conf/
