### ISSUE TITLE
Reboot needed after installation?

### ISSUE THREAD

**Issue by Giermann** [jacobsalmela/pi-hole#57]
Your script https://github.com/jacobsalmela/pi-hole/blob/master/automated%20install/basic-install.sh ends with rebooting the whole box - is this needed indeed? Why not just restart the services, since they have already been stopped before modifying the config files...?

**Comment by jacobsalmela** [comment]
I remember I put the reboot in there for a specific reason, which eludes me at the moment.  I'll have to look back to see why I have it in there.

**Comment by jacobsalmela** [comment]
This is fixed in #74.  It will restart if the user selects a new IP address.  If they choose to use their current DHCP address, then it simply starts the services without restarting.

**Comment by jacobsalmela** [comment]
This was addressed again in #90 so now a reboot is not even an option, but we will suggest to the user that it might be a good idea.
