### ISSUE TITLE
chronometer.sh runtime error

### ISSUE THREAD

**Issue by arjanv** [jacobsalmela/pi-hole#64]
Hi,
I'm geting a runtime error when running chronometer.sh

Runtime error (func=(main), adr=3): Divide by zero
(standard_in) 1: syntax error

any idea?

**Comment by jacobsalmela** [comment]
You probably forgot to install `bc` (bash calculator), which is needed to do the advanced math.

`sudo apt-get -y install bc`

**Comment by arjanv** [comment]
hi when i do  sudo apt-get -y install bc  i get the message it's allready installed.

**Comment by arjanv** [comment]
don't know whats going wrong, but also when i comment out: 	#tail -f /var/log/pihole.log | awk '/\/etc\/pihole\/gravity.list/ {if ($7 != "address" && $7 != "name" && $7 != "/etc/pihole/gravity.list") print $7; else;}' 

only the word "is" are displayed.
