### ISSUE TITLE
No 1x1 PNG is served?

### ISSUE THREAD

**Issue by ajp2k13** [jacobsalmela/pi-hole#7]
According to commit e1d79ffb0ac2460a4e5b2582ed501e3987e0febf a 1x1 png i served instead of a blank html page but it's not on my install. Do I have to add it myself and if so, how? Did I miss something?

**Comment by jacobsalmela** [comment]
I haven't updated the actual index.html file yet.  I just uploaded the .png so I could test it.  Sorry for the confusion.

**Comment by ajp2k13** [comment]
Ah ok, I see! I thought I missed something.. thanks!

**Comment by jacobsalmela** [comment]
This is fixed in the version released this evening.  You can set many different types of GIFs of varying sizes.
