### ISSUE TITLE
Whitelisting formatting - whitelisting working?

### ISSUE THREAD

**Issue by DonLexos** [jacobsalmela/pi-hole#81]
Hi,

I just learned the latest weekly update blocked me out of (looking at) Google Analytics (analytics.google.com). I should be able to whitelist it by adding a whitelist.txt file in /etc/pi-hole, however I am not sure what format the whitelist should be? Could you give an example?

Thanks! Alex

**Comment by DonLexos** [comment]
Hmm I should have just tried first, anyway here is the solution to my own issue:
^analytics\.google\.com$

Adding it does not allow me to connect though ...

**Comment by DonLexos** [comment]
To add more information, I did whitelist, I restarted the DNSmasq after I ran the gravity.sh script to make sure the whitelist is processed, but a dig to analytics.google.com returns my pihole IP adres instead of the correct one.

**Comment by DonLexos** [comment]
Fixed it, and to add to this for anyone who bumps into the same issue:
whitelisting as a regular domain (analytics.google.com) by adding it to /etc/pihole/whitelist.txt
sudo /etc/init.d/dnsmasq stop
sudo /usr/local/bin/gravity.sh
sudo /etc/init.d/dnsmasq start

**Comment by jacobsalmela** [comment]
Normally, you should be able to add a domain or sub domain (one-per line) to `/etc/pihole/ whitelist.txt` and then run `gravity.sh` to apply it.  Alternatively, the `whitelist.sh` script is also vastly improved and works well for whitelisting domains without having to run the entire `gravity.sh` script again.

Also, you can see these FAQs for more help with whitelisting:

http://pi-hole.net/faq/how-do-i-whitelist-or-blacklist-a-webiste-or-domain/

http://pi-hole.net/faq/why-dont-my-whitelisted-sites-show-ads/
