### ISSUE TITLE
Issue when router is acting as a DNS proxy

### ISSUE THREAD

**Issue by sirajea** [jacobsalmela/pi-hole#83]
My router (Fritz!Box) allows me to set the DNS servers to be used for name resolution so the router acts as a DNS proxy. I use the (local) Raspberry Pi as the DNS server for the router and this works, except on the devices connected to the router the domains it should block do not resolve at all instead of resolving to the Raspberry Pi. When I configure my devices to use the Raspberry Pi as a DNS server directly the domains do resolve. Does anyone else have the same issue?

**Comment by dschaper** [comment]
I wonder if the Fritz is seeing a non-routable local IP address in the responses and is filtering the responses. I know with DNSMasq you can filter private addresses so it won't forward addresses that resolve to private address-space.

**Comment by jofrep** [comment]
I use a Fritz!Box 7490 and could not add a local DNS server. I´m can to set any DNS server but not using a local IP.
See other users having the same problem https://forums.whirlpool.net.au/archive/1835726 <https://forums.whirlpool.net.au/archive/1835726>
I ended using the Raspberry Pi to be a DHCP and DNS server to solve that problem
Regards
Jofre

**Comment by jacobsalmela** [comment]
So is it a Fritz!Box problem, or a Pi-hole problem?  Or a combination of both?

**Comment by jofrep** [comment]
IMHO is a Fritz!Box problem but I’d wait for sirajea to confirm

Acording to the vendor is a “security” feature to prevent rough DNS servers  :-)

**Comment by sirajea** [comment]
@jacobsalmela @jofrep I think it's a Fritz!Box problem. It seems to filter local IP-addresses as @dschaper noted.

**Comment by DonLexos** [comment]
Not sure if it would work but you can try to set it to your WAN ip address and make sure you forward DNS port 53 to your pi internal IP. That way you would use the public (external) IP. This will open your DNS/Pi to others though (but it's worth a try to see if you can have it work like that).

**Comment by jacobsalmela** [comment]
Closing since this seems to be Fritz!Box issue, not Pi-hole.

**Comment by leipert** [comment]
If you have a current FritzOS (at least `6.50`), you can change the DNS (English translations are guessed, as my Fritzbox is in German):

1. Heimnetz (Home Net)
1. Heimnetzübersichte (Home Net Overview)
1. Netzwerkeinstellungen (Network Settings)
1. IPv4-Adressen (IPv4 adresses)
1. Lokaler DNS-Server (local DNS server)

<img width="577" alt="screen shot 2016-05-08 at 11 04 47" src="https://cloud.githubusercontent.com/assets/2906107/15096941/d2a35cb0-150c-11e6-9083-4c726f5fc6b4.png">

Make sure your device refreshes it's DHCP session and the new DNS server is set. I couldn't test it yet with Pi-Hole, as my Raspberry Pi is broken and I am waiting for a new one 💃

**Comment by sirajea** [comment]
@leipert Thanks, will try this as soon as they release the international update!

**Comment by sirajea** [comment]
I just downloaded the international [beta](https://service.avm.de/downloads/beta/fritzbox_7490/english/) update and it's indeed possible to set a local DNS server now. Now I no longer have to configure each device in the network separately to use the Pi-hole. Awesome!

**Comment by Gravesy83** [comment]
This issue is usually solved by either updating to the newest fritz!os, or using the beta firmware on one's fritzbox for the most part.
I have several older models than the one sirajea uses (and the same one), and the DNS settings can be accessed on all of them...
However, i would like to note that some ISP's use modified firmwares that lock the user out of such settings.
