### ISSUE TITLE
Single Go executable web-interface

### ISSUE THREAD

**Issue by girishso** [jacobsalmela/pi-hole#95]
Not really an issue.

I just ported the web interface to Go. https://github.com/girishso/pi-hole-web single executable with all the assets and web server included. No lighttpd or php-fpm required! :)

**Comment by jacobsalmela** [comment]
Pretty awesome!  So this is just the Web interface, not the actual ad-blocking that the Pi-hole does, correct?

**Comment by girishso** [comment]
:)

This is just the web interface (/admin) and the one pixel gif (/) serving code.

**Comment by jacobsalmela** [comment]
Cool.  So if I update my repo for the interface (I have some updates coming), how does yours get updated (if its possible)?  

I was thinking I could add this as an option for people to install the interface separately or if they are making the Pi-hole manually from scratch.

**Comment by girishso** [comment]
Sounds cool.

I will need to update the Go repo to reflect your changes.

**Comment by jacobsalmela** [comment]
OK, cool.  I'll let you know if there are any significant changes.  Thanks again!
